<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="ES-es" xml:lang="ES-es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.335">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Asesor= Javier Rodríguez Barrios">
<meta name="dcterms.date" content="2025-09-04">
<meta name="description" content="Aplicación del índice GSI, de acuerdo a las recomendaciones del par evaluador del manuscrito presentado.">

<title>Asesoría 1. Análisis de parches o vacios de información de diversidad - GSI</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
</style>


<script src="gsi_uraba_resum_files/libs/clipboard/clipboard.min.js"></script>
<script src="gsi_uraba_resum_files/libs/quarto-html/quarto.js"></script>
<script src="gsi_uraba_resum_files/libs/quarto-html/popper.min.js"></script>
<script src="gsi_uraba_resum_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="gsi_uraba_resum_files/libs/quarto-html/anchor.min.js"></script>
<link href="gsi_uraba_resum_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="gsi_uraba_resum_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="gsi_uraba_resum_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="gsi_uraba_resum_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="gsi_uraba_resum_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<style>
    .quarto-title-block .quarto-title-banner {
      background: #66c2a5;
    }
    </style>

<script src="gsi_uraba_resum_files/libs/kePrint-0.0.1/kePrint.js"></script>
<link href="gsi_uraba_resum_files/libs/lightable-0.0.1/lightable.css" rel="stylesheet">

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="styles2.css">
</head>

<body>

<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Asesoría 1. Análisis de parches o vacios de información de diversidad - GSI</h1>
            <p class="subtitle lead">Aplicación del índice GSI, relacionado con vacíos o parches de diversidad a escala espacial en Urabá</p>
                  <div>
        <div class="description">
          Aplicación del índice GSI, de acuerdo a las recomendaciones del par evaluador del manuscrito presentado.
        </div>
      </div>
                </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Autor/a</div>
      <div class="quarto-title-meta-contents">
               <p>Asesor= Javier Rodríguez Barrios </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Fecha de publicación</div>
      <div class="quarto-title-meta-contents">
        <p class="date">September 4, 2025</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Menú flotante</h2>
   
  <ul>
  <li><a href="#requerimiento-del-par-evaluador" id="toc-requerimiento-del-par-evaluador" class="nav-link active" data-scroll-target="#requerimiento-del-par-evaluador">Requerimiento del par evaluador</a></li>
  <li><a href="#área-de-estudio" id="toc-área-de-estudio" class="nav-link" data-scroll-target="#área-de-estudio">Área de Estudio</a></li>
  <li><a href="#indice-de-selección-de-parches---gsi" id="toc-indice-de-selección-de-parches---gsi" class="nav-link" data-scroll-target="#indice-de-selección-de-parches---gsi">Indice de selección de parches - GSI</a>
  <ul>
  <li><a href="#paso-1.-dimensión-de-registros." id="toc-paso-1.-dimensión-de-registros." class="nav-link" data-scroll-target="#paso-1.-dimensión-de-registros.">Paso 1. Dimensión de registros.</a>
  <ul>
  <li><a href="#base-de-datos-utilizada" id="toc-base-de-datos-utilizada" class="nav-link" data-scroll-target="#base-de-datos-utilizada">Base de datos utilizada</a></li>
  </ul></li>
  <li><a href="#paso-2.-dimensión-ambiental" id="toc-paso-2.-dimensión-ambiental" class="nav-link" data-scroll-target="#paso-2.-dimensión-ambiental">Paso 2. Dimensión Ambiental</a></li>
  <li><a href="#paso-3.-dimensión-complementaria" id="toc-paso-3.-dimensión-complementaria" class="nav-link" data-scroll-target="#paso-3.-dimensión-complementaria">Paso 3. Dimensión complementaria</a></li>
  <li><a href="#paso-4.-índice-de-parches---gsi" id="toc-paso-4.-índice-de-parches---gsi" class="nav-link" data-scroll-target="#paso-4.-índice-de-parches---gsi">Paso 4. Índice de parches - GSI</a>
  <ul>
  <li><a href="#tabulación-de-las-áreas-de-parches-del-gsi" id="toc-tabulación-de-las-áreas-de-parches-del-gsi" class="nav-link" data-scroll-target="#tabulación-de-las-áreas-de-parches-del-gsi">Tabulación de las áreas de parches del GSI</a></li>
  <li><a href="#mapas-con-los-estimadores-calculados---boot-y-jack" id="toc-mapas-con-los-estimadores-calculados---boot-y-jack" class="nav-link" data-scroll-target="#mapas-con-los-estimadores-calculados---boot-y-jack"><strong>Mapas con los estimadores calculados - Boot y Jack</strong></a></li>
  </ul></li>
  </ul></li>
  </ul>
</nav>
</div>
<main class="content quarto-banner-title-block" id="quarto-document-content">




<hr>
<section id="requerimiento-del-par-evaluador" class="level2">
<h2 class="anchored" data-anchor-id="requerimiento-del-par-evaluador">Requerimiento del par evaluador</h2>
<ul>
<li><p>5.) Incluir <strong>mapas para presentar el número de especies y registros</strong> representados en la base de datos, más allá de concentrarse en diagrama de barras.</p>
<p>R./ Mapas 1 y 2 de este reporte. Completar con una tabla que relaciones registros y especies por municipios, porque el mapa 2 solo relaciona a las 20 especies más abundantes, para no saturarlo.</p></li>
<li><p>6.) A partir de los registros proponer algunos <strong>modelos de interpolación de la riqueza,</strong> esto si se quiere indicar cuál es la <strong>riqueza potencial del área de estudio</strong> (Ejemplo: <a href="http://www.scielo.org.co/scielo.php?script=sci_arttext&amp;pid=S0366-52322021000200247" class="uri">http://www.scielo.org.co/scielo.php?script=sci_arttext&amp;pid=S0366-52322021000200247</a>; <a href="https://github.com/PEM-Humboldt/gsi_analysis/blob/main/3_Complementarity%20dimesion.R" class="uri">https://github.com/PEM-Humboldt/gsi_analysis/blob/main/3_Complementarity%20dimesion.R</a>).</p>
<p>R./Interpólación de la riqueza ya se hizo: <strong>Propuesta de Chao et al.&nbsp;en 4 pasos</strong> (<a href="https://javier-2712.github.io/Manuscritos/4.bio.lenin/alfa.uraba.html#diversidad-alfa---propuesta-de-chao-et-al.-2020">enlace</a>).</p>
<p>R./ La referencia del <strong>GSI</strong> se enfoca es en los vacíos de información (parches) a nivel espacial (entre municipios), es el enfoque de este reporte.</p></li>
<li><p>7.) <strong>Las conclusiones se deben orientar a la disponibilidad de datos</strong>, más que a la riqueza de especies, ya que los muestreos no son homogeneos.</p>
<p>R./ Tener en cuenta el resultado del <strong>paso 4 de este reporte</strong>, en especial la <strong>tabla</strong> (<a href="#tbl-tbl1">Tabla&nbsp;1</a>), que relaciona cantidad de área por muestrear en cada municipio, como resultado del índice GSI.</p></li>
</ul>
<hr>
</section>
<section id="área-de-estudio" class="level2">
<h2 class="anchored" data-anchor-id="área-de-estudio">Área de Estudio</h2>
<div class="cell">

</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-fig1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="gsi_uraba_resum_files/figure-html/fig-fig1-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Figura&nbsp;1: Área de estudio. Lo colores representan el número y distribución de los registros de especies relacionados.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>Top 20 de las especies con más registros</p>
<div class="cell">

</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-fig2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="gsi_uraba_resum_files/figure-html/fig-fig2-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Figura&nbsp;2: Top 20 de las especies con mayor número de registros.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<hr>
</section>
<section id="indice-de-selección-de-parches---gsi" class="level2">
<h2 class="anchored" data-anchor-id="indice-de-selección-de-parches---gsi">Indice de selección de parches - GSI</h2>
<p>Este ínice es pruesto por el Instituto von Humboldt (<a href="#0">enlace</a>), basado en algunos referentes como <a href="http://www.biodiversity-plants.de/biodivers_ecol/article_meta.php?DOI=10.7809/b-e.00057">García Márquez et al.&nbsp;(2012)</a> y <a href="https://onlinelibrary.wiley.com/doi/full/10.1111/ddi.13137">Aguiar et al.&nbsp;(2020)</a>. El GSI se enfoca en la idenificación de zonas con información faltante de registros de especies (parches), generando propuestas de implementación de mayores esfuerzos de muestreo, incorporando el análisis de densidad de registros, capas climáticas (ambientales). El GSI muestra valores entre 0 y 1, siendo los valores iguales o cercanos a 1, los que exigen mayor representación o esfuerzos de muestreo.</p>
<p>El siguiente procedimiento, sigue la propuesta del Humboldt, basado en 4 pasos:</p>
<p><strong>1_Record_dimension</strong></p>
<p><strong>2_Ambiental_dimension</strong></p>
<p><strong>3_Complementarity dimension</strong></p>
<p><strong>4_GSI</strong></p>
<hr>
<section id="paso-1.-dimensión-de-registros." class="level3">
<h3 class="anchored" data-anchor-id="paso-1.-dimensión-de-registros.">Paso 1. Dimensión de registros.</h3>
<p>Se cosntruirá una <strong>superficie continua de intensidad de muestreo</strong> (densidad de registros) a <strong>1 km</strong> para el <strong>Urabá antioqueño</strong>, usando los registros de especies o las ocurrencias georreferenciadas. Luego, <strong>reescalarla a [0,1]</strong> y derivar una <strong>máscara de áreas muy submuestreadas</strong> (percentil 10). Esto es la “capa de esfuerzo” que después se cruza con las otras dimensiones del <strong>GSI</strong> en el resto de pasos.</p>
<p>Los objtivos de este paso se orientan en (1) <strong>Cuantificar y mapear</strong> dónde se ha muestreado más/menos dentro de Urabá para no confundir vacíos de datos con ausencia de registros. (2) <strong>Identificar vacíos de información</strong> (p10) que ayuden a planear salidas y que, más adelante, <strong>ponderen</strong> la combinación de dimensiones del GSI.</p>
<div class="cell">

</div>
<section id="base-de-datos-utilizada" class="level4">
<h4 class="anchored" data-anchor-id="base-de-datos-utilizada">Base de datos utilizada</h4>
<div class="cell">
<div class="cell-output-display">

<div style="border: 1px solid #ddd; padding: 0px; overflow-y: scroll; height:320px; overflow-x: scroll; width:100%; "><table class="table table-striped table-condensed" style="font-size: 11px; width: auto !important; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">Resumen de datos (primeras 6 filas)</caption>
 <thead>
  <tr>
   <th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;"> ID </th>
   <th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;"> lat </th>
   <th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;"> lon </th>
   <th style="text-align:left;position: sticky; top:0; background-color: #FFFFFF;"> kingdom </th>
   <th style="text-align:left;position: sticky; top:0; background-color: #FFFFFF;"> phylum </th>
   <th style="text-align:left;position: sticky; top:0; background-color: #FFFFFF;"> Grupo </th>
   <th style="text-align:left;position: sticky; top:0; background-color: #FFFFFF;"> class1 </th>
   <th style="text-align:left;position: sticky; top:0; background-color: #FFFFFF;"> class </th>
   <th style="text-align:left;position: sticky; top:0; background-color: #FFFFFF;"> order_ </th>
   <th style="text-align:left;position: sticky; top:0; background-color: #FFFFFF;"> family </th>
   <th style="text-align:left;position: sticky; top:0; background-color: #FFFFFF;"> genus </th>
   <th style="text-align:left;position: sticky; top:0; background-color: #FFFFFF;"> species </th>
   <th style="text-align:left;position: sticky; top:0; background-color: #FFFFFF;"> stateProvi </th>
   <th style="text-align:left;position: sticky; top:0; background-color: #FFFFFF;"> verbatimSc </th>
   <th style="text-align:left;position: sticky; top:0; background-color: #FFFFFF;"> Dpto </th>
   <th style="text-align:left;position: sticky; top:0; background-color: #FFFFFF;"> Municipio </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 7.666700 </td>
   <td style="text-align:right;"> -76.67920 </td>
   <td style="text-align:left;"> Animalia </td>
   <td style="text-align:left;"> Chordata </td>
   <td style="text-align:left;"> A </td>
   <td style="text-align:left;"> Amphibia </td>
   <td style="text-align:left;"> Amphibia </td>
   <td style="text-align:left;"> Anura </td>
   <td style="text-align:left;"> Leptodactylidae </td>
   <td style="text-align:left;"> Leptodactylus </td>
   <td style="text-align:left;"> Leptodactylus savagei </td>
   <td style="text-align:left;"> Antioquia </td>
   <td style="text-align:left;"> Leptodactylus savagei </td>
   <td style="text-align:left;"> ANTIOQUIA </td>
   <td style="text-align:left;"> Chigorodó </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 2 </td>
   <td style="text-align:right;"> 7.824057 </td>
   <td style="text-align:right;"> -77.12531 </td>
   <td style="text-align:left;"> Animalia </td>
   <td style="text-align:left;"> Chordata </td>
   <td style="text-align:left;"> A </td>
   <td style="text-align:left;"> Aves </td>
   <td style="text-align:left;"> Aves </td>
   <td style="text-align:left;"> Passeriformes </td>
   <td style="text-align:left;"> Thamnophilidae </td>
   <td style="text-align:left;"> Thamnophilus </td>
   <td style="text-align:left;"> Thamnophilus atrinucha </td>
   <td style="text-align:left;"> Antioquia </td>
   <td style="text-align:left;"> Thamnophilus atrinucha </td>
   <td style="text-align:left;"> ANTIOQUIA </td>
   <td style="text-align:left;"> Turbo </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 3 </td>
   <td style="text-align:right;"> 7.805023 </td>
   <td style="text-align:right;"> -77.12233 </td>
   <td style="text-align:left;"> Animalia </td>
   <td style="text-align:left;"> Chordata </td>
   <td style="text-align:left;"> A </td>
   <td style="text-align:left;"> Aves </td>
   <td style="text-align:left;"> Aves </td>
   <td style="text-align:left;"> Accipitriformes </td>
   <td style="text-align:left;"> Cathartidae </td>
   <td style="text-align:left;"> Cathartes </td>
   <td style="text-align:left;"> Cathartes burrovianus </td>
   <td style="text-align:left;"> Antioquia </td>
   <td style="text-align:left;"> Cathartes burrovianus </td>
   <td style="text-align:left;"> ANTIOQUIA </td>
   <td style="text-align:left;"> Turbo </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 4 </td>
   <td style="text-align:right;"> 7.805023 </td>
   <td style="text-align:right;"> -77.12233 </td>
   <td style="text-align:left;"> Animalia </td>
   <td style="text-align:left;"> Chordata </td>
   <td style="text-align:left;"> A </td>
   <td style="text-align:left;"> Aves </td>
   <td style="text-align:left;"> Aves </td>
   <td style="text-align:left;"> Piciformes </td>
   <td style="text-align:left;"> Picidae </td>
   <td style="text-align:left;"> Melanerpes </td>
   <td style="text-align:left;"> Melanerpes rubricapillus </td>
   <td style="text-align:left;"> Antioquia </td>
   <td style="text-align:left;"> Melanerpes rubricapillus </td>
   <td style="text-align:left;"> ANTIOQUIA </td>
   <td style="text-align:left;"> Turbo </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 5 </td>
   <td style="text-align:right;"> 7.805023 </td>
   <td style="text-align:right;"> -77.12233 </td>
   <td style="text-align:left;"> Animalia </td>
   <td style="text-align:left;"> Chordata </td>
   <td style="text-align:left;"> A </td>
   <td style="text-align:left;"> Aves </td>
   <td style="text-align:left;"> Aves </td>
   <td style="text-align:left;"> Suliformes </td>
   <td style="text-align:left;"> Phalacrocoracidae </td>
   <td style="text-align:left;"> Phalacrocorax </td>
   <td style="text-align:left;"> Phalacrocorax brasilianus </td>
   <td style="text-align:left;"> Antioquia </td>
   <td style="text-align:left;"> Nannopterum brasilianum </td>
   <td style="text-align:left;"> ANTIOQUIA </td>
   <td style="text-align:left;"> Turbo </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 6 </td>
   <td style="text-align:right;"> 7.805023 </td>
   <td style="text-align:right;"> -77.12233 </td>
   <td style="text-align:left;"> Animalia </td>
   <td style="text-align:left;"> Chordata </td>
   <td style="text-align:left;"> A </td>
   <td style="text-align:left;"> Aves </td>
   <td style="text-align:left;"> Aves </td>
   <td style="text-align:left;"> Passeriformes </td>
   <td style="text-align:left;"> Thraupidae </td>
   <td style="text-align:left;"> Ramphocelus </td>
   <td style="text-align:left;"> Ramphocelus dimidiatus </td>
   <td style="text-align:left;"> Antioquia </td>
   <td style="text-align:left;"> Ramphocelus dimidiatus </td>
   <td style="text-align:left;"> ANTIOQUIA </td>
   <td style="text-align:left;"> Turbo </td>
  </tr>
</tbody>
</table></div>

</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Registros en Urabá: 6887 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>png 
  2 </code></pre>
</div>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="https://javier-2712.github.io/Manuscritos/4.bio.lenin/Vac_dens_rescal_1km_Uraba.png" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">Figura 3: Mapa de densidad de registros de especies.</figcaption><p></p>
</figure>
</div>
<p>En el mapa se logra visualizar un tipo de <strong>hotspot central</strong> (azul oscuro) que coincide con el <strong>eje Turbo–Apartadó–Carepa–Chigorodó</strong>, donde se concentra el mayor número de registros o de esfuerzo de muestreo. Hacia los <strong>bordes, del nororiente (Arboletes / San Pedro) y del sur (Mutatá)</strong> la densidad cae gradualmente (tonos claros), indicando <strong>menor esfuerzo o submuestreo</strong>.</p>
<p>En este sentido, donde la densidad es alta (hotspot) el índice <strong>GSI será bajo</strong> (parche o brecha menor) en las periferias con densidad baja y <strong>será alto</strong> (brecha mayor, con vacíos de información). Esto se complementará con el resto de pasos del GSI.</p>
<hr>
</section>
</section>
<section id="paso-2.-dimensión-ambiental" class="level3">
<h3 class="anchored" data-anchor-id="paso-2.-dimensión-ambiental">Paso 2. Dimensión Ambiental</h3>
<p>En este paso se evalúa qué tan bien está <strong>representado el espacio ambiental</strong> de Urabá por los registros de especies del estudio. Para ello se compara a las condiciones ambientales alrededor de las presencias vs.&nbsp;un conjunto de puntos de fondo (pseudo-ausencias) muestreados dentro del <strong>AOI</strong> pero <strong>lejos de las presencias</strong>. El AOI (área de interes / área de estudio) es un procedimiento cartográfico que acota o ajusta a toda el área de estudio para el cálculo del GSI a lo largo de los cuatro pasos. Para este caso, el AOI une a los 9 municipios. El resultado es un raster continuo con valores 0–1:</p>
<ul>
<li><p>Valores <strong>altos</strong> = ambientes bien cubiertos por los datos.</p></li>
<li><p>Valores <strong>bajos</strong> = ambientes poco representados (potenciales brechas).</p></li>
<li><p><strong>Variables ambientales</strong>: WorldClim BIO (subconjunto sin alta colinealidad), <strong>elevación</strong> y <strong>pendiente</strong>, recortadas al AOI.</p></li>
<li><p><strong>Modelado</strong>: GLM binomial (<em>sp</em>∈{0,1}) con <strong>selección stepAIC</strong>. Se evalúa con una partición tipo <em>hold-out</em> (AUC).</p></li>
</ul>
<p>El objetivo consiste en construir una <strong>capa de representatividad ambiental</strong> robusta y alineada al grid del Paso 1, que luego se combinará con las otras dimensiones del GSI. Esta capa ayuda a identificar <strong>ambientes</strong> –no solo lugares – que requieren mayor esfuerzo de muestreo.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Registros en Urabá: 6887 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>png 
  2 </code></pre>
</div>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="https://javier-2712.github.io/Manuscritos/4.bio.lenin/ambiental_dimension_GSI_rescal_Uraba_aligned.png" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">Figura 4: Mapa de representación ambiental de los registros de especies</figcaption><p></p>
</figure>
</div>
<p>En el mapa, los colores <strong>azules</strong> indican valores altos (ambientes <strong>bien representados</strong> por los datos o registros) y los <strong>amarillos</strong> valores bajos (ambientes <strong>poco representados o con mayores brechas</strong>).</p>
<ul>
<li><p>Se observan <strong>valores altos (azules)</strong> en gran parte del occidente y sur del Urabá, lo que indica que esas combinaciones ambientales están bien cubiertas por los registros (coincide con la franja central y sur ampliamente muestreada del <strong>Paso 1</strong>).</p></li>
<li><p>Se distinguen <strong>valores bajos (claros)</strong> en el <strong>nororiente</strong> (hacia Arboletes / San Pedro de Urabá) y algunos sectores costeros y orientales. Esas zonas combinan condiciones climáticas/altitudinales menos representadas en la base, por lo que <strong>aportan brecha ambiental</strong>.</p></li>
<li><p>El reescalado por cuantiles evita que la capa quede “plana” y facilita ubicar parches claros que, más adelante, <strong>elevarán el GSI</strong> (En el índice, ambientes bien representados tienden a <strong>reducir</strong> la brecha o parche; ambientes poco representados la <strong>aumentan</strong>).</p></li>
<li><p><strong>Calidad del ajuste - AUC</strong>: Se puede revisar el <strong>AUC</strong> impreso por el script. Como guía, AUC estándar, donde &gt; 0.7 = aceptable, &gt; 0.8 = bueno. AUC define que tam bien el modelo separa a las presencias de las ausencias, para todos los umbrales posibles del score.</p></li>
</ul>
<hr>
</section>
<section id="paso-3.-dimensión-complementaria" class="level3">
<h3 class="anchored" data-anchor-id="paso-3.-dimensión-complementaria">Paso 3. Dimensión complementaria</h3>
<p>En este tercer paso, se utilizan dos estimadores no paramétricos de riqueza de especies (Bootstrap y Jackknife 1), para evaluar <strong>qué tan completo</strong> es el inventario. El resultado es un raster por método con valores entre <strong>[0–1]</strong>: cercano a <strong>1</strong> = alta <strong>completitud</strong> (poca brecha); cercano a <strong>0</strong> = baja <strong>completitud</strong> (mayor brecha potencial).</p>
<p>El objetivo de este paso, consiste en detectar celdas donde, dado lo observado, <strong>faltan especies por registrar</strong> (baja completitud) y, por tanto, <strong>tienen mayor potencial de aportar nuevos registros</strong> si se prioriza el esfuerzo de muestreo en campo.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="gsi_uraba_resum_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Los mapas muestran valores <strong>altos de completitud</strong> (amarillos) en el <strong>corredor central</strong> (p.&nbsp;ej., entorno Apartadó–Carepa–Chigorodó–Turbo), donde hay <strong>más especies y repeticiones por celda</strong>.</p>
<p>Hacia <strong>bordes y sectores periféricos</strong> (nororiente: Arboletes/San Pedro de Urabá; extremo sur en Mutatá; franjas costeras) aparecen <strong>valores medios</strong> y algunos <strong>bajos</strong> (más verde en Jackknife), indicando <strong>mayor brecha potencial</strong> allí.</p>
<p><strong>Bootstrap vs.&nbsp;Jackknife</strong>: los patrones espaciales son muy similares, pero <strong>Jackknife es más conservador</strong> (tiende a dar completitudes más bajas, rango más amplio; en su salida llega ~0.58), por lo que realza mejor las áreas con brecha.</p>
<p>Interpretación visual (paleta YlGnBu):</p>
<ul>
<li><p><strong>Amarillo (≈1)</strong>: inventario local <strong>bastante completo</strong>; menor ganancia esperada por más muestreo.</p></li>
<li><p><strong>Verde–azul (≈0.6–0.8)</strong>: <strong>faltan especies</strong>; celdas candidatas para reforzar.</p></li>
<li><p><strong>Gris</strong>: <strong>sin datos</strong> en la celda (la dimensión de densidad ya las prioriza).</p></li>
</ul>
<hr>
</section>
<section id="paso-4.-índice-de-parches---gsi" class="level3">
<h3 class="anchored" data-anchor-id="paso-4.-índice-de-parches---gsi">Paso 4. Índice de parches - GSI</h3>
<p>En este cuarto y últomo paso, se integran las tres dimensiones construidas en los pasos 1–3 —<strong>densidad de registros</strong>, <strong>ambiente</strong> y <strong>complementariedad</strong> — para obtener dos superficies finales del índice <strong>GSI</strong>: una basada en el estimador <span class="math inline">\(Bootstrap\)</span> y otra en <span class="math inline">\(Jackknife\)</span>. Cada capa se reescala, se <strong>alinea</strong> a la grilla de 1 km y luego se combina como:</p>
<p><span class="math display">\[GSI=\frac{3 - \text{DENSIDAD} - \text{AMBIENTE} - \text{COMPLEMENTARIEDAD}}{3}\]</span> De modo que <strong>valores altos</strong> indican <strong>mayor brecha</strong> (prioridad de muestreo). Finalmente se generan: <span class="math inline">\(GeoTIFF\)</span> (float32) y <strong>máscaras Top 10 %</strong> (priorización) con su <strong>área (km²)</strong> y un <strong>mapa de consenso</strong> (solapamiento <span class="math inline">\(BOOT∩JACK\)</span> = Mapa Top 10%).</p>
<p>En este sentido, se generan mapas operativos que identifiquen <strong>dónde muestrear primero</strong> en el Urabá, priorizando las celdas con mayor <strong>brecha</strong> simultánea en: (i) baja densidad de datos, (ii) ambientes poco representados y (iii) composición no cubierta, y entregando <strong>polígonos/áreas</strong> cuantificables para la planificación de salidas de campo paramuestrear.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Área top10% — BOOT: 114 km2 | JACK: 114 km2</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Solapamiento BOOT∩JACK (top10%): 99.8 km²</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>png 
  2 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>png 
  2 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Listo:
-  E:/Artículos/Lenin3/GSI_Index_Urabá/4_GSI/GSI_BOOT_Uraba_mpios.png 
-  E:/Artículos/Lenin3/GSI_Index_Urabá/4_GSI/GSI_JACK_Uraba_mpios.png </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>png 
  2 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>png 
  2 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>png 
  2 </code></pre>
</div>
</div>
<section id="tabulación-de-las-áreas-de-parches-del-gsi" class="level4">
<h4 class="anchored" data-anchor-id="tabulación-de-las-áreas-de-parches-del-gsi">Tabulación de las áreas de parches del GSI</h4>
<p>La tabla es la cuantificación de los parches o zonas por muestrear, definidos por el GSI y que fueron mapeados.</p>
<div id="tbl-tbl1" class="cell tbl-parent quarto-layout-panel anchored" data-tbl-caption="Relación de áreas por intensificar el esfuerzo de muestreo, de acuerdo a los resultados de índice de brechas GSI">
<div class="panel-caption table-caption">
<p>Tabla&nbsp;1: <strong>?(caption)</strong></p>
</div>
<div class="quarto-layout-row quarto-layout-valign-top">
<div id="tbl-tbl1-1" class="quarto-layout-cell quarto-layout-cell-subref anchored" data-ref-parent="tbl-tbl1" style="flex-basis: 100.0%;justify-content: center;">

<table class=" lightable-classic" style="font-family: &quot;Arial Narrow&quot;, &quot;Source Sans Pro&quot;, sans-serif; width: auto !important; margin-left: auto; margin-right: auto;">
<caption>(a) % de parches o área por muestrear</caption>
 <thead>
  <tr>
   <th style="text-align:right;"> ID </th>
   <th style="text-align:right;"> zid </th>
   <th style="text-align:right;"> area_km2 </th>
   <th style="text-align:right;"> % </th>
   <th style="text-align:left;"> Localidad </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 8 </td>
   <td style="text-align:right;"> 36.9 </td>
   <td style="text-align:right;"> 36.3 </td>
   <td style="text-align:left;"> San Pedro de Urabá </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 2 </td>
   <td style="text-align:right;"> 9 </td>
   <td style="text-align:right;"> 28.9 </td>
   <td style="text-align:right;"> 28.4 </td>
   <td style="text-align:left;"> Turbo </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 3 </td>
   <td style="text-align:right;"> 5 </td>
   <td style="text-align:right;"> 17.0 </td>
   <td style="text-align:right;"> 16.7 </td>
   <td style="text-align:left;"> Mutatá </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 4 </td>
   <td style="text-align:right;"> 2 </td>
   <td style="text-align:right;"> 11.0 </td>
   <td style="text-align:right;"> 10.8 </td>
   <td style="text-align:left;"> Arboletes </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 5 </td>
   <td style="text-align:right;"> 6 </td>
   <td style="text-align:right;"> 4.0 </td>
   <td style="text-align:right;"> 3.9 </td>
   <td style="text-align:left;"> Necoclí </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 6 </td>
   <td style="text-align:right;"> 4 </td>
   <td style="text-align:right;"> 3.0 </td>
   <td style="text-align:right;"> 2.9 </td>
   <td style="text-align:left;"> Chigorodó </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 7 </td>
   <td style="text-align:right;"> 7 </td>
   <td style="text-align:right;"> 1.0 </td>
   <td style="text-align:right;"> 1.0 </td>
   <td style="text-align:left;"> San Juan de Urabá </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 8 </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 0.0 </td>
   <td style="text-align:right;"> 0.0 </td>
   <td style="text-align:left;"> Apartadó </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 9 </td>
   <td style="text-align:right;"> 3 </td>
   <td style="text-align:right;"> 0.0 </td>
   <td style="text-align:right;"> 0.0 </td>
   <td style="text-align:left;"> Carepa </td>
  </tr>
</tbody>
</table>

</div>
</div>
</div>
</section>
<section id="mapas-con-los-estimadores-calculados---boot-y-jack" class="level4">
<h4 class="anchored" data-anchor-id="mapas-con-los-estimadores-calculados---boot-y-jack"><strong>Mapas con los estimadores calculados - Boot y Jack</strong></h4>
<div class="cell">
<div class="cell-output-display">
<p><img src="gsi_uraba_resum_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<ul>
<li><p><strong>Patrón espacial</strong> (en BOOT y JACK):</p>
<ul>
<li><p><strong>GSI bajo</strong> (colores claros en los mapas) en el <strong>corredor central</strong> más muestreado (eje Apartadó–Carepa–Chigorodó y alrededores).</p></li>
<li><p><strong>GSI medio–alto</strong> en <strong>bordes</strong> y zonas menos cubiertas:</p>
<ul>
<li><p><strong>Nororiente</strong> (San Pedro de Urabá / Arboletes): parches concentrados y valores altos.</p></li>
<li><p><strong>Costa</strong> (Necoclí y franjas litorales) con núcleos dispersos.</p></li>
<li><p><strong>Sur</strong> (Mutatá y cola meridional) con clústeres medianos.</p></li>
</ul></li>
</ul></li>
<li><p><strong>Concordancia de estimadores</strong>: BOOT y JACK muestran estructuras muy similares; <strong>JACK</strong> tiende a <strong>realzar picos</strong> (ligeramente mayor máximo: ~0.79 vs ~0.73), lo que respalda usar el <strong>mapa de</strong> <strong>consenso</strong> que se muestra a continuación.</p></li>
</ul>
<!-- -->
<ul>
<li><strong>Dónde empezar (aumentar esfuerzos de muestreos de inventarios)</strong>:
<ul>
<li><p>Si se busca <strong>máxima robustez</strong>, comenzar por el <strong>solapamiento BOOT∩JACK</strong> (101.8 km²).</p></li>
<li><p>Si se requiere <strong>masa crítica por sitio</strong>, usar el inventario de <strong>parches</strong> (el mayor ≈ 11 km²) para seleccionar <strong>4–6 clústeres</strong> y asignar esfuerzo por accesibilidad.</p></li>
<li><p><strong>Por municipio</strong> (consenso): mayor área prioritaria en <strong>San Pedro de Urabá (~36.9 km²)</strong>, <strong>Turbo (~28.9 km²)</strong> y <strong>Mutatá (~17 km²)</strong>; aportes menores en Arboletes y Necoclí; <strong>casi nulo</strong> en Apartadó/Carepa (coincide con buena cobertura previa).</p></li>
</ul></li>
</ul>
<!-- -->
<ul>
<li><p><strong>Contexto ecológico</strong>: el índice GSI está captando una <strong>brecha de información</strong>, sin “riqueza” <em>per se,</em> a zonas con <strong>pocos datos y ambientes/composición poco representados</strong> aparecen con GSI alto, lo que <strong>optimiza</strong> nuevas campañas para <strong>cerrar vacíos de inventarios</strong>.</p></li>
<li><p>Recomendación para el manuscrito: mostrar (i) los mapas <strong>GSI_BOOT</strong> y <strong>GSI_JACK</strong> anteriores y (ii) el <strong>mapa de concenso</strong> que sigue a continuación con <strong>Top 10 %</strong> de cada uno (JACK y BOOT) <strong>más</strong> el <strong>solapamiento</strong>.</p></li>
</ul>
<p><strong>Mapa de concenso por solapamiento de BOOT y JACK.</strong></p>
<ul>
<li><p><strong>Patrón espacial:</strong> los parches TOP 10 % se concentran en los <strong>bordes menos muestreados</strong>:<br>
<strong>nororiente</strong> (Arboletes–San Pedro de Urabá), tramos de la <strong>franja costera</strong> y el <strong>extremo sur</strong> (Mutatá).<br>
En el eje central <strong>Turbo–Apartadó–Carepa–Chigorodó</strong> aparecen pocos parches → esa zona ya tiene <strong>buena cobertura</strong> (bajo GSI).</p></li>
<li><p><strong>BOOT vs JACK:</strong> coinciden mucho; JACK suele marcar picos muy puntuales y BOOT incluye celdas adyacentes en algunos sectores. Aun así, ambos suman ~<strong>114 km²</strong> cada uno en top 10 %.</p></li>
</ul>
<div class="cell">
<div class="cell-output-display">
<div id="fig-fig4" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="gsi_uraba_resum_files/figure-html/fig-fig4-1.png" class="img-fluid figure-img" width="940"></p>
<p></p><figcaption class="figure-caption">Figura&nbsp;3: Mapa de solapamiento de los mapas BOOT y JACK</figcaption><p></p>
</figure>
</div>
</div>
</div>
</section>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copiado");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copiado");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>