<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="EN-en" xml:lang="EN-en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.335">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Javier Rodríguez Barrios">
<meta name="dcterms.date" content="2024-12-14">
<meta name="description" content="Análisis de datos de diversidad alfa de peces estuarinos y su relación con condiciones ambientales.">

<title>Asesoría 2. Análisis de diversidad alfa</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
</style>


<script src="alfa.eng1peces_files/libs/clipboard/clipboard.min.js"></script>
<script src="alfa.eng1peces_files/libs/quarto-html/quarto.js"></script>
<script src="alfa.eng1peces_files/libs/quarto-html/popper.min.js"></script>
<script src="alfa.eng1peces_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="alfa.eng1peces_files/libs/quarto-html/anchor.min.js"></script>
<link href="alfa.eng1peces_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="alfa.eng1peces_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="alfa.eng1peces_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="alfa.eng1peces_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="alfa.eng1peces_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<style>
    .quarto-title-block .quarto-title-banner {
      background: #2b8cbe;
    }
    </style>

<script src="alfa.eng1peces_files/libs/kePrint-0.0.1/kePrint.js"></script>
<link href="alfa.eng1peces_files/libs/lightable-0.0.1/lightable.css" rel="stylesheet">


<link rel="stylesheet" href="stile-justify.css">
</head>

<body>

<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Asesoría 2. Análisis de diversidad alfa</h1>
            <p class="subtitle lead">Diversidad alfa con datos peces estuarinos</p>
                  <div>
        <div class="description">
          Análisis de datos de diversidad alfa de peces estuarinos y su relación con condiciones ambientales.
        </div>
      </div>
                </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Javier Rodríguez Barrios </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">December 14, 2024</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Menú flotante</h2>
   
  <ul>
  <li><a href="#resumen" id="toc-resumen" class="nav-link active" data-scroll-target="#resumen">Resumen</a></li>
  <li><a href="#cargar-bases-de-datos" id="toc-cargar-bases-de-datos" class="nav-link" data-scroll-target="#cargar-bases-de-datos">Cargar bases de datos</a></li>
  <li><a href="#datos-biológicos" id="toc-datos-biológicos" class="nav-link" data-scroll-target="#datos-biológicos">Datos biológicos</a>
  <ul>
  <li><a href="#elipses" id="toc-elipses" class="nav-link" data-scroll-target="#elipses">Elipses</a></li>
  </ul></li>
  <li><a href="#datos-ambientales" id="toc-datos-ambientales" class="nav-link" data-scroll-target="#datos-ambientales">Datos ambientales</a>
  <ul>
  <li><a href="#elipses-1" id="toc-elipses-1" class="nav-link" data-scroll-target="#elipses-1">Elipses</a></li>
  <li><a href="#relación-ambientales-y-taxones" id="toc-relación-ambientales-y-taxones" class="nav-link" data-scroll-target="#relación-ambientales-y-taxones">Relación ambientales y taxones</a></li>
  <li><a href="#figuras-de-cajas" id="toc-figuras-de-cajas" class="nav-link" data-scroll-target="#figuras-de-cajas">Figuras de Cajas</a></li>
  <li><a href="#burbujas" id="toc-burbujas" class="nav-link" data-scroll-target="#burbujas">Burbujas</a>
  <ul>
  <li><a href="#por-niveles-de-ph" id="toc-por-niveles-de-ph" class="nav-link" data-scroll-target="#por-niveles-de-ph">Por niveles de pH</a></li>
  <li><a href="#por-niveles-de-o2" id="toc-por-niveles-de-o2" class="nav-link" data-scroll-target="#por-niveles-de-o2">Por niveles de O2</a></li>
  <li><a href="#por-niveles-de-ups" id="toc-por-niveles-de-ups" class="nav-link" data-scroll-target="#por-niveles-de-ups">Por niveles de UPS</a></li>
  <li><a href="#por-niveles-de-temperatura" id="toc-por-niveles-de-temperatura" class="nav-link" data-scroll-target="#por-niveles-de-temperatura">Por niveles de Temperatura</a></li>
  </ul></li>
  <li><a href="#curvas-rad-fases-lunares-horarios-día-noche-y-por-zonas" id="toc-curvas-rad-fases-lunares-horarios-día-noche-y-por-zonas" class="nav-link" data-scroll-target="#curvas-rad-fases-lunares-horarios-día-noche-y-por-zonas">Curvas RAD (Fases lunares, Horarios día-noche y por zonas)</a>
  <ul>
  <li><a href="#rad-por-fases-lunares-moon" id="toc-rad-por-fases-lunares-moon" class="nav-link" data-scroll-target="#rad-por-fases-lunares-moon">RAD por fases lunares (Moon)</a></li>
  <li><a href="#rad-por-horarios-del-día-time" id="toc-rad-por-horarios-del-día-time" class="nav-link" data-scroll-target="#rad-por-horarios-del-día-time">RAD por horarios del día (Time)</a></li>
  <li><a href="#rad-por-zonas-zone" id="toc-rad-por-zonas-zone" class="nav-link" data-scroll-target="#rad-por-zonas-zone">RAD por Zonas (Zone)</a></li>
  </ul></li>
  <li><a href="#ajuste-de-las-curvas-rad-fases-lunares-horarios-día-noche-y-por-zonas" id="toc-ajuste-de-las-curvas-rad-fases-lunares-horarios-día-noche-y-por-zonas" class="nav-link" data-scroll-target="#ajuste-de-las-curvas-rad-fases-lunares-horarios-día-noche-y-por-zonas">Ajuste de las curvas RAD (Fases lunares, Horarios día-noche y por zonas)</a>
  <ul>
  <li><a href="#ajuste-del-rad-por-fases-lunares-moon" id="toc-ajuste-del-rad-por-fases-lunares-moon" class="nav-link" data-scroll-target="#ajuste-del-rad-por-fases-lunares-moon">Ajuste del RAD por fases lunares (Moon)</a></li>
  <li><a href="#figuras-de-los-modelos-rad" id="toc-figuras-de-los-modelos-rad" class="nav-link" data-scroll-target="#figuras-de-los-modelos-rad">Figuras de los modelos RAD</a></li>
  <li><a href="#ajuste-del-rad-por-horarios-día-noche-time" id="toc-ajuste-del-rad-por-horarios-día-noche-time" class="nav-link" data-scroll-target="#ajuste-del-rad-por-horarios-día-noche-time">Ajuste del RAD por horarios día-noche (Time)</a></li>
  <li><a href="#figuras-de-los-modelos-rad-1" id="toc-figuras-de-los-modelos-rad-1" class="nav-link" data-scroll-target="#figuras-de-los-modelos-rad-1">Figuras de los modelos RAD</a></li>
  <li><a href="#ajuste-del-rad-por-zonas-zone" id="toc-ajuste-del-rad-por-zonas-zone" class="nav-link" data-scroll-target="#ajuste-del-rad-por-zonas-zone">Ajuste del RAD por zonas (Zone)</a></li>
  <li><a href="#figuras-de-los-modelos-rad-2" id="toc-figuras-de-los-modelos-rad-2" class="nav-link" data-scroll-target="#figuras-de-los-modelos-rad-2">Figuras de los modelos RAD</a></li>
  </ul></li>
  <li><a href="#diversidad-alfa---propuesta-de-chao-et-al.-2020" id="toc-diversidad-alfa---propuesta-de-chao-et-al.-2020" class="nav-link" data-scroll-target="#diversidad-alfa---propuesta-de-chao-et-al.-2020">Diversidad alfa - propuesta de Chao et al.&nbsp;(2020)</a>
  <ul>
  <li><a href="#por-fases-lunares-moon" id="toc-por-fases-lunares-moon" class="nav-link" data-scroll-target="#por-fases-lunares-moon">Por fases lunares (Moon)</a>
  <ul>
  <li><a href="#paso-1.-perfil-de-completitud" id="toc-paso-1.-perfil-de-completitud" class="nav-link" data-scroll-target="#paso-1.-perfil-de-completitud">Paso 1. Perfil de completitud</a></li>
  <li><a href="#paso-2.-perfil-asintótico" id="toc-paso-2.-perfil-asintótico" class="nav-link" data-scroll-target="#paso-2.-perfil-asintótico">Paso 2. Perfil asintótico</a></li>
  <li><a href="#paso-3.-perfil-no-asintótico" id="toc-paso-3.-perfil-no-asintótico" class="nav-link" data-scroll-target="#paso-3.-perfil-no-asintótico">Paso 3. Perfil no asintótico</a></li>
  <li><a href="#paso-4.-patrón-de-uniformidad" id="toc-paso-4.-patrón-de-uniformidad" class="nav-link" data-scroll-target="#paso-4.-patrón-de-uniformidad">Paso 4. Patrón de uniformidad</a></li>
  </ul></li>
  <li><a href="#por-horarios-times" id="toc-por-horarios-times" class="nav-link" data-scroll-target="#por-horarios-times">Por Horarios (Times)</a>
  <ul>
  <li><a href="#paso-1.-perfil-de-completitud-1" id="toc-paso-1.-perfil-de-completitud-1" class="nav-link" data-scroll-target="#paso-1.-perfil-de-completitud-1">Paso 1. Perfil de completitud</a></li>
  <li><a href="#paso-2.-perfil-asintótico-1" id="toc-paso-2.-perfil-asintótico-1" class="nav-link" data-scroll-target="#paso-2.-perfil-asintótico-1">Paso 2. Perfil asintótico</a></li>
  <li><a href="#paso-3.-perfil-no-asintótico-1" id="toc-paso-3.-perfil-no-asintótico-1" class="nav-link" data-scroll-target="#paso-3.-perfil-no-asintótico-1">Paso 3. Perfil no asintótico</a></li>
  <li><a href="#paso-4.-patrón-de-uniformidad-1" id="toc-paso-4.-patrón-de-uniformidad-1" class="nav-link" data-scroll-target="#paso-4.-patrón-de-uniformidad-1">Paso 4. Patrón de uniformidad</a></li>
  </ul></li>
  <li><a href="#por-zonas-zone" id="toc-por-zonas-zone" class="nav-link" data-scroll-target="#por-zonas-zone">Por Zonas (Zone)</a>
  <ul>
  <li><a href="#paso-1.-perfil-de-completitud-2" id="toc-paso-1.-perfil-de-completitud-2" class="nav-link" data-scroll-target="#paso-1.-perfil-de-completitud-2">Paso 1. Perfil de completitud</a></li>
  <li><a href="#paso-2.-perfil-asintótico-2" id="toc-paso-2.-perfil-asintótico-2" class="nav-link" data-scroll-target="#paso-2.-perfil-asintótico-2">Paso 2. Perfil asintótico</a></li>
  <li><a href="#paso-3.-perfil-no-asintótico-2" id="toc-paso-3.-perfil-no-asintótico-2" class="nav-link" data-scroll-target="#paso-3.-perfil-no-asintótico-2">Paso 3. Perfil no asintótico</a></li>
  <li><a href="#paso-4.-patrón-de-uniformidad-2" id="toc-paso-4.-patrón-de-uniformidad-2" class="nav-link" data-scroll-target="#paso-4.-patrón-de-uniformidad-2">Paso 4. Patrón de uniformidad</a></li>
  </ul></li>
  <li><a href="#pendientes-por-realizar" id="toc-pendientes-por-realizar" class="nav-link" data-scroll-target="#pendientes-por-realizar"><strong>Pendientes por realizar:</strong></a></li>
  </ul></li>
  </ul></li>
  </ul>
</nav>
</div>
<main class="content quarto-banner-title-block" id="quarto-document-content">




<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="mangroves%20uraba.jpg" class="img-fluid figure-img" width="625"></p>
<p></p><figcaption class="figure-caption">Área de estudio</figcaption><p></p>
</figure>
</div>
<hr>
<p><b style="color:#1f78b4;"></b></p><b style="color:#1f78b4;">
</b><section id="resumen" class="level2"><b style="color:#1f78b4;">
<h2 class="anchored" data-anchor-id="resumen">Resumen</h2>
</b><p><b style="color:#1f78b4;"></b></p>
<p>El presente ejercicio consiste en el procesamiento inicial de los datos entregados por el profesor Lenin Florez y Alejandro Sandoval, para dar respuesta al siguiente requerimiento: “<em>Analizar el efecto de cambios en las fases lunares (<strong>ciclo lunar</strong>) y horarios de <strong>día vs.&nbsp;noche</strong>, sobre los patrones de <strong>riqueza, de composición y de abundancia (también la biomasa) de peces estuarinos</strong></em>”. Las fases lunares analizadas se describen en la siguiente figura: <strong>Wanning crescent</strong> (luna creciente), <strong>Waning gibbous</strong> (Luna gibosa menguante), <strong>Waxing crescent</strong> (Luna creciente) y <strong>Waxing gibbous</strong> (Luna gibosa creciente).</p>
<div class="quarto-figure quarto-figure-left">
<figure class="figure">
<p><img src="https://c.tadst.com/gfx/600x337/moon-phases-explained.png?1" class="img-fluid figure-img" width="644"></p>
<p></p><figcaption class="figure-caption">Tomado de <a href="https://www.timeanddate.com/astronomy/moon/phases.html">timeanddate</a></figcaption><p></p>
</figure>
</div>
<hr>
<p><b style="color:#1f78b4;"></b></p><b style="color:#1f78b4;">
</b></section><b style="color:#1f78b4;">
</b><section id="cargar-bases-de-datos" class="level2"><b style="color:#1f78b4;">
<h2 class="anchored" data-anchor-id="cargar-bases-de-datos">Cargar bases de datos</h2>
</b><p><b style="color:#1f78b4;"></b></p>
<p>Se cargan las librerías requeridas para el procesamiento de los datos.</p>
<div class="cell">

</div>
<hr>
<p><b style="color:#1f78b4;"></b></p><b style="color:#1f78b4;">
</b></section><b style="color:#1f78b4;">
</b><section id="datos-biológicos" class="level2"><b style="color:#1f78b4;">
<h2 class="anchored" data-anchor-id="datos-biológicos">Datos biológicos</h2>
</b><p><b style="color:#1f78b4;"></b></p>
<p>Se carga la base de datos con las especies de peces.</p>
<div id="tbl-tbl1" class="cell tbl-parent quarto-layout-panel anchored" data-tbl-cap="Resumen de los seis primeros datos de los taxones con nombres abreviados">

</div>
<div class="cell">
<div class="cell-output-display">

<table class=" lightable-classic" style="font-family: Cambria; width: auto !important; margin-left: auto; margin-right: auto;">
<caption></caption>
 <thead>
  <tr>
   <th style="text-align:left;"> Especies </th>
   <th style="text-align:left;"> Abreviaturas </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> Achirus lineatus </td>
   <td style="text-align:left;"> Achl </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Anchovia clupeoides </td>
   <td style="text-align:left;"> Ancc </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Ariopsis sp </td>
   <td style="text-align:left;"> Aris </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Bardiela ronchus </td>
   <td style="text-align:left;"> Barr </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Batrachoides surinamensis </td>
   <td style="text-align:left;"> Bats </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Caranx crysos </td>
   <td style="text-align:left;"> Carc </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Caranx hippos </td>
   <td style="text-align:left;"> Carh </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Caranx latus </td>
   <td style="text-align:left;"> Carl </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Cathorops mapale </td>
   <td style="text-align:left;"> Catm </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Centropomus ensiferus </td>
   <td style="text-align:left;"> Cene </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Centropomus pectinatus </td>
   <td style="text-align:left;"> Cenp </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Centropomus undecimalis </td>
   <td style="text-align:left;"> Cenu </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Cetengraulis edentulus </td>
   <td style="text-align:left;"> Cete </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Chaetodipterus fabel </td>
   <td style="text-align:left;"> Chaf </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Citharichthys spilopterus </td>
   <td style="text-align:left;"> Cits </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Dasyatis guttata </td>
   <td style="text-align:left;"> Dasg </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Diapterus rhombeus </td>
   <td style="text-align:left;"> Diar </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Epinephelus itajara </td>
   <td style="text-align:left;"> Epii </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Eugerres plumieri </td>
   <td style="text-align:left;"> Eugp </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Gerres cinereus </td>
   <td style="text-align:left;"> Gerc </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Gobiomorus dormitor </td>
   <td style="text-align:left;"> Gobd </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Gymnothorax ocellatus </td>
   <td style="text-align:left;"> Gymo </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Lutjanus analis </td>
   <td style="text-align:left;"> Luta </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Lutjanus jocu </td>
   <td style="text-align:left;"> Lutj </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Lycengraulis grossidens </td>
   <td style="text-align:left;"> Lycg </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Megalops atlanticus </td>
   <td style="text-align:left;"> Mega </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Menticirrhus americanus </td>
   <td style="text-align:left;"> Mena </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Mugil incilis </td>
   <td style="text-align:left;"> Mugi </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Oligoplites saliens </td>
   <td style="text-align:left;"> Olig </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Oligoplites saurus </td>
   <td style="text-align:left;"> Olig.1 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Selene vomer </td>
   <td style="text-align:left;"> Selv </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Sphoeroides testudineum </td>
   <td style="text-align:left;"> Spht </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Stellifer sp </td>
   <td style="text-align:left;"> Stes </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Strongylura timuco </td>
   <td style="text-align:left;"> Strt </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Trichiurus lepturus </td>
   <td style="text-align:left;"> Tril </td>
  </tr>
</tbody>
</table>

</div>
</div>
<hr>
<p><b style="color:#e78ac3;"></b></p><b style="color:#e78ac3;">
</b><section id="elipses" class="level4"><b style="color:#e78ac3;">
<h4 class="anchored" data-anchor-id="elipses">Elipses</h4>
</b><p><b style="color:#e78ac3;"></b></p>
<p>Algunas especies presentan relaciones positivas o directas en sus abundancias, las relaciones inversas son muy bajas.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="alfa.eng1peces_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<hr>
<p><b style="color:#1f78b4;"></b></p><b style="color:#1f78b4;">
</b></section><b style="color:#1f78b4;">
</b></section><b style="color:#1f78b4;">
</b><section id="datos-ambientales" class="level2"><b style="color:#1f78b4;">
<h2 class="anchored" data-anchor-id="datos-ambientales">Datos ambientales</h2>
</b><p><b style="color:#1f78b4;"></b></p>
<p>Se carga la base de datos ambientales.</p>
<div class="cell">

</div>
<p><b style="color:#e78ac3;"></b></p><b style="color:#e78ac3;">
</b><section id="elipses-1" class="level4"><b style="color:#e78ac3;">
<h4 class="anchored" data-anchor-id="elipses-1">Elipses</h4>
</b><p><b style="color:#e78ac3;"></b></p>
<p>Relaciones entre las variables ambientales tienen a ser positivas o directas.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="alfa.eng1peces_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><b style="color:#e78ac3;"></b></p><b style="color:#e78ac3;">
</b></section><b style="color:#e78ac3;">
</b><section id="relación-ambientales-y-taxones" class="level4"><b style="color:#e78ac3;">
<h4 class="anchored" data-anchor-id="relación-ambientales-y-taxones">Relación ambientales y taxones</h4>
</b><p><b style="color:#e78ac3;"></b></p>
<p>Se observan algunas relaciones negativas entre las variables ambientales y la abundancia de las especies.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="alfa.eng1peces_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<hr>
<p><b style="color:#e78ac3;"></b></p><b style="color:#e78ac3;">
</b></section><b style="color:#e78ac3;">
</b><section id="figuras-de-cajas" class="level4"><b style="color:#e78ac3;">
<h4 class="anchored" data-anchor-id="figuras-de-cajas">Figuras de Cajas</h4>
</b><p><b style="color:#e78ac3;"></b></p>
<p>Se analizan los patrones de <strong>abundancias de peces</strong> (eje y), con diferentes factores (eje x), como las fases lunares (<strong>Moon</strong>), horarios (<strong>Time</strong>), y zonas (<strong>Zones</strong>).</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="alfa.eng1peces_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<hr>
<div class="cell">
<div class="cell-output-display">
<p><img src="alfa.eng1peces_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<hr>
<div class="cell">
<div class="cell-output-display">
<p><img src="alfa.eng1peces_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<hr>
<p><b style="color:#e78ac3;"></b></p><b style="color:#e78ac3;">
</b></section><b style="color:#e78ac3;">
</b><section id="burbujas" class="level4"><b style="color:#e78ac3;">
<h4 class="anchored" data-anchor-id="burbujas">Burbujas</h4>
</b><p><b style="color:#e78ac3;"></b></p>
<p>Se relaciona a las especies de peces (eje y), variables ambientales (eje x), colores de las burbujas (fases lunares) y tamaños de las burbujas (abundancias).</p>
<p><strong>Nota:</strong> Solo se hará con fases lunares, pero se puede hacer con el resto de factores (horarios y zonas).</p>
<div class="cell">

</div>
<div class="cell">

</div>
<p><b style="color:#66c2a5;"></b></p><b style="color:#66c2a5;">
</b><section id="por-niveles-de-ph" class="level6"><b style="color:#66c2a5;">
<h6 class="anchored" data-anchor-id="por-niveles-de-ph">Por niveles de pH</h6>
</b><p><b style="color:#66c2a5;"></b></p>
<p>Se observa la mayor concentración de taxones abundantes y la mayor riqueza en <strong>pH</strong> entre 7.5 y 8 unidades.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="alfa.eng1peces_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><b style="color:#66c2a5;"></b></p><b style="color:#66c2a5;">
</b></section><b style="color:#66c2a5;">
</b><section id="por-niveles-de-o2" class="level6"><b style="color:#66c2a5;">
<h6 class="anchored" data-anchor-id="por-niveles-de-o2">Por niveles de O2</h6>
</b><p><b style="color:#66c2a5;"></b></p>
<p>Se observa la mayor concentración de taxones abundantes y la mayor riqueza en <strong>OD</strong> entre 3.5 y 4.7 mg/L.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="alfa.eng1peces_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><b style="color:#66c2a5;"></b></p><b style="color:#66c2a5;">
</b></section><b style="color:#66c2a5;">
</b><section id="por-niveles-de-ups" class="level6"><b style="color:#66c2a5;">
<h6 class="anchored" data-anchor-id="por-niveles-de-ups">Por niveles de UPS</h6>
</b><p><b style="color:#66c2a5;"></b></p>
<p>Se observa la mayor concentración de taxones abundantes y la mayor riqueza en <strong>UPS</strong> entre 19 y 25 unidades.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="alfa.eng1peces_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><b style="color:#66c2a5;"></b></p><b style="color:#66c2a5;">
</b></section><b style="color:#66c2a5;">
</b><section id="por-niveles-de-temperatura" class="level6"><b style="color:#66c2a5;">
<h6 class="anchored" data-anchor-id="por-niveles-de-temperatura">Por niveles de Temperatura</h6>
</b><p><b style="color:#66c2a5;"></b><br>
Se observa la mayor concentración de taxones abundantes y la mayor riqueza en <strong>temperaturas</strong> entre 28 y 30 grados centigrados.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="alfa.eng1peces_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<hr>
<p><b style="color:#e78ac3;"></b></p><b style="color:#e78ac3;">
</b></section><b style="color:#e78ac3;">
</b></section><b style="color:#e78ac3;">
</b><section id="curvas-rad-fases-lunares-horarios-día-noche-y-por-zonas" class="level4"><b style="color:#e78ac3;">
<h4 class="anchored" data-anchor-id="curvas-rad-fases-lunares-horarios-día-noche-y-por-zonas">Curvas RAD (Fases lunares, Horarios día-noche y por zonas)</h4>
</b><p><b style="color:#e78ac3;"></b></p>
<p><b style="color:#66c2a5;"></b></p><b style="color:#66c2a5;">
</b><section id="rad-por-fases-lunares-moon" class="level5"><b style="color:#66c2a5;">
<h5 class="anchored" data-anchor-id="rad-por-fases-lunares-moon">RAD por fases lunares (Moon)</h5>
</b><p><b style="color:#66c2a5;"></b></p>
<div class="cell">

</div>
<div class="cell">

</div>
<p>Patrón de distribución de abundancias para las 15 especies más abundantes (para no saturar las figuras). <strong>Wan.cres</strong> y <strong>Wan.gibb</strong>, muestran la mayor presencia de especies abundantes o dominantes.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="alfa.eng1peces_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<hr>
<p><b style="color:#66c2a5;"></b></p><b style="color:#66c2a5;">
</b></section><b style="color:#66c2a5;">
</b><section id="rad-por-horarios-del-día-time" class="level5"><b style="color:#66c2a5;">
<h5 class="anchored" data-anchor-id="rad-por-horarios-del-día-time">RAD por horarios del día (Time)</h5>
</b><p><b style="color:#66c2a5;"></b></p>
<div class="cell">

</div>
<div class="cell">

</div>
<p>Patrón de distribución de abundancias para las 15 especies más abundantes (para no saturar las figuras). En la <strong>noche</strong> se presenta el mayor número de especies abundantes o dominantes.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="alfa.eng1peces_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<hr>
<p><b style="color:#66c2a5;"></b></p><b style="color:#66c2a5;">
</b></section><b style="color:#66c2a5;">
</b><section id="rad-por-zonas-zone" class="level5"><b style="color:#66c2a5;">
<h5 class="anchored" data-anchor-id="rad-por-zonas-zone">RAD por Zonas (Zone)</h5>
</b><p><b style="color:#66c2a5;"></b></p>
<div class="cell">

</div>
<div class="cell">

</div>
<p>Patrón de distribución de abundancias para las 15 especies más abundantes (para no saturar las figuras). En la <strong>zona 3</strong> se presenta el mayor número de especies abundantes o dominantes, seguida de las zonas 2 y 1 respectivamente.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="alfa.eng1peces_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<hr>
<hr>
<p><b style="color:#4daf4a;"></b></p><b style="color:#4daf4a;">
</b></section><b style="color:#4daf4a;">
</b></section><b style="color:#4daf4a;">
</b><section id="ajuste-de-las-curvas-rad-fases-lunares-horarios-día-noche-y-por-zonas" class="level4"><b style="color:#4daf4a;">
<h4 class="anchored" data-anchor-id="ajuste-de-las-curvas-rad-fases-lunares-horarios-día-noche-y-por-zonas">Ajuste de las curvas RAD (Fases lunares, Horarios día-noche y por zonas)</h4>
</b><p><b style="color:#4daf4a;"></b></p>
<p>Los <strong>modelos de distribución de rango-abundancia</strong> (RAD, Rank-Abundance Distribution) siguen una <strong>distribución</strong> <strong>Poisson</strong> como base estadística, por ser datos discretos representados por valores de abundancia de las especies censadas. En este sentido los cinco modelos que se describen a continuación corresponde a esta familia de modelos generalizados (<strong>Null,</strong> <strong>Preemption, log-normal, Zipf y Mandelbrot</strong>).</p>
<p>La familia <strong>Poisson</strong> es parte de los <strong>Modelos Lineales Generalizados (GLMs)</strong>, como una opción flexible para modelar datos que no necesariamente siguen una distribución normal. Esta familia es adecuada para modelar datos de conteo como las abundancias de especies. Sin embargo, su aplicabilidad depende de que los datos cumplan con supuestos de independencia y de homogeneidad de varianzas de las medias. Si lo anterior no se cumple, podría ser necesario considerar alternativas más flexibles como la <strong>Binomial Negativa</strong>.</p>
<p>El comando <code>radfit</code> de R (ajuste de Modelos - RAD), compara los cinco modelos mencionados: <strong>Null,</strong> <strong>Preemption, log-normal, Zipf y Mandelbrot</strong>, utilizando los criterios de información de Akaike (<code>AIC</code>) y los Bayesianos o de Schwartz (<code>BIC</code>). Los modelos RAD que se ajustan mejor a los datos, son los que presenten <strong>menor AIC y BIC</strong>.</p>
<p>En este sentido, los modelos evaluados (Preemption, Lognormal, Zipf, Mandelbrot) asumen la misma familia estadística (Poisson) para garantizar consistencia en los cálculos y comparaciones con trabajos realizados en muestras o ensamblajes similares. La elección de la familia estadística afecta la forma en que se calculan los criterios AIC y el BIC, permitiendo una evaluación equilibrada entre los modelos.</p>
<p><b style="color:#66c2a5;"></b></p><b style="color:#66c2a5;">
</b><section id="ajuste-del-rad-por-fases-lunares-moon" class="level5"><b style="color:#66c2a5;">
<h5 class="anchored" data-anchor-id="ajuste-del-rad-por-fases-lunares-moon">Ajuste del RAD por fases lunares (Moon)</h5>
</b><p><b style="color:#66c2a5;"></b></p>
<div class="cell">

</div>
<p>A continuación se tabulan los resultados con los cinco modelos para cada <strong>fase lunar</strong>, lo importante es seleccionar para cada caso, el modelo que presente el menor <strong>AIC</strong> y <strong>BIC</strong>.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
RAD models, family poisson 
No. of species 26, total abundance 233

           par1     par2    par3    Deviance AIC      BIC     
Null                                 39.5871 126.0509 126.0509
Preemption  0.17654                  21.6136 110.0774 111.3355
Lognormal   1.4245   1.3058           7.7456  98.2094 100.7256
Zipf        0.299   -1.1081          17.8514 108.3151 110.8313
Mandelbrot  5.3459  -2.0802  3.4159   9.6873 102.1510 105.9253</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
RAD models, family poisson 
No. of species 24, total abundance 274

           par1     par2    par3    Deviance AIC     BIC    
Null                                 93.127  172.441 172.441
Preemption  0.22873                  30.018  111.333 112.511
Lognormal   1.4311   1.5112          19.674  102.988 105.345
Zipf        0.36315 -1.2648          34.267  117.582 119.938
Mandelbrot  109.7   -3.1539  5.5868  17.551  102.866 106.400</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
RAD models, family poisson 
No. of species 13, total abundance 72

           par1     par2    par3        Deviance AIC     BIC    
Null                                     6.0994  47.5182 47.5182
Preemption  0.23331                      7.8975  51.3162 51.8812
Lognormal   1.258    1.0249              2.8758  48.2945 49.4244
Zipf        0.33416 -1.0596              2.8938  48.3125 49.4424
Mandelbrot  0.33417 -1.0596  8.6624e-06  2.8938  50.3125 52.0073</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
RAD models, family poisson 
No. of species 17, total abundance 70

           par1     par2    par3        Deviance AIC     BIC    
Null                                    14.1116  62.3112 62.3112
Preemption  0.21242                     14.1658  64.3654 65.1986
Lognormal   0.80179  1.1825              5.4251  57.6247 59.2911
Zipf        0.34422 -1.1533              1.7478  53.9474 55.6139
Mandelbrot  0.34422 -1.1533  1.7583e-06  1.7478  55.9474 58.4471</code></pre>
</div>
</div>
<div style="text-align: justify">

<p><strong>Modelo 1: Wan.cres. Distribución predominante: Lognormal (AIC = 102.9).</strong> El patrón lognormal sugiere que el ensablaje de peces está estructurado de forma relativamente equilibrada, donde hay unas pocas especies muy abundantes y muchas especies con abundancias intermedias o bajas. Esto puede reflejar un entorno donde los recursos están repartidos en varios nichos trógicos.</p>
<p><strong>Modelo 2: Wan.gibb. Distribución predominante: Zipf (AIC = 48.29).</strong> Los modelos Lognormal (48.29) y Zipf (48.31) tienen valores de AIC muy similares. Los modelos ZIP se asocian a ensamblajes en los que las especies dominantes ejercen el contro sobre los recursos. Esto se asocia a un patrón jerárquico, donde una o pocas especies dominan en abundancia. Esto puede reflejar mecanismos de competencia en los nichos tróficos.</p>
<p><strong>Modelo 3: Wax.gibb. Distribución predominante: Zipf (AIC = 53.94).</strong> Aquí, el modelo Zipf es claramente el de mejor ajuste.</p>
<p><strong>Modelo 4: Wax.cres. Distribución predominante: Lognormal (AIC = 102.86).</strong> El modelo Lognormal (102.86) es el mejor ajustado, muy cercano al modelo Mandelbrot (106.400).</p>
<p>Finalmente se puede presentar mayor competencia durante las fases lunares Wan.gibb y Wax.gib, en el resto de fases la competencia disminuye y el ensamblaje es más equilibrado en cuanto al uso del recurso, quiza por su mayor disponibilidad. De acuerdo a <a href="#0">Ibañez et al.&nbsp;(2006)</a>, las distribuciones <strong>lognormales</strong>, aplican a ensamblajes estables (sin perturbaciones) y/o a oportunistas.</p>
<p><b style="color:#4daf4a;"></b></p><b style="color:#4daf4a;">
</b></div></section><b style="color:#4daf4a;">
</b><section id="figuras-de-los-modelos-rad" class="level5"><b style="color:#4daf4a;">
<h5 class="anchored" data-anchor-id="figuras-de-los-modelos-rad">Figuras de los modelos RAD</h5>
</b><p><b style="color:#4daf4a;"></b></p>
<div class="cell">
<div class="cell-output-display">
<p><img src="alfa.eng1peces_files/figure-html/unnamed-chunk-28-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div style="text-align: justify">

<p>La línea de mayor grosor es la que representa al <strong>modelo de mayor ajuste</strong> para cada fase lunar. A continuación se grafican los diagramas de mayor ajuste.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="alfa.eng1peces_files/figure-html/unnamed-chunk-29-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<hr>
<p><b style="color:#66c2a5;"></b></p><b style="color:#66c2a5;">
</b></div></section><b style="color:#66c2a5;">
</b><section id="ajuste-del-rad-por-horarios-día-noche-time" class="level5"><b style="color:#66c2a5;">
<h5 class="anchored" data-anchor-id="ajuste-del-rad-por-horarios-día-noche-time">Ajuste del RAD por horarios día-noche (Time)</h5>
</b><p><b style="color:#66c2a5;"></b></p>
<div class="cell">

</div>
<p>A continuación se tabulan los resultados con los cinco modelos para cada <strong>jornada</strong>, lo importante es seleccionar para cada caso, el modelo que presente el menor <strong>AIC</strong> y <strong>BIC</strong>.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
RAD models, family poisson 
No. of species 19, total abundance 147

           par1     par2    par3     Deviance AIC     BIC    
Null                                 37.4963  97.9286 97.9286
Preemption  0.24107                  22.3261  84.7584 85.7028
Lognormal   1.1935   1.4004           7.7767  72.2090 74.0979
Zipf        0.37692 -1.2647           8.1032  72.5355 74.4244
Mandelbrot  0.87051 -1.5987  0.75701  7.1920  73.6243 76.4576</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
RAD models, family poisson 
No. of species 32, total abundance 502

           par1        par2    par3    Deviance AIC     BIC    
Null                                   209.072  318.126 318.126
Preemption  0.19667                     36.012  147.066 148.532
Lognormal   1.6935      1.5363          69.321  182.375 185.307
Zipf        0.32326    -1.2015         119.887  232.941 235.873
Mandelbrot  1.5186e+07 -6.0261  18.926  25.416  140.471 144.868</code></pre>
</div>
</div>
<div style="text-align: justify">

<p><strong>Modelo 1: Day. Distribución predominante: Lognormal (AIC = 72.2)</strong>, seguido muy de cerca por <strong>Zipf (AIC = 72.53)</strong>. La distribución <strong>Lognormal</strong> sugiere que, en el horario diurno, las especies tienen una estructura de abundancia equilibrada con predominancia de unas pocas especies más abundantes y muchas de abundancias similares. Esto puede estar asociado con una mayor diversificación de nichos y de recursos tróficos. La similitud en el ajuste con el modelo <strong>Zipf</strong> podría indicar que hay una ligera jerarquización en la comunidad, pero no tan marcada.</p>
<p><strong>Modelo 2: Night. Distribución predominante: Mandelbrot (AIC = 140.47)</strong>, seguido por <strong>Preemption (AIC = 147.06)</strong>. El modelo <strong>Mandelbrot</strong> indica que este ensamblaje en la noche, prsenta una estructura compleja, caracterizada por una jerarquía de en la dominancia de las especies de peces, pero más flexible que el modelo Zipf. Esto puede reflejar dinámicas de abundancia influenciadas por interacciones ecológicas nocturnas, como cambios en la obtención de recursos, el efecto de la depredación, o comportamiento de las especies. El modelo <strong>Preemption</strong> también que puede haber una fuerte repartición de los recursos, donde unas pocas especies dominan significativamente.</p>
<p>De acuerdo a <a href="https://cienciasforestales.inifap.gob.mx/index.php/forestales/article/view/591/2056">Alanís-Rodríguez et al.&nbsp;(2020)</a>, el ajuste <em>Premption,</em> se denomina de nicho preferencial o de serie geométrica y se asocia a ensamblajes con algunos taxones que dominan por sus mayores densidades de indiviuos, especialmente en etapas iniciales de las sucesiones. Según <a href="https://cienciasforestales.inifap.gob.mx/index.php/forestales/article/view/591/2056">Alanís-Rodríguez et al.&nbsp;(2020)</a> y (<a href="https://cienciasforestales.inifap.gob.mx/index.php/forestales/article/view/591/2056">Magurran, 2004</a>), en el ajuste Mandelbrot se asocia a ensamblajes con pocas especies dominantes y en etapas sucesionales iniciales, considerado como uno de los mejores modelos para describir la distribución de la abundancia de especies.</p>
<p><b style="color:#4daf4a;"></b></p><b style="color:#4daf4a;">
</b></div></section><b style="color:#4daf4a;">
</b><section id="figuras-de-los-modelos-rad-1" class="level5"><b style="color:#4daf4a;">
<h5 class="anchored" data-anchor-id="figuras-de-los-modelos-rad-1">Figuras de los modelos RAD</h5>
</b><p><b style="color:#4daf4a;"></b></p>
<div class="cell">
<div class="cell-output-display">
<p><img src="alfa.eng1peces_files/figure-html/unnamed-chunk-32-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div style="text-align: justify">

<p>La línea de mayor grosor es la que representa al <strong>modelo de mayor ajuste</strong> para cada horario evaluado. A continuación se grafican los diagramas de mayor ajuste.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="alfa.eng1peces_files/figure-html/unnamed-chunk-33-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<hr>
<p><b style="color:#66c2a5;"></b></p><b style="color:#66c2a5;">
</b></div></section><b style="color:#66c2a5;">
</b><section id="ajuste-del-rad-por-zonas-zone" class="level5"><b style="color:#66c2a5;">
<h5 class="anchored" data-anchor-id="ajuste-del-rad-por-zonas-zone">Ajuste del RAD por zonas (Zone)</h5>
</b><p><b style="color:#66c2a5;"></b></p>
<div class="cell">

</div>
<p>A continuación se tabulan los resultados con los cinco modelos para cada <strong>zona</strong>, lo importante es seleccionar para cada caso, el modelo que presente el menor <strong>AIC</strong> y <strong>BIC</strong>.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
RAD models, family poisson 
No. of species 23, total abundance 203

           par1        par2    par3    Deviance AIC      BIC     
Null                                    36.6570 111.6121 111.6121
Preemption  0.20222                      6.4117  83.3668  84.5023
Lognormal   1.4548      1.2709          20.4063  99.3614 101.6324
Zipf        0.30043    -1.0908          37.1589 116.1140 118.3850
Mandelbrot  2.5606e+09 -7.1813  24.198   4.5651  85.5202  88.9267</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
RAD models, family poisson 
No. of species 27, total abundance 236

           par1        par2    par3    Deviance AIC     BIC    
Null                                    41.456  129.044 129.044
Preemption  0.17068                     15.236  104.824 106.120
Lognormal   1.4571      1.2516          22.464  114.052 116.644
Zipf        0.27366    -1.0461          42.368  133.956 136.548
Mandelbrot  8.0713e+08 -6.6708  26.793  13.417  107.005 110.892</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
RAD models, family poisson 
No. of species 20, total abundance 210

           par1     par2    par3    Deviance AIC      BIC     
Null                                100.7204 164.7249 164.7249
Preemption  0.29413                  33.5950  99.5994 100.5951
Lognormal   1.1182   1.7068           8.9331  76.9376  78.9290
Zipf        0.45212 -1.4765           6.6855  74.6900  76.6814
Mandelbrot  2.318   -2.1289  1.2439   2.4291  72.4335  75.4207</code></pre>
</div>
</div>
<div style="text-align: justify">

<p><strong>Modelo 1: Zona 1. Distribución predominante: Preemption (AIC = 83.37)</strong>. El modelo <strong>Preemption</strong> sugiere una repartición jerárquica de recursos, con pocas especies dominantes.</p>
<p><strong>Modelo 2: Zona 2. Distribución predominante: Preemption (AIC = 104.82)</strong>. Patrón similar al de la zona 1.</p>
<p><strong>Modelo 3: Zona 3. Distribución predominante: Maldelbrot (AIC = 72.43)</strong>. Como se mencionó para el caso del patrón nocturno, donde también se presenta este ajuste, hay una estructura compleja, debido al patron de dominancia de las especies, debido a posibles mecanismos de depredación o por cambios en la disponibilidad del recurso.</p>
<p><b style="color:#4daf4a;"></b></p><b style="color:#4daf4a;">
</b></div></section><b style="color:#4daf4a;">
</b><section id="figuras-de-los-modelos-rad-2" class="level5"><b style="color:#4daf4a;">
<h5 class="anchored" data-anchor-id="figuras-de-los-modelos-rad-2">Figuras de los modelos RAD</h5>
</b><p><b style="color:#4daf4a;"></b></p>
<div class="cell">
<div class="cell-output-display">
<p><img src="alfa.eng1peces_files/figure-html/unnamed-chunk-36-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="alfa.eng1peces_files/figure-html/unnamed-chunk-36-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<div style="text-align: justify">

<p>La línea de mayor grosor es la que representa al <strong>modelo de mayor ajuste</strong> para cada zona evaluada. A continuación se grafican los diagramas de mayor ajuste.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="alfa.eng1peces_files/figure-html/unnamed-chunk-37-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="alfa.eng1peces_files/figure-html/unnamed-chunk-37-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<hr>
<hr>
<p><b style="color:#e78ac3;"></b></p><b style="color:#e78ac3;">
</b></div></section><b style="color:#e78ac3;">
</b></section><b style="color:#e78ac3;">
</b><section id="diversidad-alfa---propuesta-de-chao-et-al.-2020" class="level4"><b style="color:#e78ac3;">
<h4 class="anchored" data-anchor-id="diversidad-alfa---propuesta-de-chao-et-al.-2020">Diversidad alfa - propuesta de Chao et al.&nbsp;(2020)</h4>
</b><p><b style="color:#e78ac3;"></b></p>
<p><b style="color:#66c2a5;"></b></p><b style="color:#66c2a5;">
</b><section id="por-fases-lunares-moon" class="level5"><b style="color:#66c2a5;">
<h5 class="anchored" data-anchor-id="por-fases-lunares-moon">Por fases lunares (Moon)</h5>
</b><p><b style="color:#66c2a5;"></b></p>
<div class="cell">

</div>
<p>Patrón general de diversidad por cada fase lunar. <strong>Wan.cres</strong> y <strong>Wang.gib</strong>b presentan la mayoa abundancia y riqueza de especies, así como la mayor cantidad de <strong>singletons</strong> o especies con un individuo (f1) y de <strong>doubletons</strong> o especies con dos individuos (f2), esta cantidad de singletons afectará considerablemente a su perfil de completitud y el perfil asintótico que se muestran a continuación.</p>
<div class="cell">
<div class="cell-output-display">

<table class=" lightable-classic" style="font-family: Cambria; width: auto !important; margin-left: auto; margin-right: auto;">
<caption>Tabla. Estimadores de diversidad alfa</caption>
 <thead>
  <tr>
   <th style="text-align:left;"> Moon </th>
   <th style="text-align:right;"> N </th>
   <th style="text-align:right;"> Richness </th>
   <th style="text-align:right;"> f1 </th>
   <th style="text-align:right;"> f2 </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> Wan.cres </td>
   <td style="text-align:right;"> 233 </td>
   <td style="text-align:right;"> 26 </td>
   <td style="text-align:right;"> 8 </td>
   <td style="text-align:right;"> 4 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Wan.gibb </td>
   <td style="text-align:right;"> 274 </td>
   <td style="text-align:right;"> 24 </td>
   <td style="text-align:right;"> 8 </td>
   <td style="text-align:right;"> 4 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Wax..gibb </td>
   <td style="text-align:right;"> 72 </td>
   <td style="text-align:right;"> 13 </td>
   <td style="text-align:right;"> 3 </td>
   <td style="text-align:right;"> 1 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Wax.cres </td>
   <td style="text-align:right;"> 70 </td>
   <td style="text-align:right;"> 17 </td>
   <td style="text-align:right;"> 6 </td>
   <td style="text-align:right;"> 3 </td>
  </tr>
</tbody>
</table>

</div>
</div>
<p><b style="color:#fc8d62;"></b></p><b style="color:#fc8d62;">
</b><section id="paso-1.-perfil-de-completitud" class="level6"><b style="color:#fc8d62;">
<h6 class="anchored" data-anchor-id="paso-1.-perfil-de-completitud">Paso 1. Perfil de completitud</h6>
</b><p><b style="color:#fc8d62;"></b></p>
<div class="cell">

</div>
<p>El <strong>perfil de completitud</strong>, para los casos que sea &lt;0.9 indica que la muestra no es completa. Se observa que para la <strong>riqueza de especies</strong> (q=0) todas las fases lunares son incompleta (&lt;0.9), lo cual indica que puede requerirse un mayor esfuerzo de muestreo o que se pueden encontrar más taxones. Los <strong>taxones abundantes</strong> (q=1) y <strong>muy abundantes</strong> (q=2) fueron registrados en su totalidad (&gt;0.9).</p>
<div class="cell">
<div class="cell-output-display">

<table class=" lightable-classic" style="font-family: Cambria; width: auto !important; margin-left: auto; margin-right: auto;">
<caption></caption>
 <thead>
  <tr>
   <th style="text-align:left;"> Moon </th>
   <th style="text-align:right;"> q = 0 </th>
   <th style="text-align:right;"> q = 1 </th>
   <th style="text-align:right;"> q = 2 </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> Wan.cres </td>
   <td style="text-align:right;"> 0.77 </td>
   <td style="text-align:right;"> 0.97 </td>
   <td style="text-align:right;"> 1.00 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Wan.gibb </td>
   <td style="text-align:right;"> 0.75 </td>
   <td style="text-align:right;"> 0.97 </td>
   <td style="text-align:right;"> 1.00 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Wax..gibb </td>
   <td style="text-align:right;"> 0.75 </td>
   <td style="text-align:right;"> 0.96 </td>
   <td style="text-align:right;"> 1.00 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Wax.cres </td>
   <td style="text-align:right;"> 0.74 </td>
   <td style="text-align:right;"> 0.92 </td>
   <td style="text-align:right;"> 0.99 </td>
  </tr>
</tbody>
</table>

</div>
</div>
<p><b style="color:#fc8d62;"></b></p><b style="color:#fc8d62;">
</b></section><b style="color:#fc8d62;">
</b><section id="paso-2.-perfil-asintótico" class="level6"><b style="color:#fc8d62;">
<h6 class="anchored" data-anchor-id="paso-2.-perfil-asintótico">Paso 2. Perfil asintótico</h6>
</b><p><b style="color:#fc8d62;"></b></p>
<p>El <strong>perfil asintótico</strong> muestra que en las fases lunares <strong>Wan.cres</strong> y <strong>Wan.gibb</strong>, se presenta el mayor número de especies sin detectar (8 especies), seguidas de <strong>Wax.cres</strong> con 6 especies no detectadas. Este patrón puede afectar para que no se encuentre la asintota de diversidad, en la figura que se presenta a continuación.</p>
<div class="cell">
<div class="cell-output-display">

<table class=" lightable-classic" style="font-family: Cambria; width: auto !important; margin-left: auto; margin-right: auto;">
<caption></caption>
 <thead>
  <tr>
   <th style="text-align:left;"> Moon </th>
   <th style="text-align:left;"> Estimator </th>
   <th style="text-align:right;"> Ob.D </th>
   <th style="text-align:right;"> Est.D </th>
   <th style="text-align:right;"> Undet. </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> Wan.cres </td>
   <td style="text-align:left;"> q = 0 </td>
   <td style="text-align:right;"> 26 </td>
   <td style="text-align:right;"> 34 </td>
   <td style="text-align:right;"> 8 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Wan.cres </td>
   <td style="text-align:left;"> q = 1 </td>
   <td style="text-align:right;"> 13 </td>
   <td style="text-align:right;"> 14 </td>
   <td style="text-align:right;"> 1 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Wan.cres </td>
   <td style="text-align:left;"> q = 2 </td>
   <td style="text-align:right;"> 8 </td>
   <td style="text-align:right;"> 9 </td>
   <td style="text-align:right;"> 0 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Wan.gibb </td>
   <td style="text-align:left;"> q = 0 </td>
   <td style="text-align:right;"> 24 </td>
   <td style="text-align:right;"> 32 </td>
   <td style="text-align:right;"> 8 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Wan.gibb </td>
   <td style="text-align:left;"> q = 1 </td>
   <td style="text-align:right;"> 10 </td>
   <td style="text-align:right;"> 10 </td>
   <td style="text-align:right;"> 1 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Wan.gibb </td>
   <td style="text-align:left;"> q = 2 </td>
   <td style="text-align:right;"> 6 </td>
   <td style="text-align:right;"> 6 </td>
   <td style="text-align:right;"> 0 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Wax..gibb </td>
   <td style="text-align:left;"> q = 0 </td>
   <td style="text-align:right;"> 13 </td>
   <td style="text-align:right;"> 17 </td>
   <td style="text-align:right;"> 4 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Wax..gibb </td>
   <td style="text-align:left;"> q = 1 </td>
   <td style="text-align:right;"> 8 </td>
   <td style="text-align:right;"> 10 </td>
   <td style="text-align:right;"> 1 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Wax..gibb </td>
   <td style="text-align:left;"> q = 2 </td>
   <td style="text-align:right;"> 6 </td>
   <td style="text-align:right;"> 6 </td>
   <td style="text-align:right;"> 0 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Wax.cres </td>
   <td style="text-align:left;"> q = 0 </td>
   <td style="text-align:right;"> 17 </td>
   <td style="text-align:right;"> 23 </td>
   <td style="text-align:right;"> 6 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Wax.cres </td>
   <td style="text-align:left;"> q = 1 </td>
   <td style="text-align:right;"> 9 </td>
   <td style="text-align:right;"> 11 </td>
   <td style="text-align:right;"> 2 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Wax.cres </td>
   <td style="text-align:left;"> q = 2 </td>
   <td style="text-align:right;"> 6 </td>
   <td style="text-align:right;"> 6 </td>
   <td style="text-align:right;"> 0 </td>
  </tr>
</tbody>
</table>

</div>
</div>
<p>La siguiente figura complementa el <strong>patrón asintótico</strong> de la tabla anterior, en el que se observa que ninguna de las fases lunares se estabiliza en q = 0 (total de especies), ni siquiera interpolando al doble de la abundancia registrada (líneas punteadas, no se estabilizan o no se vuelven asintóticas para la diversidad esperada). Esto se debe al lto número de especies con un solo individuo encontradas (f1).</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="alfa.eng1peces_files/figure-html/unnamed-chunk-43-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><b style="color:#fc8d62;"></b></p><b style="color:#fc8d62;">
</b></section><b style="color:#fc8d62;">
</b><section id="paso-3.-perfil-no-asintótico" class="level6"><b style="color:#fc8d62;">
<h6 class="anchored" data-anchor-id="paso-3.-perfil-no-asintótico">Paso 3. Perfil no asintótico</h6>
</b><p><b style="color:#fc8d62;"></b></p>
<p>La siguiente tabla muestra el <strong>patrón no asintótico</strong>, en el que se extrae una submuestra de cada fase lunar y para este caso la cobertura calculada es del 97%, para lo cual se espera encontrar mayor número de taxones en <strong>Wan.cre</strong>s, seguida de Wan.gibb, Wax.cres y Wax.gibb respectivamente. Este patrón presenta validez, debido a la falta de asintota en el paso anterior.</p>
<div class="cell">
<div class="cell-output-display">

<table class=" lightable-classic" style="font-family: Cambria; width: auto !important; margin-left: auto; margin-right: auto;">
<caption></caption>
 <thead>
  <tr>
   <th style="text-align:left;"> Cmax = 0.969 </th>
   <th style="text-align:right;"> q = 0 </th>
   <th style="text-align:right;"> q = 1 </th>
   <th style="text-align:right;"> q = 2 </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> Wan.cres </td>
   <td style="text-align:right;"> 26.78 </td>
   <td style="text-align:right;"> 12.97 </td>
   <td style="text-align:right;"> 8.34 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Wan.gibb </td>
   <td style="text-align:right;"> 23.53 </td>
   <td style="text-align:right;"> 9.76 </td>
   <td style="text-align:right;"> 6.35 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Wax..gibb </td>
   <td style="text-align:right;"> 14.12 </td>
   <td style="text-align:right;"> 8.78 </td>
   <td style="text-align:right;"> 5.97 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Wax.cres </td>
   <td style="text-align:right;"> 20.75 </td>
   <td style="text-align:right;"> 10.51 </td>
   <td style="text-align:right;"> 5.84 </td>
  </tr>
</tbody>
</table>

</div>
</div>
<p>El siguiente perfil complementa a la tabla anterior, para lo cual, todas las curvas presentan una cobertura &gt; 0.9 o cercana a uno en el eje x, para que sus patrones de diversidad sean comparables.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="alfa.eng1peces_files/figure-html/unnamed-chunk-45-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><b style="color:#fc8d62;"></b></p><b style="color:#fc8d62;">
</b></section><b style="color:#fc8d62;">
</b><section id="paso-4.-patrón-de-uniformidad" class="level6"><b style="color:#fc8d62;">
<h6 class="anchored" data-anchor-id="paso-4.-patrón-de-uniformidad">Paso 4. Patrón de uniformidad</h6>
</b><p><b style="color:#fc8d62;"></b></p>
<p>Para este caso se observa que la mayor <strong>uniformidad de Pielou (J)</strong> se presenta en <strong>Wax.gibb</strong> que representa a la estación con menor número de tazones (q=0) y menos nùmero de singletons (f1).</p>
<div class="cell">
<div class="cell-output-display">

<table class=" lightable-classic" style="font-family: Cambria; width: auto !important; margin-left: auto; margin-right: auto;">
<caption></caption>
 <thead>
  <tr>
   <th style="text-align:left;"> Cmax = 0.969 </th>
   <th style="text-align:right;"> Pielou J' </th>
   <th style="text-align:right;"> q = 1 </th>
   <th style="text-align:right;"> q = 2 </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> Wan.cres </td>
   <td style="text-align:right;"> 0.78 </td>
   <td style="text-align:right;"> 0.46 </td>
   <td style="text-align:right;"> 0.28 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Wan.gibb </td>
   <td style="text-align:right;"> 0.72 </td>
   <td style="text-align:right;"> 0.39 </td>
   <td style="text-align:right;"> 0.24 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Wax..gibb </td>
   <td style="text-align:right;"> 0.82 </td>
   <td style="text-align:right;"> 0.59 </td>
   <td style="text-align:right;"> 0.38 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Wax.cres </td>
   <td style="text-align:right;"> 0.78 </td>
   <td style="text-align:right;"> 0.48 </td>
   <td style="text-align:right;"> 0.25 </td>
  </tr>
</tbody>
</table>

</div>
</div>
<hr>
<p><b style="color:#66c2a5;"></b></p><b style="color:#66c2a5;">
</b></section><b style="color:#66c2a5;">
</b></section><b style="color:#66c2a5;">
</b><section id="por-horarios-times" class="level5"><b style="color:#66c2a5;">
<h5 class="anchored" data-anchor-id="por-horarios-times">Por Horarios (Times)</h5>
</b><p><b style="color:#66c2a5;"></b></p>
<div class="cell">

</div>
<p><strong>Patrón general de diversidad por horario del día</strong>. En la noche se presenta la mayor abundancia y riqueza de especies, así como la mayor cantidad de <strong>singletons</strong> o especies con un individuo (f1) y de <strong>doubletons</strong> o especies con dos individuos (f2), esta cantidad de singletons afectará considerablemente a su perfil de completitud y el perfil asintótico que se muestran a continuación.</p>
<div class="cell">
<div class="cell-output-display">

<table class=" lightable-classic" style="font-family: Cambria; width: auto !important; margin-left: auto; margin-right: auto;">
<caption>Tabla. Estimadores de diversidad alfa</caption>
 <thead>
  <tr>
   <th style="text-align:left;"> Solar_day </th>
   <th style="text-align:right;"> N </th>
   <th style="text-align:right;"> Richness </th>
   <th style="text-align:right;"> f1 </th>
   <th style="text-align:right;"> f2 </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> Day </td>
   <td style="text-align:right;"> 147 </td>
   <td style="text-align:right;"> 19 </td>
   <td style="text-align:right;"> 6 </td>
   <td style="text-align:right;"> 4 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Night </td>
   <td style="text-align:right;"> 502 </td>
   <td style="text-align:right;"> 32 </td>
   <td style="text-align:right;"> 13 </td>
   <td style="text-align:right;"> 3 </td>
  </tr>
</tbody>
</table>

</div>
</div>
<p><b style="color:#fc8d62;"></b></p><b style="color:#fc8d62;">
</b><section id="paso-1.-perfil-de-completitud-1" class="level6"><b style="color:#fc8d62;">
<h6 class="anchored" data-anchor-id="paso-1.-perfil-de-completitud-1">Paso 1. Perfil de completitud</h6>
</b><p><b style="color:#fc8d62;"></b></p>
<div class="cell">

</div>
<p>El <strong>perfil de completitud</strong>, para los casos que sea &lt;0.9 indica que la muestra no es completa. Se observa que para la <strong>riqueza de especies</strong> (q=0) los horarios día y noche son inncompletos (&lt;0.9), lo cual indica que puede requerirse un mayor esfuerzo de muestreo o que se pueden encontrar más taxones, especialmente en la noche. Los <strong>taxones abundantes</strong> (q=1) y <strong>muy abundantes</strong> (q=2) fueron registrados en su totalidad (&gt;0.9).</p>
<div class="cell">
<div class="cell-output-display">

<table class=" lightable-classic" style="font-family: Cambria; width: auto !important; margin-left: auto; margin-right: auto;">
<caption></caption>
 <thead>
  <tr>
   <th style="text-align:left;"> Solar_day </th>
   <th style="text-align:right;"> q = 0 </th>
   <th style="text-align:right;"> q = 1 </th>
   <th style="text-align:right;"> q = 2 </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> Day </td>
   <td style="text-align:right;"> 0.81 </td>
   <td style="text-align:right;"> 0.96 </td>
   <td style="text-align:right;"> 1 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Night </td>
   <td style="text-align:right;"> 0.53 </td>
   <td style="text-align:right;"> 0.97 </td>
   <td style="text-align:right;"> 1 </td>
  </tr>
</tbody>
</table>

</div>
</div>
<p><b style="color:#fc8d62;"></b></p><b style="color:#fc8d62;">
</b></section><b style="color:#fc8d62;">
</b><section id="paso-2.-perfil-asintótico-1" class="level6"><b style="color:#fc8d62;">
<h6 class="anchored" data-anchor-id="paso-2.-perfil-asintótico-1">Paso 2. Perfil asintótico</h6>
</b><p><b style="color:#fc8d62;"></b></p>
<p>El <strong>perfil asintótico</strong> muestra que en la <strong>noche</strong> se presenta el mayor número de especies sin detectar (28 especies no detectadas), seguida del <strong>día</strong> con solo 4 especies no detectadas. Este patrón puede afectar para que no se encuentre la asintota de diversidad, en la figura que se presenta a continuación.</p>
<div class="cell">
<div class="cell-output-display">

<table class=" lightable-classic" style="font-family: Cambria; width: auto !important; margin-left: auto; margin-right: auto;">
<caption></caption>
 <thead>
  <tr>
   <th style="text-align:left;"> Solar_day </th>
   <th style="text-align:left;"> Estimator </th>
   <th style="text-align:right;"> Ob.D </th>
   <th style="text-align:right;"> Est.D </th>
   <th style="text-align:right;"> Undet. </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> Day </td>
   <td style="text-align:left;"> q = 0 </td>
   <td style="text-align:right;"> 19 </td>
   <td style="text-align:right;"> 23 </td>
   <td style="text-align:right;"> 4 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Day </td>
   <td style="text-align:left;"> q = 1 </td>
   <td style="text-align:right;"> 9 </td>
   <td style="text-align:right;"> 10 </td>
   <td style="text-align:right;"> 1 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Day </td>
   <td style="text-align:left;"> q = 2 </td>
   <td style="text-align:right;"> 5 </td>
   <td style="text-align:right;"> 6 </td>
   <td style="text-align:right;"> 0 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Night </td>
   <td style="text-align:left;"> q = 0 </td>
   <td style="text-align:right;"> 32 </td>
   <td style="text-align:right;"> 60 </td>
   <td style="text-align:right;"> 28 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Night </td>
   <td style="text-align:left;"> q = 1 </td>
   <td style="text-align:right;"> 12 </td>
   <td style="text-align:right;"> 13 </td>
   <td style="text-align:right;"> 1 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Night </td>
   <td style="text-align:left;"> q = 2 </td>
   <td style="text-align:right;"> 8 </td>
   <td style="text-align:right;"> 8 </td>
   <td style="text-align:right;"> 0 </td>
  </tr>
</tbody>
</table>

</div>
</div>
<p>La siguiente figura complementa el <strong>patrón asintótico</strong> de la tabla anterior, en el que se observa que ninguno de los horarios día-noche se estabilizan en q = 0 (total de especies), ni siquiera interpolando al doble de la abundancia registrada (líneas punteadas, no se estabilizan o no se vuelven asintóticas para la diversidad esperada). Esto se debe al lto número de especies con un solo individuo encontradas (f1).</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="alfa.eng1peces_files/figure-html/unnamed-chunk-52-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><b style="color:#fc8d62;"></b></p><b style="color:#fc8d62;">
</b></section><b style="color:#fc8d62;">
</b><section id="paso-3.-perfil-no-asintótico-1" class="level6"><b style="color:#fc8d62;">
<h6 class="anchored" data-anchor-id="paso-3.-perfil-no-asintótico-1">Paso 3. Perfil no asintótico</h6>
</b><p><b style="color:#fc8d62;"></b></p>
<p>La siguiente tabla muestra el <strong>patrón no asintótico</strong>, en el que se extrae una submuestra de cada horario día-noche y para este caso la cobertura calculada es del 98%, para lo cual se espera encontrar mayor número de taxones en <strong>la noche</strong> (42 especies), seguida de la <strong>mañana</strong> (22 especies). Este patrón presenta validez, debido a la falta de asintota en el paso anterior.</p>
<div class="cell">
<div class="cell-output-display">

<table class=" lightable-classic" style="font-family: Cambria; width: auto !important; margin-left: auto; margin-right: auto;">
<caption></caption>
 <thead>
  <tr>
   <th style="text-align:left;"> Cmax = 0.984 </th>
   <th style="text-align:right;"> q = 0 </th>
   <th style="text-align:right;"> q = 1 </th>
   <th style="text-align:right;"> q = 2 </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> Day </td>
   <td style="text-align:right;"> 21.67 </td>
   <td style="text-align:right;"> 9.25 </td>
   <td style="text-align:right;"> 5.54 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Night </td>
   <td style="text-align:right;"> 42.40 </td>
   <td style="text-align:right;"> 12.29 </td>
   <td style="text-align:right;"> 8.27 </td>
  </tr>
</tbody>
</table>

</div>
</div>
<p>El siguiente perfil complementa a la tabla anterior, para lo cual, todas las curvas presentan una cobertura &gt; 0.9 o cercana a uno en el eje x, para que sus patrones de diversidad sean comparables.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="alfa.eng1peces_files/figure-html/unnamed-chunk-54-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><b style="color:#fc8d62;"></b></p><b style="color:#fc8d62;">
</b></section><b style="color:#fc8d62;">
</b><section id="paso-4.-patrón-de-uniformidad-1" class="level6"><b style="color:#fc8d62;">
<h6 class="anchored" data-anchor-id="paso-4.-patrón-de-uniformidad-1">Paso 4. Patrón de uniformidad</h6>
</b><p><b style="color:#fc8d62;"></b></p>
<p>Para este caso se observa que la mayor <strong>uniformidad de Pielou (J)</strong> se presenta en <strong>la mañana</strong> que representa a la estación con menor número de tazones (q=0) y de especies con un solo individuo (f1).</p>
<div class="cell">
<div class="cell-output-display">

<table class=" lightable-classic" style="font-family: Cambria; width: auto !important; margin-left: auto; margin-right: auto;">
<caption></caption>
 <thead>
  <tr>
   <th style="text-align:left;"> Cmax = 0.984 </th>
   <th style="text-align:right;"> Pielou J' </th>
   <th style="text-align:right;"> q = 1 </th>
   <th style="text-align:right;"> q = 2 </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> Day </td>
   <td style="text-align:right;"> 0.72 </td>
   <td style="text-align:right;"> 0.40 </td>
   <td style="text-align:right;"> 0.22 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Night </td>
   <td style="text-align:right;"> 0.67 </td>
   <td style="text-align:right;"> 0.27 </td>
   <td style="text-align:right;"> 0.18 </td>
  </tr>
</tbody>
</table>

</div>
</div>
<hr>
<p><b style="color:#66c2a5;"></b></p><b style="color:#66c2a5;">
</b></section><b style="color:#66c2a5;">
</b></section><b style="color:#66c2a5;">
</b><section id="por-zonas-zone" class="level5"><b style="color:#66c2a5;">
<h5 class="anchored" data-anchor-id="por-zonas-zone">Por Zonas (Zone)</h5>
</b><p><b style="color:#66c2a5;"></b></p>
<div class="cell">

</div>
<p><strong>Patrón general de diversidad por horario del día</strong>. En la la <strong>zona 2</strong> se presenta la mayor abundancia y riqueza de especies, así como la mayor cantidad de <strong>singletons</strong> o especies con un individuo (f1) y de <strong>doubletons</strong> o especies con dos individuos (f2), seguida de las zonas y 1, respectivamente. Esta cantidad de singletons afectará considerablemente a su perfil de completitud y el perfil asintótico que se muestran a continuación.</p>
<div class="cell">
<div class="cell-output-display">

<table class=" lightable-classic" style="font-family: Cambria; width: auto !important; margin-left: auto; margin-right: auto;">
<caption>Tabla. Estimadores de diversidad alfa</caption>
 <thead>
  <tr>
   <th style="text-align:left;"> Zone </th>
   <th style="text-align:right;"> N </th>
   <th style="text-align:right;"> Richness </th>
   <th style="text-align:right;"> f1 </th>
   <th style="text-align:right;"> f2 </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> 1 </td>
   <td style="text-align:right;"> 203 </td>
   <td style="text-align:right;"> 23 </td>
   <td style="text-align:right;"> 8 </td>
   <td style="text-align:right;"> 3 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 2 </td>
   <td style="text-align:right;"> 236 </td>
   <td style="text-align:right;"> 27 </td>
   <td style="text-align:right;"> 11 </td>
   <td style="text-align:right;"> 2 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 3 </td>
   <td style="text-align:right;"> 210 </td>
   <td style="text-align:right;"> 20 </td>
   <td style="text-align:right;"> 8 </td>
   <td style="text-align:right;"> 1 </td>
  </tr>
</tbody>
</table>

</div>
</div>
<p><b style="color:#fc8d62;"></b></p><b style="color:#fc8d62;">
</b><section id="paso-1.-perfil-de-completitud-2" class="level6"><b style="color:#fc8d62;">
<h6 class="anchored" data-anchor-id="paso-1.-perfil-de-completitud-2">Paso 1. Perfil de completitud</h6>
</b><p><b style="color:#fc8d62;"></b></p>
<div class="cell">

</div>
<p>El <strong>perfil de completitud</strong>, para los casos que sea &lt;0.9 indica que la muestra no es completa. Se observa que para la <strong>riqueza de especies</strong> (q=0) Las tres zonas son bastante inncompletas (&lt;&lt;0.9), lo cual indica que puede requerirse un mayor esfuerzo de muestreo o que se pueden encontrar más taxones, especialmente en las zonas 3 y 2. Los <strong>taxones abundantes</strong> (q=1) y <strong>muy abundantes</strong> (q=2) fueron registrados en su totalidad (&gt;0.9).</p>
<div class="cell">
<div class="cell-output-display">

<table class=" lightable-classic" style="font-family: Cambria; width: auto !important; margin-left: auto; margin-right: auto;">
<caption></caption>
 <thead>
  <tr>
   <th style="text-align:left;"> Zone </th>
   <th style="text-align:right;"> q = 0 </th>
   <th style="text-align:right;"> q = 1 </th>
   <th style="text-align:right;"> q = 2 </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> 1 </td>
   <td style="text-align:right;"> 0.68 </td>
   <td style="text-align:right;"> 0.96 </td>
   <td style="text-align:right;"> 1 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 2 </td>
   <td style="text-align:right;"> 0.47 </td>
   <td style="text-align:right;"> 0.95 </td>
   <td style="text-align:right;"> 1 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 3 </td>
   <td style="text-align:right;"> 0.39 </td>
   <td style="text-align:right;"> 0.96 </td>
   <td style="text-align:right;"> 1 </td>
  </tr>
</tbody>
</table>

</div>
</div>
<p><b style="color:#fc8d62;"></b></p><b style="color:#fc8d62;">
</b></section><b style="color:#fc8d62;">
</b><section id="paso-2.-perfil-asintótico-2" class="level6"><b style="color:#fc8d62;">
<h6 class="anchored" data-anchor-id="paso-2.-perfil-asintótico-2">Paso 2. Perfil asintótico</h6>
</b><p><b style="color:#fc8d62;"></b></p>
<p>El <strong>perfil asintótico</strong> muestra que en la <strong>zona 3</strong> se presenta el mayor número de especies sin detectar (32 especies no detectadas), seguida de las <strong>zonas 2 y 1</strong> con 30 y 11 especies no detectadas. Este patrón puede afectar para que no se encuentre la asintota de diversidad, en la figura que se presenta a continuación.</p>
<div class="cell">
<div class="cell-output-display">

<table class=" lightable-classic" style="font-family: Cambria; width: auto !important; margin-left: auto; margin-right: auto;">
<caption></caption>
 <thead>
  <tr>
   <th style="text-align:left;"> Zone </th>
   <th style="text-align:left;"> Estimator </th>
   <th style="text-align:right;"> Ob.D </th>
   <th style="text-align:right;"> Est.D </th>
   <th style="text-align:right;"> Undet. </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> 1 </td>
   <td style="text-align:left;"> q = 0 </td>
   <td style="text-align:right;"> 23 </td>
   <td style="text-align:right;"> 34 </td>
   <td style="text-align:right;"> 11 </td>
  </tr>
  <tr>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;"> q = 1 </td>
   <td style="text-align:right;"> 11 </td>
   <td style="text-align:right;"> 13 </td>
   <td style="text-align:right;"> 1 </td>
  </tr>
  <tr>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;"> q = 2 </td>
   <td style="text-align:right;"> 8 </td>
   <td style="text-align:right;"> 9 </td>
   <td style="text-align:right;"> 0 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 2 </td>
   <td style="text-align:left;"> q = 0 </td>
   <td style="text-align:right;"> 27 </td>
   <td style="text-align:right;"> 57 </td>
   <td style="text-align:right;"> 30 </td>
  </tr>
  <tr>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;"> q = 1 </td>
   <td style="text-align:right;"> 14 </td>
   <td style="text-align:right;"> 15 </td>
   <td style="text-align:right;"> 2 </td>
  </tr>
  <tr>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;"> q = 2 </td>
   <td style="text-align:right;"> 10 </td>
   <td style="text-align:right;"> 10 </td>
   <td style="text-align:right;"> 0 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 3 </td>
   <td style="text-align:left;"> q = 0 </td>
   <td style="text-align:right;"> 20 </td>
   <td style="text-align:right;"> 52 </td>
   <td style="text-align:right;"> 32 </td>
  </tr>
  <tr>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;"> q = 1 </td>
   <td style="text-align:right;"> 7 </td>
   <td style="text-align:right;"> 8 </td>
   <td style="text-align:right;"> 1 </td>
  </tr>
  <tr>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;"> q = 2 </td>
   <td style="text-align:right;"> 4 </td>
   <td style="text-align:right;"> 4 </td>
   <td style="text-align:right;"> 0 </td>
  </tr>
</tbody>
</table>

</div>
</div>
<div class="cell">
<div class="cell-output-display">
<p><img src="alfa.eng1peces_files/figure-html/unnamed-chunk-61-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><b style="color:#fc8d62;"></b></p><b style="color:#fc8d62;">
</b></section><b style="color:#fc8d62;">
</b><section id="paso-3.-perfil-no-asintótico-2" class="level6"><b style="color:#fc8d62;">
<h6 class="anchored" data-anchor-id="paso-3.-perfil-no-asintótico-2">Paso 3. Perfil no asintótico</h6>
</b><p><b style="color:#fc8d62;"></b></p>
<p>La siguiente tabla muestra el <strong>patrón no asintótico</strong>, en el que se extrae una submuestra de cada horario día-noche y para este caso la cobertura calculada es del 97%, para lo cual se espera encontrar mayor número de taxones en <strong>la zona 2</strong> (36 especies), seguida de las <strong>zonas 3 y 1</strong> (25 especies). Este patrón presenta validez, debido a la falta de asintota en el paso anterior.</p>
<div class="cell">
<div class="cell-output-display">

<table class=" lightable-classic" style="font-family: Cambria; width: auto !important; margin-left: auto; margin-right: auto;">
<caption></caption>
 <thead>
  <tr>
   <th style="text-align:left;"> Cmax = 0.968 </th>
   <th style="text-align:right;"> q = 0 </th>
   <th style="text-align:right;"> q = 1 </th>
   <th style="text-align:right;"> q = 2 </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> X1 </td>
   <td style="text-align:right;"> 24.88 </td>
   <td style="text-align:right;"> 11.67 </td>
   <td style="text-align:right;"> 8.48 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> X2 </td>
   <td style="text-align:right;"> 36.21 </td>
   <td style="text-align:right;"> 14.34 </td>
   <td style="text-align:right;"> 9.87 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> X3 </td>
   <td style="text-align:right;"> 24.80 </td>
   <td style="text-align:right;"> 7.44 </td>
   <td style="text-align:right;"> 4.39 </td>
  </tr>
</tbody>
</table>

</div>
</div>
<p>El siguiente perfil complementa a la tabla anterior, para lo cual, todas las curvas presentan una cobertura &gt; 0.9 o cercana a uno en el eje x, para que sus patrones de diversidad sean comparables.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="alfa.eng1peces_files/figure-html/unnamed-chunk-63-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><b style="color:#fc8d62;"></b></p><b style="color:#fc8d62;">
</b></section><b style="color:#fc8d62;">
</b><section id="paso-4.-patrón-de-uniformidad-2" class="level6"><b style="color:#fc8d62;">
<h6 class="anchored" data-anchor-id="paso-4.-patrón-de-uniformidad-2">Paso 4. Patrón de uniformidad</h6>
</b><p><b style="color:#fc8d62;"></b></p>
<p>Para este caso se observa que la mayor <strong>uniformidad de Pielou (J)</strong> se presenta en la <strong>zona 1</strong> que representa a la estación con menor número de tazones (q=0) y de especies con un solo individuo (f1).</p>
<div class="cell">
<div class="cell-output-display">

<table class=" lightable-classic" style="font-family: Cambria; width: auto !important; margin-left: auto; margin-right: auto;">
<caption></caption>
 <thead>
  <tr>
   <th style="text-align:left;"> Cmax = 0.968 </th>
   <th style="text-align:right;"> Pielou J' </th>
   <th style="text-align:right;"> q = 1 </th>
   <th style="text-align:right;"> q = 2 </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> X1 </td>
   <td style="text-align:right;"> 0.76 </td>
   <td style="text-align:right;"> 0.45 </td>
   <td style="text-align:right;"> 0.31 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> X2 </td>
   <td style="text-align:right;"> 0.74 </td>
   <td style="text-align:right;"> 0.38 </td>
   <td style="text-align:right;"> 0.25 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> X3 </td>
   <td style="text-align:right;"> 0.63 </td>
   <td style="text-align:right;"> 0.27 </td>
   <td style="text-align:right;"> 0.14 </td>
  </tr>
</tbody>
</table>

</div>
</div>
<hr>
<p><b style="color:#e78ac3;"></b></p><b style="color:#e78ac3;">
</b></section><b style="color:#e78ac3;">
</b></section><b style="color:#e78ac3;">
</b><section id="pendientes-por-realizar" class="level5"><b style="color:#e78ac3;">
<h5 class="anchored" data-anchor-id="pendientes-por-realizar"><strong>Pendientes por realizar:</strong></h5>
</b><p><b style="color:#e78ac3;"></b></p>
<ul>
<li><p><strong>Análisis de gremios tróficos</strong>. Hay otro html en donde se encuentra esta información.</p></li>
<li><p><strong>Patrones multivariados.</strong> Habrá otro html con esta información (protocolo del PCA, NMDS, CA, LDA, DCA, CLA, RDA, PERMANOVAS y BIOENV).</p></li>
</ul>
</section>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>