<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="ES-es" xml:lang="ES-es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.335">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Javier Rodríguez Barrios">
<meta name="dcterms.date" content="2025-01-20">
<meta name="description" content="Análisis de escalamientos (nmds), de correspondencias simples (ca), de clúester (cla) y discriminantes (lda) para la exploración de los datos, así como las pruebas de hipótesis de diferencias entre sitios (manovas y permanovas) de acuerdo a los requerimientos del manuscrito de Lenin Florez.">

<title>Asesoría 3. Análisis de gradientes y conglomerados</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="multivar1.eng.peces_files/libs/clipboard/clipboard.min.js"></script>
<script src="multivar1.eng.peces_files/libs/quarto-html/quarto.js"></script>
<script src="multivar1.eng.peces_files/libs/quarto-html/popper.min.js"></script>
<script src="multivar1.eng.peces_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="multivar1.eng.peces_files/libs/quarto-html/anchor.min.js"></script>
<link href="multivar1.eng.peces_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="multivar1.eng.peces_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="multivar1.eng.peces_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="multivar1.eng.peces_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="multivar1.eng.peces_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<style>
    .quarto-title-block .quarto-title-banner {
      background: #2b8cbe;
    }
    </style>

<script src="multivar1.eng.peces_files/libs/kePrint-0.0.1/kePrint.js"></script>
<link href="multivar1.eng.peces_files/libs/lightable-0.0.1/lightable.css" rel="stylesheet">


<link rel="stylesheet" href="styles.css">
<link rel="stylesheet" href="stile-justify.css">
</head>

<body>

<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Asesoría 3. Análisis de gradientes y conglomerados</h1>
            <p class="subtitle lead">Técnicas de ordenación y de clasificación con datos peces estuarinos del Golfo de Urabá</p>
                  <div>
        <div class="description">
          Análisis de escalamientos (nmds), de correspondencias simples (ca), de clúester (cla) y discriminantes (lda) para la exploración de los datos, así como las pruebas de hipótesis de diferencias entre sitios (manovas y permanovas) de acuerdo a los requerimientos del manuscrito de Lenin Florez.
        </div>
      </div>
                </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Autor/a</div>
      <div class="quarto-title-meta-contents">
               <p>Javier Rodríguez Barrios </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Fecha de publicación</div>
      <div class="quarto-title-meta-contents">
        <p class="date">January 20, 2025</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Menú flotante</h2>
   
  <ul>
  <li><a href="#resumen" id="toc-resumen" class="nav-link active" data-scroll-target="#resumen">Resumen</a></li>
  <li><a href="#análisis-de-componentes-principales-pca" id="toc-análisis-de-componentes-principales-pca" class="nav-link" data-scroll-target="#análisis-de-componentes-principales-pca">1. Análisis de Componentes Principales (PCA)</a>
  <ul>
  <li><a href="#paso-1.-cargar-librerías" id="toc-paso-1.-cargar-librerías" class="nav-link" data-scroll-target="#paso-1.-cargar-librerías">Paso 1. Cargar Librerías</a></li>
  <li><a href="#paso-2.-base-de-datos-de-los-taxones" id="toc-paso-2.-base-de-datos-de-los-taxones" class="nav-link" data-scroll-target="#paso-2.-base-de-datos-de-los-taxones">Paso 2. Base de datos de los taxones</a></li>
  </ul></li>
  <li><a href="#escalamiento-multidimensional-no-métrico-nmds" id="toc-escalamiento-multidimensional-no-métrico-nmds" class="nav-link" data-scroll-target="#escalamiento-multidimensional-no-métrico-nmds">2. Escalamiento Multidimensional no Métrico (NMDS)</a>
  <ul>
  <li><a href="#paso-1.-cargar-librerías-1" id="toc-paso-1.-cargar-librerías-1" class="nav-link" data-scroll-target="#paso-1.-cargar-librerías-1">Paso 1. Cargar Librerías</a></li>
  <li><a href="#paso-2.-nmds" id="toc-paso-2.-nmds" class="nav-link" data-scroll-target="#paso-2.-nmds">Paso 2. NMDS</a></li>
  </ul></li>
  <li><a href="#análisis-de-correspondencia-simple-ca" id="toc-análisis-de-correspondencia-simple-ca" class="nav-link" data-scroll-target="#análisis-de-correspondencia-simple-ca">3. Análisis de Correspondencia Simple (CA)</a>
  <ul>
  <li><a href="#paso-1.-cargar-librerías-2" id="toc-paso-1.-cargar-librerías-2" class="nav-link" data-scroll-target="#paso-1.-cargar-librerías-2">Paso 1. Cargar Librerías</a></li>
  <li><a href="#paso-2.-ca-con-el-paquete-ggplo2" id="toc-paso-2.-ca-con-el-paquete-ggplo2" class="nav-link" data-scroll-target="#paso-2.-ca-con-el-paquete-ggplo2">Paso 2. CA con el paquete ggplo2</a></li>
  </ul></li>
  <li><a href="#rda" id="toc-rda" class="nav-link" data-scroll-target="#rda">4. RDA</a>
  <ul>
  <li><a href="#cargar-las-librerías-requeridas" id="toc-cargar-las-librerías-requeridas" class="nav-link" data-scroll-target="#cargar-las-librerías-requeridas">Cargar las librerías requeridas</a></li>
  <li><a href="#funciones-adicionales-bordcard-et-al.-2018" id="toc-funciones-adicionales-bordcard-et-al.-2018" class="nav-link" data-scroll-target="#funciones-adicionales-bordcard-et-al.-2018">Funciones adicionales (Bordcard et al.&nbsp;2018)</a></li>
  <li><a href="#ajuste-de-las-bases-de-datos-biológica-tax.hel-y-ambiental-amb" id="toc-ajuste-de-las-bases-de-datos-biológica-tax.hel-y-ambiental-amb" class="nav-link" data-scroll-target="#ajuste-de-las-bases-de-datos-biológica-tax.hel-y-ambiental-amb">Ajuste de las bases de datos biológica (tax.hel) y Ambiental (amb)</a></li>
  </ul></li>
  <li><a href="#doce-pasos-para-el-análisis-de-redundancia---rda." id="toc-doce-pasos-para-el-análisis-de-redundancia---rda." class="nav-link" data-scroll-target="#doce-pasos-para-el-análisis-de-redundancia---rda.">Doce pasos para el análisis de redundancia - RDA.</a>
  <ul>
  <li><a href="#paso-1.-ordenación-de-los-taxones-y-las-variables-ambientales." id="toc-paso-1.-ordenación-de-los-taxones-y-las-variables-ambientales." class="nav-link" data-scroll-target="#paso-1.-ordenación-de-los-taxones-y-las-variables-ambientales.">Paso 1. Ordenación de los taxones y las variables ambientales.</a></li>
  <li><a href="#paso-2.-coeficientes-de-las-variables-regresoras-ambientales-en-el-modelo-lineal." id="toc-paso-2.-coeficientes-de-las-variables-regresoras-ambientales-en-el-modelo-lineal." class="nav-link" data-scroll-target="#paso-2.-coeficientes-de-las-variables-regresoras-ambientales-en-el-modelo-lineal.">Paso 2. Coeficientes de las variables regresoras (ambientales), en el modelo lineal.</a></li>
  <li><a href="#paso-3.-r2-sin-ajuste-vs.-r2-ajustado-ezequiel-1930" id="toc-paso-3.-r2-sin-ajuste-vs.-r2-ajustado-ezequiel-1930" class="nav-link" data-scroll-target="#paso-3.-r2-sin-ajuste-vs.-r2-ajustado-ezequiel-1930">Paso 3. R2 sin ajuste vs.&nbsp;R2 ajustado (Ezequiel 1930)</a></li>
  <li><a href="#paso-5.-prueba-global-del-rda" id="toc-paso-5.-prueba-global-del-rda" class="nav-link" data-scroll-target="#paso-5.-prueba-global-del-rda">Paso 5. Prueba global del RDA</a></li>
  <li><a href="#paso-6.-factor-de-inflación-de-la-varianza-vif-del-rda" id="toc-paso-6.-factor-de-inflación-de-la-varianza-vif-del-rda" class="nav-link" data-scroll-target="#paso-6.-factor-de-inflación-de-la-varianza-vif-del-rda">Paso 6. Factor de inflación de la varianza (VIF) del RDA</a></li>
  <li><a href="#paso-7.-criterios-de-selección-de-variables-ambientales-x" id="toc-paso-7.-criterios-de-selección-de-variables-ambientales-x" class="nav-link" data-scroll-target="#paso-7.-criterios-de-selección-de-variables-ambientales-x">Paso 7. Criterios de selección de variables ambientales (X)</a>
  <ul>
  <li><a href="#forward-selection-usando-forward.sel" id="toc-forward-selection-usando-forward.sel" class="nav-link" data-scroll-target="#forward-selection-usando-forward.sel">7.1 Forward selection usando forward.sel()</a></li>
  <li><a href="#eliminación-anticipada-backward-usando-ordistep-de-vegan" id="toc-eliminación-anticipada-backward-usando-ordistep-de-vegan" class="nav-link" data-scroll-target="#eliminación-anticipada-backward-usando-ordistep-de-vegan">7.2 Eliminación anticipada (Backward) usando “ordistep()” de vegan</a></li>
  </ul></li>
  <li><a href="#paso-8.-r2-ajustado" id="toc-paso-8.-r2-ajustado" class="nav-link" data-scroll-target="#paso-8.-r2-ajustado">Paso 8. R2 ajustado</a></li>
  <li><a href="#paso-12.-rda-con-paquete-ggplot2" id="toc-paso-12.-rda-con-paquete-ggplot2" class="nav-link" data-scroll-target="#paso-12.-rda-con-paquete-ggplot2">Paso 12. RDA con paquete ggplot2</a>
  <ul>
  <li><a href="#coordenadas-de-los-sitios-y-el-factor-coord.sit" id="toc-coordenadas-de-los-sitios-y-el-factor-coord.sit" class="nav-link" data-scroll-target="#coordenadas-de-los-sitios-y-el-factor-coord.sit">12.1 Coordenadas de los sitios y el factor “coord.sit”</a></li>
  <li><a href="#coordenadas-de-los-taxones-coord.tax" id="toc-coordenadas-de-los-taxones-coord.tax" class="nav-link" data-scroll-target="#coordenadas-de-los-taxones-coord.tax">12.2 Coordenadas de los taxones “coord.tax”</a></li>
  <li><a href="#coordenadas-de-las-ambientales-coord.amb" id="toc-coordenadas-de-las-ambientales-coord.amb" class="nav-link" data-scroll-target="#coordenadas-de-las-ambientales-coord.amb">12.3 Coordenadas de las ambientales “coord.amb”</a></li>
  <li><a href="#figura-del-rda-con-vectores-de-especies" id="toc-figura-del-rda-con-vectores-de-especies" class="nav-link" data-scroll-target="#figura-del-rda-con-vectores-de-especies">12.4 Figura del RDA con vectores de especies</a></li>
  <li><a href="#figura-con-vectores-de-especies-y-ambientales" id="toc-figura-con-vectores-de-especies-y-ambientales" class="nav-link" data-scroll-target="#figura-con-vectores-de-especies-y-ambientales">12.6 Figura con vectores de especies y ambientales</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#bioenv" id="toc-bioenv" class="nav-link" data-scroll-target="#bioenv">4. Bioenv</a></li>
  <li><a href="#análisis-de-clúster-cla" id="toc-análisis-de-clúster-cla" class="nav-link" data-scroll-target="#análisis-de-clúster-cla">5. Análisis de Clúster (CLA)</a>
  <ul>
  <li><a href="#cargar-librerías" id="toc-cargar-librerías" class="nav-link" data-scroll-target="#cargar-librerías">Cargar Librerías</a></li>
  <li><a href="#paso-1.-distancia-entre-observaciones" id="toc-paso-1.-distancia-entre-observaciones" class="nav-link" data-scroll-target="#paso-1.-distancia-entre-observaciones">Paso 1. Distancia entre observaciones</a></li>
  <li><a href="#paso-2.-elección-del-método-de-agrupación-de-mayor-ajuste" id="toc-paso-2.-elección-del-método-de-agrupación-de-mayor-ajuste" class="nav-link" data-scroll-target="#paso-2.-elección-del-método-de-agrupación-de-mayor-ajuste">Paso 2. Elección del método de agrupación de mayor ajuste</a>
  <ul>
  <li><a href="#cálculo-de-los-siete-dendogramas" id="toc-cálculo-de-los-siete-dendogramas" class="nav-link" data-scroll-target="#cálculo-de-los-siete-dendogramas">2.1 Cálculo de los siete dendogramas</a></li>
  <li><a href="#cálculo-de-las-correlaciones-cofenéticas" id="toc-cálculo-de-las-correlaciones-cofenéticas" class="nav-link" data-scroll-target="#cálculo-de-las-correlaciones-cofenéticas">2.2 Cálculo de las correlaciones cofenéticas</a></li>
  </ul></li>
  <li><a href="#paso-3.-número-de-species-formados" id="toc-paso-3.-número-de-species-formados" class="nav-link" data-scroll-target="#paso-3.-número-de-species-formados">Paso 3. Número de Species formados</a>
  <ul>
  <li><a href="#método-de-silueta" id="toc-método-de-silueta" class="nav-link" data-scroll-target="#método-de-silueta">3.1 Método de silueta</a></li>
  <li><a href="#dendograma-jerárquico-final" id="toc-dendograma-jerárquico-final" class="nav-link" data-scroll-target="#dendograma-jerárquico-final">3.3 Dendograma jerárquico final</a></li>
  <li><a href="#dendograma-no-jerárquico-final" id="toc-dendograma-no-jerárquico-final" class="nav-link" data-scroll-target="#dendograma-no-jerárquico-final">3.4 Dendograma no jerárquico final</a></li>
  </ul></li>
  <li><a href="#paso-4.-aporte-de-las-variables-a-la-clasificación" id="toc-paso-4.-aporte-de-las-variables-a-la-clasificación" class="nav-link" data-scroll-target="#paso-4.-aporte-de-las-variables-a-la-clasificación">Paso 4. Aporte de las variables a la clasificación</a></li>
  </ul></li>
  <li><a href="#análisis-discriminante-lineal-lda" id="toc-análisis-discriminante-lineal-lda" class="nav-link" data-scroll-target="#análisis-discriminante-lineal-lda">6. Análisis Discriminante Lineal (LDA)</a>
  <ul>
  <li><a href="#cargar-librerías-1" id="toc-cargar-librerías-1" class="nav-link" data-scroll-target="#cargar-librerías-1">Cargar Librerías</a></li>
  <li><a href="#paso-1.-selección-de-una-muestra-aleatoria-para-el-lda" id="toc-paso-1.-selección-de-una-muestra-aleatoria-para-el-lda" class="nav-link" data-scroll-target="#paso-1.-selección-de-una-muestra-aleatoria-para-el-lda">Paso 1. selección de una muestra aleatoria para el lda</a></li>
  <li><a href="#paso-2.-supuestos-de-normalidad-y-homogeneidad-de-covarianzas" id="toc-paso-2.-supuestos-de-normalidad-y-homogeneidad-de-covarianzas" class="nav-link" data-scroll-target="#paso-2.-supuestos-de-normalidad-y-homogeneidad-de-covarianzas">Paso 2. Supuestos de normalidad y homogeneidad de covarianzas</a>
  <ul>
  <li><a href="#supuesto-1.-normalidad-multivariada" id="toc-supuesto-1.-normalidad-multivariada" class="nav-link" data-scroll-target="#supuesto-1.-normalidad-multivariada">Supuesto 1. Normalidad multivariada</a></li>
  <li><a href="#supuesto-2.-homogeneidad-de-covarianzas-esfericidad" id="toc-supuesto-2.-homogeneidad-de-covarianzas-esfericidad" class="nav-link" data-scroll-target="#supuesto-2.-homogeneidad-de-covarianzas-esfericidad">Supuesto 2. Homogeneidad de covarianzas (esfericidad)</a></li>
  </ul></li>
  <li><a href="#paso-3.-análisis-discriminante-lineal-de-fisher" id="toc-paso-3.-análisis-discriminante-lineal-de-fisher" class="nav-link" data-scroll-target="#paso-3.-análisis-discriminante-lineal-de-fisher">Paso 3. Análisis discriminante lineal de Fisher</a></li>
  <li><a href="#paso-4.-visualización-grafica-del-lda" id="toc-paso-4.-visualización-grafica-del-lda" class="nav-link" data-scroll-target="#paso-4.-visualización-grafica-del-lda">Paso 4. Visualización grafica del LDA</a></li>
  </ul></li>
  <li><a href="#manovas---species-taxonómicos-de-biol2" id="toc-manovas---species-taxonómicos-de-biol2" class="nav-link" data-scroll-target="#manovas---species-taxonómicos-de-biol2">7. Manovas - Species Taxonómicos de biol2</a>
  <ul>
  <li><a href="#paso-1.-análisis-de-varinaza-multivariado---manova" id="toc-paso-1.-análisis-de-varinaza-multivariado---manova" class="nav-link" data-scroll-target="#paso-1.-análisis-de-varinaza-multivariado---manova">Paso 1. Análisis de Varinaza Multivariado - MANOVA</a>
  <ul>
  <li><a href="#respuesta-de-cada-variable-a-las-diferencias-entre-moon" id="toc-respuesta-de-cada-variable-a-las-diferencias-entre-moon" class="nav-link" data-scroll-target="#respuesta-de-cada-variable-a-las-diferencias-entre-moon">1.1 Respuesta de cada variable a las diferencias entre Moon</a></li>
  <li><a href="#cuatro-tipos-de-manova" id="toc-cuatro-tipos-de-manova" class="nav-link" data-scroll-target="#cuatro-tipos-de-manova">1.2 Cuatro tipos de MANOVA</a></li>
  <li><a href="#supuesto-de-normalidad-de-los-residuales-del-manova" id="toc-supuesto-de-normalidad-de-los-residuales-del-manova" class="nav-link" data-scroll-target="#supuesto-de-normalidad-de-los-residuales-del-manova">1.3. Supuesto de normalidad de los residuales del MANOVA</a></li>
  <li><a href="#supuesto-de-independencia" id="toc-supuesto-de-independencia" class="nav-link" data-scroll-target="#supuesto-de-independencia">1.4. Supuesto de independencia</a></li>
  </ul></li>
  <li><a href="#permanova---ambientales.-permanova-de-dos-factores-a-2-vías" id="toc-permanova---ambientales.-permanova-de-dos-factores-a-2-vías" class="nav-link" data-scroll-target="#permanova---ambientales.-permanova-de-dos-factores-a-2-vías">Permanova - Ambientales. Permanova de dos factores (a 2 vías)</a>
  <ul>
  <li><a href="#paso-1.-disancia-entre-observaciones-hellinger-para-este-caso" id="toc-paso-1.-disancia-entre-observaciones-hellinger-para-este-caso" class="nav-link" data-scroll-target="#paso-1.-disancia-entre-observaciones-hellinger-para-este-caso">Paso 1. Disancia entre observaciones (Hellinger para este caso)</a></li>
  <li><a href="#paso-2.-prueba-de-hipótesis-de-igualdad-de-medias-multivariadas" id="toc-paso-2.-prueba-de-hipótesis-de-igualdad-de-medias-multivariadas" class="nav-link" data-scroll-target="#paso-2.-prueba-de-hipótesis-de-igualdad-de-medias-multivariadas">Paso 2. Prueba de hipótesis de igualdad de medias multivariadas</a></li>
  </ul></li>
  <li><a href="#permanova---biológicas.-permanova-de-dos-factores-a-2-vías" id="toc-permanova---biológicas.-permanova-de-dos-factores-a-2-vías" class="nav-link" data-scroll-target="#permanova---biológicas.-permanova-de-dos-factores-a-2-vías">Permanova - Biológicas. Permanova de dos factores (a 2 vías)</a>
  <ul>
  <li><a href="#paso-1.-disancia-entre-observaciones-hellinger-para-este-caso-1" id="toc-paso-1.-disancia-entre-observaciones-hellinger-para-este-caso-1" class="nav-link" data-scroll-target="#paso-1.-disancia-entre-observaciones-hellinger-para-este-caso-1">Paso 1. Disancia entre observaciones (Hellinger para este caso)</a></li>
  <li><a href="#paso-2.-prueba-de-hipótesis-de-igualdad-de-medias-multivariadas-1" id="toc-paso-2.-prueba-de-hipótesis-de-igualdad-de-medias-multivariadas-1" class="nav-link" data-scroll-target="#paso-2.-prueba-de-hipótesis-de-igualdad-de-medias-multivariadas-1">Paso 2. Prueba de hipótesis de igualdad de medias multivariadas</a></li>
  </ul></li>
  </ul></li>
  </ul>
</nav>
</div>
<main class="content quarto-banner-title-block" id="quarto-document-content">




<p><strong>Área de estudio</strong>: Zonas del Golfo de Urabá en Colombia.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="https://javier-2712.github.io/Manuscritos/4.peces.lenin/mangroves%20uraba.jpg" class="img-fluid figure-img" width="486"></p>
</figure>
</div>
<p><b style="color:#1f78b4;"></b></p><b style="color:#1f78b4;">
</b><section id="resumen" class="level2"><b style="color:#1f78b4;">
<h2 class="anchored" data-anchor-id="resumen">Resumen</h2>
</b><p><b style="color:#1f78b4;"></b></p>
<p>El presente ejercicio consiste en el procesamiento inicial de los datos entregados por los profesores <strong>Lenin Florez y Alejandro Sandoval</strong>, para dar respuesta al siguiente requerimiento: “<em>Analizar el efecto de cambios en las fases lunares (<strong>ciclo lunar - Moon</strong>) y horarios de <strong>día vs.&nbsp;noche</strong></em> (<strong><em>Time</em></strong>)<em>, sobre los patrones de <strong>abundancia de peces estuarinos, censados en el Golfo de Urabá y su relación con variables ambientales</strong></em>”.</p>
<ul>
<li><p><strong>Estructura de los datos:</strong></p>
<ul>
<li><p>Los datos tienen <strong>variables categóricas</strong> (como Semanas, fases lunares y jornadas día-noche)</p></li>
<li><p><strong>Las abundancias</strong> de los peces están organizadas por especies.</p></li>
<li><p><strong>Variables ambientales</strong>, tomadas en los mismos lugares y que pueden estar generando un efecto en la distribución de los peces.</p></li>
</ul></li>
</ul>
<hr>
<p><b style="color:#1f78b4;"></b></p><b style="color:#1f78b4;">
</b></section><b style="color:#1f78b4;">
</b><section id="análisis-de-componentes-principales-pca" class="level2"><b style="color:#1f78b4;">
<h2 class="anchored" data-anchor-id="análisis-de-componentes-principales-pca">1. Análisis de Componentes Principales (PCA)</h2>
</b><p><b style="color:#1f78b4;"></b></p>
<p><b style="color:#fc8d62;"></b></p><b style="color:#fc8d62;">
</b><section id="paso-1.-cargar-librerías" class="level3"><b style="color:#fc8d62;">
<h3 class="anchored" data-anchor-id="paso-1.-cargar-librerías">Paso 1. Cargar Librerías</h3>
</b><p><b style="color:#fc8d62;"></b></p>
<p>Librerías requeridas para el PCA.</p>
<div class="cell">

</div>
<hr>
<p><b style="color:#fc8d62;"></b></p><b style="color:#fc8d62;">
</b></section><b style="color:#fc8d62;">
</b><section id="paso-2.-base-de-datos-de-los-taxones" class="level3"><b style="color:#fc8d62;">
<h3 class="anchored" data-anchor-id="paso-2.-base-de-datos-de-los-taxones">Paso 2. Base de datos de los taxones</h3>
</b><p><b style="color:#fc8d62;"></b></p>
<p>La <a href="#tbl-tbl1">Tabla&nbsp;1</a> muestra la oranización de los Species de taxones (13), para los diferentes sitios o Moon (6), los Times (2) y los Zones (2).</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-tbl1" class="anchored">

<table class=" lightable-classic" style="font-family: Cambria; width: auto !important; margin-left: auto; margin-right: auto;">
<caption>Tabla&nbsp;1:  Base de datos biológicos </caption>
 <thead>
  <tr>
   <th style="text-align:left;"> Cod </th>
   <th style="text-align:left;"> Moon </th>
   <th style="text-align:left;"> Time </th>
   <th style="text-align:right;"> Zone </th>
   <th style="text-align:right;"> Achirus lineatus </th>
   <th style="text-align:right;"> Anchovia clupeoides </th>
   <th style="text-align:right;"> Ariopsis sp </th>
   <th style="text-align:right;"> Bardiela ronchus </th>
   <th style="text-align:right;"> Batrachoides surinamensis </th>
   <th style="text-align:right;"> Caranx crysos </th>
   <th style="text-align:right;"> Caranx hippos </th>
   <th style="text-align:right;"> Caranx latus </th>
   <th style="text-align:right;"> Cathorops mapale </th>
   <th style="text-align:right;"> Centropomus ensiferus </th>
   <th style="text-align:right;"> Centropomus pectinatus </th>
   <th style="text-align:right;"> Centropomus undecimalis </th>
   <th style="text-align:right;"> Cetengraulis edentulus </th>
   <th style="text-align:right;"> Chaetodipterus fabel </th>
   <th style="text-align:right;"> Citharichthys spilopterus </th>
   <th style="text-align:right;"> Dasyatis guttata </th>
   <th style="text-align:right;"> Diapterus rhombeus </th>
   <th style="text-align:right;"> Epinephelus itajara </th>
   <th style="text-align:right;"> Eugerres plumieri </th>
   <th style="text-align:right;"> Gerres cinereus </th>
   <th style="text-align:right;"> Gobiomorus dormitor </th>
   <th style="text-align:right;"> Gymnothorax ocellatus </th>
   <th style="text-align:right;"> Lutjanus analis </th>
   <th style="text-align:right;"> Lutjanus jocu </th>
   <th style="text-align:right;"> Lycengraulis grossidens </th>
   <th style="text-align:right;"> Megalops atlanticus </th>
   <th style="text-align:right;"> Menticirrhus americanus </th>
   <th style="text-align:right;"> Mugil incilis </th>
   <th style="text-align:right;"> Oligoplites saliens </th>
   <th style="text-align:right;"> Oligoplites saurus </th>
   <th style="text-align:right;"> Selene vomer </th>
   <th style="text-align:right;"> Sphoeroides testudineum </th>
   <th style="text-align:right;"> Stellifer sp </th>
   <th style="text-align:right;"> Strongylura timuco </th>
   <th style="text-align:right;"> Trichiurus lepturus </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> Wanc.D1 </td>
   <td style="text-align:left;"> Wan.cres </td>
   <td style="text-align:left;"> Day </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 3 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 2 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 2 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 2 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Wanc.D2 </td>
   <td style="text-align:left;"> Wan.cres </td>
   <td style="text-align:left;"> Day </td>
   <td style="text-align:right;"> 2 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 2 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 5 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 3 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 2 </td>
   <td style="text-align:right;"> 2 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Wanc.D3 </td>
   <td style="text-align:left;"> Wan.cres </td>
   <td style="text-align:left;"> Day </td>
   <td style="text-align:right;"> 3 </td>
   <td style="text-align:right;"> 3 </td>
   <td style="text-align:right;"> 2 </td>
   <td style="text-align:right;"> 6 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 8 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 3 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 2 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Wanc.N1 </td>
   <td style="text-align:left;"> Wan.cres </td>
   <td style="text-align:left;"> Night </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 3 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 10 </td>
   <td style="text-align:right;"> 2 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 5 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 3 </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 20 </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 5 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 4 </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 2 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Wanc.N2 </td>
   <td style="text-align:left;"> Wan.cres </td>
   <td style="text-align:left;"> Night </td>
   <td style="text-align:right;"> 2 </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 2 </td>
   <td style="text-align:right;"> 8 </td>
   <td style="text-align:right;"> 5 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 5 </td>
   <td style="text-align:right;"> 7 </td>
   <td style="text-align:right;"> 3 </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 19 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 4 </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 4 </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 6 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 2 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Wanc.N3 </td>
   <td style="text-align:left;"> Wan.cres </td>
   <td style="text-align:left;"> Night </td>
   <td style="text-align:right;"> 3 </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 5 </td>
   <td style="text-align:right;"> 11 </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 3 </td>
   <td style="text-align:right;"> 2 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 12 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 2 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 4 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 1 </td>
  </tr>
</tbody>
</table>

</div>
</div>
</div>
<p>Si los nombres de los taxones son demasiado largos, se pueden abreviar con el número de letras que se requiera (ej: minlength = 4), esto para que las figuras que incluyan a los taxones, no queden tan saturadas de texto (<strong>?@tbl-tbl2</strong>).</p>
<div id="tbl-tbl2" class="cell tbl-parent quarto-layout-panel anchored" data-tbl-cap="Resumen de los seis primeros datos de los taxones con nombres abreviados">

</div>
<div class="cell">
<div class="cell-output-display">

<table class=" lightable-classic" style="font-family: Cambria; width: auto !important; margin-left: auto; margin-right: auto;">
<caption></caption>
 <thead>
  <tr>
   <th style="text-align:left;"> Especies </th>
   <th style="text-align:left;"> Abreviaturas </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> Achirus lineatus </td>
   <td style="text-align:left;"> Achl </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Anchovia clupeoides </td>
   <td style="text-align:left;"> Ancc </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Ariopsis sp </td>
   <td style="text-align:left;"> Aris </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Bardiela ronchus </td>
   <td style="text-align:left;"> Barr </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Batrachoides surinamensis </td>
   <td style="text-align:left;"> Bats </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Caranx crysos </td>
   <td style="text-align:left;"> Carc </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Caranx hippos </td>
   <td style="text-align:left;"> Carh </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Caranx latus </td>
   <td style="text-align:left;"> Carl </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Cathorops mapale </td>
   <td style="text-align:left;"> Catm </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Centropomus ensiferus </td>
   <td style="text-align:left;"> Cene </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Centropomus pectinatus </td>
   <td style="text-align:left;"> Cenp </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Centropomus undecimalis </td>
   <td style="text-align:left;"> Cenu </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Cetengraulis edentulus </td>
   <td style="text-align:left;"> Cete </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Chaetodipterus fabel </td>
   <td style="text-align:left;"> Chaf </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Citharichthys spilopterus </td>
   <td style="text-align:left;"> Cits </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Dasyatis guttata </td>
   <td style="text-align:left;"> Dasg </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Diapterus rhombeus </td>
   <td style="text-align:left;"> Diar </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Epinephelus itajara </td>
   <td style="text-align:left;"> Epii </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Eugerres plumieri </td>
   <td style="text-align:left;"> Eugp </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Gerres cinereus </td>
   <td style="text-align:left;"> Gerc </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Gobiomorus dormitor </td>
   <td style="text-align:left;"> Gobd </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Gymnothorax ocellatus </td>
   <td style="text-align:left;"> Gymo </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Lutjanus analis </td>
   <td style="text-align:left;"> Luta </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Lutjanus jocu </td>
   <td style="text-align:left;"> Lutj </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Lycengraulis grossidens </td>
   <td style="text-align:left;"> Lycg </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Megalops atlanticus </td>
   <td style="text-align:left;"> Mega </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Menticirrhus americanus </td>
   <td style="text-align:left;"> Mena </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Mugil incilis </td>
   <td style="text-align:left;"> Mugi </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Oligoplites saliens </td>
   <td style="text-align:left;"> Olig </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Oligoplites saurus </td>
   <td style="text-align:left;"> Olig.1 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Selene vomer </td>
   <td style="text-align:left;"> Selv </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Sphoeroides testudineum </td>
   <td style="text-align:left;"> Spht </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Stellifer sp </td>
   <td style="text-align:left;"> Stes </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Strongylura timuco </td>
   <td style="text-align:left;"> Strt </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Trichiurus lepturus </td>
   <td style="text-align:left;"> Tril </td>
  </tr>
</tbody>
</table>

</div>
</div>
<div class="cell">

</div>
<p><strong>Variables ambientales + biológiccas</strong>: datos</p>
<p><strong>Variables biológicas</strong>: biol2, <strong>Biológicos Hell</strong>: biol2.h</p>
<p><strong>Variables ambientales</strong>: amb2</p>
<p><strong>Nota</strong>: Llegué hasta aquí, requiero:</p>
<ul>
<li>Cargar las figuras de Alejo, para tenerlas de comparación.</li>
</ul>
<hr>
<p><b style="color:#1f78b4;"></b></p><b style="color:#1f78b4;">
</b></section><b style="color:#1f78b4;">
</b></section><b style="color:#1f78b4;">
</b><section id="escalamiento-multidimensional-no-métrico-nmds" class="level2"><b style="color:#1f78b4;">
<h2 class="anchored" data-anchor-id="escalamiento-multidimensional-no-métrico-nmds">2. Escalamiento Multidimensional no Métrico (NMDS)</h2>
</b><p><b style="color:#1f78b4;"></b></p>
<p>Se aplicará esta técnica para explorar los gradientes en la ordenación de los sitios o Moon, su relación con los trece Species taxonómicos y las variables ambientales. Se utilizará la distancia Bray Curtis, para la asociación de los datos.</p>
<p><b style="color:#fc8d62;"></b></p><b style="color:#fc8d62;">
</b><section id="paso-1.-cargar-librerías-1" class="level3"><b style="color:#fc8d62;">
<h3 class="anchored" data-anchor-id="paso-1.-cargar-librerías-1">Paso 1. Cargar Librerías</h3>
</b><p><b style="color:#fc8d62;"></b></p>
<p>Se ejecutan las librerías necesarias para este análisis.</p>
<div class="cell">

</div>
<p><b style="color:#fc8d62;"></b></p><b style="color:#fc8d62;">
</b></section><b style="color:#fc8d62;">
</b><section id="paso-2.-nmds" class="level3"><b style="color:#fc8d62;">
<h3 class="anchored" data-anchor-id="paso-2.-nmds">Paso 2. NMDS</h3>
</b><p><b style="color:#fc8d62;"></b></p>
<p>Se utiliza la <strong>distancia Bray Curtis</strong> y el estrés generado es de <strong>0.17</strong> (17%), denotando una buena configuración para este análisis.</p>
<div class="cell">

</div>
<div class="cell">
<div class="cell-output-display">

<table class=" lightable-classic" style="font-family: Cambria; width: auto !important; margin-left: auto; margin-right: auto;">
<caption></caption>
 <thead>
  <tr>
   <th style="text-align:left;"> sitio </th>
   <th style="text-align:right;"> NMDS1 </th>
   <th style="text-align:right;"> NMDS2 </th>
   <th style="text-align:left;"> Moon </th>
   <th style="text-align:left;"> Time </th>
   <th style="text-align:right;"> Zone </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> Wanc.D1 </td>
   <td style="text-align:right;"> -0.0291456 </td>
   <td style="text-align:right;"> -0.5718580 </td>
   <td style="text-align:left;"> Wan.cres </td>
   <td style="text-align:left;"> Day </td>
   <td style="text-align:right;"> 1 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Wanc.D2 </td>
   <td style="text-align:right;"> -0.3355544 </td>
   <td style="text-align:right;"> -0.1622831 </td>
   <td style="text-align:left;"> Wan.cres </td>
   <td style="text-align:left;"> Day </td>
   <td style="text-align:right;"> 2 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Wanc.D3 </td>
   <td style="text-align:right;"> -0.0716100 </td>
   <td style="text-align:right;"> 0.3099774 </td>
   <td style="text-align:left;"> Wan.cres </td>
   <td style="text-align:left;"> Day </td>
   <td style="text-align:right;"> 3 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Wanc.N1 </td>
   <td style="text-align:right;"> -0.4937941 </td>
   <td style="text-align:right;"> 0.1358198 </td>
   <td style="text-align:left;"> Wan.cres </td>
   <td style="text-align:left;"> Night </td>
   <td style="text-align:right;"> 1 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Wanc.N2 </td>
   <td style="text-align:right;"> -0.5447319 </td>
   <td style="text-align:right;"> 0.1849498 </td>
   <td style="text-align:left;"> Wan.cres </td>
   <td style="text-align:left;"> Night </td>
   <td style="text-align:right;"> 2 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Wanc.N3 </td>
   <td style="text-align:right;"> -0.2798339 </td>
   <td style="text-align:right;"> 0.2273058 </td>
   <td style="text-align:left;"> Wan.cres </td>
   <td style="text-align:left;"> Night </td>
   <td style="text-align:right;"> 3 </td>
  </tr>
</tbody>
</table>

</div>
</div>
<p>A continuación se extraen las coordenadas de las Moon, Times, Zones, Species taxonómicos y variables ambientales, para ser ordenadas con la librería <strong>ggplo2</strong>.</p>
<div class="cell">

</div>
<div class="cell">

</div>
<p>L <a href="#fig-fig3">Figura&nbsp;1</a>, muestra la ordenación del NMDS para las referencias de las Moon, con los Species taxonómicos y las variables ambientales. No se logra apreciar un gradiente claro, aunque las Moon 9, 13 y 15 son las que agrupan mayor cantidad de taxones, asociadas a mayor Temperature y Salinity.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-fig3" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="multivar1.eng.peces_files/figure-html/fig-fig3-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Figura&nbsp;1: ordenación de de las Moon, con los Species taxonómicos y las variables ambientales</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>La <a href="#fig-fig4">Figura&nbsp;2</a> muestra la diferenciación por Moon, se logra observar un gradiente horizontal, en donde algunas Moon muestran diferencias por sus Species taxonómicos.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-fig4" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="multivar1.eng.peces_files/figure-html/fig-fig4-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Figura&nbsp;2: ordenación de de las Moon, con los Species taxonómicos</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>La <a href="#fig-fig5">Figura&nbsp;3</a> que la composición taxonómica con 250 micras, se encuentra anidada en 500 micras.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-fig5" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="multivar1.eng.peces_files/figure-html/fig-fig5-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Figura&nbsp;3: ordenación de de las Moon, con los Species taxonómicos entre dos categorías de Time</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>Similar a la <a href="#fig-fig5">Figura&nbsp;3</a>, la <a href="#fig-fig6">Figura&nbsp;4</a>, muestra ausencia de diferencias en la composición taxonómica entre Zones.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-fig6" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="multivar1.eng.peces_files/figure-html/fig-fig6-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Figura&nbsp;4: ordenación de de las Moon, con los Species taxonómicos entre Zones de superficie y de Zone</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>La <a href="#fig-fig7">Figura&nbsp;5</a> complementa a la <span class="citation" data-cites="fi4">@fi4</span>, al incorporar las variables ambientales en la caracterización de las Moon y de los Species taxonómicos.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-fig7" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="multivar1.eng.peces_files/figure-html/fig-fig7-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Figura&nbsp;5: ordenación de de las Moon, con los Species taxonómicos y las variables ambientales</figcaption><p></p>
</figure>
</div>
</div>
</div>
<hr>
<p><b style="color:#1f78b4;"></b></p><b style="color:#1f78b4;">
</b></section><b style="color:#1f78b4;">
</b></section><b style="color:#1f78b4;">
</b><section id="análisis-de-correspondencia-simple-ca" class="level2"><b style="color:#1f78b4;">
<h2 class="anchored" data-anchor-id="análisis-de-correspondencia-simple-ca">3. Análisis de Correspondencia Simple (CA)</h2>
</b><p><b style="color:#1f78b4;"></b></p>
<p>En este análisis se explora una propuesta complementaria a la realizada con el NMDS, con la diferencia de que se utilizará a la <strong>distancia chi cuadrado</strong>, para relacionar a las localidades y a los Species taxonómicos.</p>
<p><b style="color:#fc8d62;"></b></p><b style="color:#fc8d62;">
</b><section id="paso-1.-cargar-librerías-2" class="level3"><b style="color:#fc8d62;">
<h3 class="anchored" data-anchor-id="paso-1.-cargar-librerías-2">Paso 1. Cargar Librerías</h3>
</b><p><b style="color:#fc8d62;"></b></p>
<p>Se ejecutan las librerías necesarias para este análisis.</p>
<div class="cell">

</div>
<p><b style="color:#fc8d62;"></b></p><b style="color:#fc8d62;">
</b></section><b style="color:#fc8d62;">
</b><section id="paso-2.-ca-con-el-paquete-ggplo2" class="level3"><b style="color:#fc8d62;">
<h3 class="anchored" data-anchor-id="paso-2.-ca-con-el-paquete-ggplo2">Paso 2. CA con el paquete ggplo2</h3>
</b><p><b style="color:#fc8d62;"></b></p>
<p>Se utiliza la <strong>distancia Chi Cuadrado</strong> con las trece variables biológicas. La varanza capturada por los dos primeros ejes canónicos es de 0.86 (86%).</p>
<div class="cell">

</div>
<div class="cell">

</div>
<div class="cell">

</div>
<div class="cell">

</div>
<p>La <a href="#fig-fig8">Figura&nbsp;6</a> no muestra un gradiente muy claro en la caracterización de los Species taxonómicos para las Moon evaluadas.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-fig8" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="multivar1.eng.peces_files/figure-html/fig-fig8-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Figura&nbsp;6: ordenación de de las Moon, con los Species taxonómicos</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>La <a href="#fig-fig9">Figura&nbsp;7</a> tampoco permite visualizar un gradiente claro en la ordenación de los sitios y de los taxones.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-fig9" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="multivar1.eng.peces_files/figure-html/fig-fig9-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Figura&nbsp;7: ordenación de de las Moon, con los Species taxonómicos</figcaption><p></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<p><img src="multivar1.eng.peces_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<p><img src="multivar1.eng.peces_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<hr>
</section>
</section>
<section id="rda" class="level2">
<h2 class="anchored" data-anchor-id="rda">4. RDA</h2>
<p><b style="color:#1f78b4;"></b></p><b style="color:#1f78b4;">
</b><section id="cargar-las-librerías-requeridas" class="level4"><b style="color:#1f78b4;">
<h4 class="anchored" data-anchor-id="cargar-las-librerías-requeridas">Cargar las librerías requeridas</h4>
</b><p><b style="color:#1f78b4;"></b></p>
<div class="cell">
<details>
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Librerías requeridas</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ade4)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(adegraphics)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(adespatial)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(cocorresp)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(vegan)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MASS)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ellipse)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(FactoMineR)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rrcov)</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(reshape2)</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggrepel)</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggforce)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p><b style="color:#1f78b4;"></b></p><b style="color:#1f78b4;">
</b></section><b style="color:#1f78b4;">
</b><section id="funciones-adicionales-bordcard-et-al.-2018" class="level4"><b style="color:#1f78b4;">
<h4 class="anchored" data-anchor-id="funciones-adicionales-bordcard-et-al.-2018">Funciones adicionales (Bordcard et al.&nbsp;2018)</h4>
</b><p><b style="color:#1f78b4;"></b></p>
<div class="cell">
<details>
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Funciones a cargar</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"hcoplot.R"</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"triplot.rda.R"</span>)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"plot.lda.R"</span>)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"polyvars.R"</span>)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"screestick.R"</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p><b style="color:#1f78b4;"></b></p><b style="color:#1f78b4;">
</b></section><b style="color:#1f78b4;">
</b><section id="ajuste-de-las-bases-de-datos-biológica-tax.hel-y-ambiental-amb" class="level4"><b style="color:#1f78b4;">
<h4 class="anchored" data-anchor-id="ajuste-de-las-bases-de-datos-biológica-tax.hel-y-ambiental-amb">Ajuste de las bases de datos biológica (tax.hel) y Ambiental (amb)</h4>
</b><p><b style="color:#1f78b4;"></b></p>
<p>A continuación se realizará un ajuste de la base de datos, primero convirtiendo a la columna <code>Tributario</code> como un factor, luego transformando a las variables ambientales <code>amb</code> con logaritmo en base 10 y finalmente ajustando a los taxones <code>tax.hel</code> con la transformación de Hellinger. Las abreviaturas en las filas <code>T1.1, ..., T1.6, ...</code> Representan el número del tributario (<code>T1</code>) y el numero de la visita realizada al lugar de muestreo (<code>1</code>).</p>
<div class="cell">
<details>
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Igualar dimensiones de las matrices biológica y ambiental</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Base de datos amb</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>amb1 <span class="ot">&lt;-</span> <span class="fu">read_xlsx</span>(<span class="st">"datos.eng3.xlsx"</span>, <span class="st">"env1"</span>)</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Impresión de la base ambiental</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>amb1 <span class="ot">=</span><span class="fu">na.omit</span>(amb1)</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Quito la fila Wax. gibb - Day, porque no está en los biológicos</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>amb2 <span class="ot">=</span> amb1[<span class="sc">-</span><span class="dv">20</span>,]   <span class="co"># Quitar fila</span></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>amb2 <span class="ot">=</span> amb2[<span class="sc">-</span><span class="fu">c</span>(<span class="dv">5</span>)]  <span class="co"># Quitar columna hour</span></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Base biológica</span></span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>biol1 <span class="ot">&lt;-</span> <span class="fu">read_xlsx</span>(<span class="st">"datos.eng3.xlsx"</span>, <span class="st">"Taxa1"</span>)</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Abreviar los nombres de las especies, sin abreviar Moom y Time.</span></span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>biol <span class="ot">&lt;-</span> biol1[, <span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>, <span class="sc">-</span><span class="dv">2</span>)] <span class="sc">%&gt;%</span></span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename_with</span>(<span class="sc">~</span> {</span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Generar las abreviaturas y limitar a 4 caracteres</span></span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a>    abrev <span class="ot">&lt;-</span> <span class="fu">abbreviate</span>(., <span class="at">minlength =</span> <span class="dv">4</span>, <span class="at">use.classes =</span> <span class="cn">FALSE</span>)</span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a>    abrev <span class="ot">&lt;-</span> <span class="fu">substr</span>(abrev, <span class="dv">1</span>, <span class="dv">4</span>)  <span class="co"># Limitar a exactamente 4 caracteres</span></span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a>    <span class="fu">make.unique</span>(abrev)  <span class="co"># Asegurarse de que sean únicos</span></span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a>  })</span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a><span class="co"># Dataframe definitivo abreviado</span></span>
<span id="cb3-22"><a href="#cb3-22" aria-hidden="true" tabindex="-1"></a>biol <span class="ot">&lt;-</span> </span>
<span id="cb3-23"><a href="#cb3-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">data.frame</span>(biol1[,<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>],biol)</span>
<span id="cb3-24"><a href="#cb3-24" aria-hidden="true" tabindex="-1"></a><span class="co"># Impresión de la base biológica</span></span>
<span id="cb3-25"><a href="#cb3-25" aria-hidden="true" tabindex="-1"></a><span class="co"># Quito la fila Wax.cres - Night, porque no está en las ambientales</span></span>
<span id="cb3-26"><a href="#cb3-26" aria-hidden="true" tabindex="-1"></a>biol2 <span class="ot">=</span> biol[<span class="sc">-</span><span class="dv">18</span>,] </span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Los datos de abundancia de los taxones están en cifras decimales, debido a la transformación logarítmica que se les aplicó.</p>
<div class="cell">
<details>
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Variables biológicas linealizadas - Taxones con Hellinger</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">rownames</span>(biol2) <span class="ot">&lt;-</span> biol2[,<span class="dv">1</span>]</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>tax.hel<span class="ot">=</span><span class="fu">decostand</span>(biol2[,<span class="sc">-</span><span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>)],<span class="st">"hellinger"</span>)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">head</span>(tax.hel),<span class="dv">2</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>        Achl Ancc Aris Barr Bats Carc Carh Carl Catm Cene Cenp Cenu Cete Chaf
Wanc.D1 0.52 0.00 0.43 0.00    0    0 0.00    0 0.43 0.00 0.00 0.00 0.00 0.00
Wanc.D2 0.00 0.23 0.32 0.00    0    0 0.23    0 0.51 0.00 0.00 0.00 0.23 0.00
Wanc.D3 0.32 0.26 0.45 0.00    0    0 0.00    0 0.19 0.00 0.00 0.00 0.53 0.00
Wanc.N1 0.23 0.00 0.42 0.19    0    0 0.00    0 0.30 0.00 0.23 0.13 0.59 0.13
Wanc.N2 0.12 0.17 0.33 0.26    0    0 0.00    0 0.26 0.31 0.20 0.12 0.51 0.00
Wanc.N3 0.15 0.34 0.50 0.15    0    0 0.00    0 0.00 0.26 0.21 0.00 0.52 0.00
        Cits Dasg Diar Epii Eugp Gerc Gobd Gymo Luta Lutj Lycg Mega Mena Mugi
Wanc.D1 0.43    0 0.30 0.00 0.00    0  0.3 0.00    0    0 0.00 0.00 0.00 0.00
Wanc.D2 0.23    0 0.40 0.00 0.00    0  0.0 0.00    0    0 0.23 0.00 0.00 0.32
Wanc.D3 0.32    0 0.00 0.00 0.00    0  0.0 0.00    0    0 0.19 0.00 0.19 0.26
Wanc.N1 0.00    0 0.30 0.00 0.00    0  0.0 0.00    0    0 0.00 0.00 0.00 0.26
Wanc.N2 0.12    0 0.23 0.12 0.12    0  0.0 0.00    0    0 0.00 0.12 0.12 0.23
Wanc.N3 0.00    0 0.21 0.00 0.00    0  0.0 0.15    0    0 0.00 0.00 0.00 0.30
        Olig Olig.1 Selv Spht Stes Strt Tril
Wanc.D1 0.00   0.00    0 0.00 0.00    0 0.00
Wanc.D2 0.32   0.00    0 0.00 0.00    0 0.00
Wanc.D3 0.00   0.19    0 0.19 0.00    0 0.00
Wanc.N1 0.13   0.00    0 0.00 0.00    0 0.19
Wanc.N2 0.12   0.00    0 0.00 0.29    0 0.17
Wanc.N3 0.00   0.15    0 0.00 0.00    0 0.15</code></pre>
</div>
</div>
<p><b style="color:#1f78b4;"></b></p><b style="color:#1f78b4;">
</b></section><b style="color:#1f78b4;">
</b></section><b style="color:#1f78b4;">
</b><section id="doce-pasos-para-el-análisis-de-redundancia---rda." class="level2"><b style="color:#1f78b4;">
<h2 class="anchored" data-anchor-id="doce-pasos-para-el-análisis-de-redundancia---rda.">Doce pasos para el análisis de redundancia - RDA.</h2>
</b><p><b style="color:#1f78b4;"></b></p>
<p><b style="color:#1f78b4;"></b></p><b style="color:#1f78b4;">
</b><section id="paso-1.-ordenación-de-los-taxones-y-las-variables-ambientales." class="level3"><b style="color:#1f78b4;">
<h3 class="anchored" data-anchor-id="paso-1.-ordenación-de-los-taxones-y-las-variables-ambientales.">Paso 1. Ordenación de los taxones y las variables ambientales.</h3>
</b><p><b style="color:#1f78b4;"></b></p>
<p>En el siguiente analisis se relaciona a la matriz de datos biológicos (abundancia de taxones) con la matriz de datos ambientales. A continuación se determinan los insumos generales del análisis.</p>
<div class="cell">
<details>
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 1. Realización del RDA</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>tax.rda<span class="ot">&lt;-</span><span class="fu">rda</span>(tax.hel <span class="sc">~</span>.,amb2[,<span class="sc">-</span><span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>)])</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>tax.rda <span class="co"># Resultados resumidos</span></span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Call: rda(formula = tax.hel ~ pH + `%OD` + OD + Conduct + TDS + UPS + Temp,
data = amb2[, -c(1:4)])

-- Model Summary --

              Inertia Proportion Rank
Total          0.4838     1.0000     
Constrained    0.1843     0.3810    7
Unconstrained  0.2995     0.6190   14

Inertia is variance

-- Eigenvalues --

Eigenvalues for constrained axes:
   RDA1    RDA2    RDA3    RDA4    RDA5    RDA6    RDA7 
0.08748 0.02908 0.02229 0.02075 0.01452 0.00636 0.00387 

Eigenvalues for unconstrained axes:
    PC1     PC2     PC3     PC4     PC5     PC6     PC7     PC8     PC9    PC10 
0.07973 0.05546 0.03768 0.03305 0.02300 0.01980 0.01304 0.01085 0.00844 0.00618 
   PC11    PC12    PC13    PC14 
0.00488 0.00361 0.00215 0.00163 </code></pre>
</div>
</div>
<p><em>Matriz 1</em>. <code>Partición de la varianza</code>. La inercia restringida es la que define el ajuste (restringida) en la relación entre las dos matrices de variables. Para este caso es de 0.54 (54%). Más adelante se aplicará el R2 de Ezequiel (1930), para encontrar el ajuste sin restricción (ajuste final del RDA). A continuación se muestra el comando para presentar los resultados detallados del RDA.</p>
<p><em>Matriz 2</em>. <code>Importancia de los componentes</code>. Muestra que se requiere de 10 ejes canónidos (RDA) para explicar el 54% de la varianza explicada por la inercia restringida. La inercia restante se explica por los ejes de los 12 componentes principales PC.</p>
<p><em>Matriz 3</em>. <code>Species scores</code>, muestra las coordenadas de las especies en los ejes canónicos, de los cuales se graficarán los dos primeros.</p>
<p><em>Matriz 4</em>. <code>Site scores</code>, Muestra las coordenadas de los sitios</p>
<p><em>Matriz 5</em>. <code>Site constraints</code>, muestra a las coordenadas de los sitos en el espacio de los taxones.</p>
<p><em>Matriz 6</em>. <code>Biplot scores</code>, muestra las coordenadas de las variables ambientales.</p>
<div class="cell">
<details>
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(tax.rda) <span class="co"># Resultados completos</span></span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
rda(formula = tax.hel ~ pH + `%OD` + OD + Conduct + TDS + UPS +      Temp, data = amb2[, -c(1:4)]) 

Partitioning of variance:
              Inertia Proportion
Total          0.4838      1.000
Constrained    0.1843      0.381
Unconstrained  0.2995      0.619

Eigenvalues, and their contribution to the variance 

Importance of components:
                         RDA1    RDA2    RDA3    RDA4    RDA5     RDA6     RDA7
Eigenvalue            0.08748 0.02908 0.02229 0.02075 0.01452 0.006356 0.003866
Proportion Explained  0.18081 0.06009 0.04607 0.04290 0.03001 0.013137 0.007990
Cumulative Proportion 0.18081 0.24090 0.28697 0.32987 0.35988 0.373019 0.381009
                          PC1     PC2     PC3     PC4     PC5     PC6     PC7
Eigenvalue            0.07973 0.05546 0.03768 0.03305 0.02300 0.01980 0.01304
Proportion Explained  0.16478 0.11462 0.07787 0.06831 0.04753 0.04091 0.02696
Cumulative Proportion 0.54579 0.66040 0.73828 0.80659 0.85412 0.89503 0.92199
                          PC8      PC9     PC10     PC11     PC12     PC13
Eigenvalue            0.01085 0.008441 0.006181 0.004884 0.003615 0.002145
Proportion Explained  0.02242 0.017445 0.012775 0.010094 0.007471 0.004434
Cumulative Proportion 0.94442 0.961864 0.974639 0.984733 0.992204 0.996638
                          PC14
Eigenvalue            0.001627
Proportion Explained  0.003362
Cumulative Proportion 1.000000

Accumulated constrained eigenvalues
Importance of components:
                         RDA1    RDA2    RDA3    RDA4    RDA5     RDA6     RDA7
Eigenvalue            0.08748 0.02908 0.02229 0.02075 0.01452 0.006356 0.003866
Proportion Explained  0.47456 0.15773 0.12091 0.11259 0.07877 0.034479 0.020971
Cumulative Proportion 0.47456 0.63228 0.75319 0.86578 0.94455 0.979029 1.000000</code></pre>
</div>
</div>
<p>A continuación se muestra una manera de extraer algunos insumos por separado del anterior comando <code>summary(tax.rda)</code>. Las coordenadas de los taxonesy de los sitios serán tenidas en cuenta más adelante, para las figuras de <code>ggplot2</code>.</p>
<div class="cell">
<details>
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Matriz 3. Escores o coordenadas de los taxones</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>species.scores <span class="ot">&lt;-</span> <span class="fu">summary</span>(tax.rda)<span class="sc">$</span><span class="st">"species"</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Escores o coordenadas de los sitios</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>site.scores <span class="ot">&lt;-</span> <span class="fu">summary</span>(tax.rda)<span class="sc">$</span><span class="st">"sites"</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Escores de las variables restringidas</span></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>biplot.scores <span class="ot">&lt;-</span> <span class="fu">summary</span>(tax.rda)<span class="sc">$</span><span class="st">"biplot"</span></span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p><b style="color:#1f78b4;"></b></p><b style="color:#1f78b4;">
</b></section><b style="color:#1f78b4;">
</b><section id="paso-2.-coeficientes-de-las-variables-regresoras-ambientales-en-el-modelo-lineal." class="level3"><b style="color:#1f78b4;">
<h3 class="anchored" data-anchor-id="paso-2.-coeficientes-de-las-variables-regresoras-ambientales-en-el-modelo-lineal.">Paso 2. Coeficientes de las variables regresoras (ambientales), en el modelo lineal.</h3>
</b><p><b style="color:#1f78b4;"></b></p>
<p>Solo se mostrarán los tres primeros ejes canónicos <code>[,1:3]</code>, para facilidad de su interpretación.</p>
<div class="cell">
<details>
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">coef</span>(tax.rda),<span class="dv">2</span>)[,<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>]</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>         RDA1  RDA2  RDA3
pH       0.01  0.07 -0.11
`%OD`   -0.03 -0.01 -0.01
OD      -0.03  0.39  0.01
Conduct  0.02  0.03  0.01
TDS     -0.08  0.00 -0.09
UPS      0.03 -0.06 -0.01
Temp     0.12  0.12  0.05</code></pre>
</div>
</div>
<p>Se puede pensar en un modelo lineal, que tiene en cuenta a los coeficientes descritos en el primer eje canónico:</p>
<p><b style="color:#1f78b4;"></b></p><b style="color:#1f78b4;">
<p>Distribución de los taxones de microalgas (<strong>Matriz Y</strong>) = 0.01(<strong>Amonio</strong>) – 0.18(<strong>Nitrito</strong>) + … + 0.06(<strong>Temp</strong>)</p>
</b><p><b style="color:#1f78b4;"></b></p>
<p><b style="color:#1f78b4;"></b></p><b style="color:#1f78b4;">
</b></section><b style="color:#1f78b4;">
</b><section id="paso-3.-r2-sin-ajuste-vs.-r2-ajustado-ezequiel-1930" class="level3"><b style="color:#1f78b4;">
<h3 class="anchored" data-anchor-id="paso-3.-r2-sin-ajuste-vs.-r2-ajustado-ezequiel-1930">Paso 3. R2 sin ajuste vs.&nbsp;R2 ajustado (Ezequiel 1930)</h3>
</b><p><b style="color:#1f78b4;"></b></p>
<p>La nueva inercia no sesgada (sin restricción) calculada con la formula de Ezequiel es de 0.19 o del 19%.</p>
<div class="cell">
<details>
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># R^2 sin ajuste (inercia restringida)</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>(R2 <span class="ot">&lt;-</span> <span class="fu">RsquareAdj</span>(tax.rda)<span class="sc">$</span>r.squared)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.3810088</code></pre>
</div>
<details>
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># R^2 ajustado</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>(R2adj <span class="ot">&lt;-</span> <span class="fu">RsquareAdj</span>(tax.rda)<span class="sc">$</span>adj.r.squared)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.07151324</code></pre>
</div>
</div>
<p><b style="color:#1f78b4;"></b></p><b style="color:#1f78b4;">
</b></section><b style="color:#1f78b4;">
</b><section id="paso-5.-prueba-global-del-rda" class="level3"><b style="color:#1f78b4;">
<h3 class="anchored" data-anchor-id="paso-5.-prueba-global-del-rda">Paso 5. Prueba global del RDA</h3>
</b><p><b style="color:#1f78b4;"></b></p>
<p>Esta prueba obtiene un valor p = 0.04296 *, por lo cual se valida que el modelo de regresión múltiple de este RDA presenta un ajuste apropiado ( a pesar de la poca inercia encontrada).</p>
<div class="cell">
<details>
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Prueba global del RDA (dos opciones)</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Ho= no hay relación entre las variables X y las Y</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(tax.rda, <span class="at">permutations =</span> <span class="fu">how</span>(<span class="at">nperm =</span> <span class="dv">1000</span>))</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Permutation test for rda under reduced model
Permutation: free
Number of permutations: 1000

Model: rda(formula = tax.hel ~ pH + `%OD` + OD + Conduct + TDS + UPS + Temp, data = amb2[, -c(1:4)])
         Df Variance      F Pr(&gt;F)
Model     7  0.18435 1.2311 0.1319
Residual 14  0.29949              </code></pre>
</div>
</div>
<p>A continuación se muestra que ninguno de los ejes canónicos prsenta significancia para la ordenación de las variables y de las observaciones de este análisis (valor p &gt; 0.05), sin embargo se continuará con el procedimiento.</p>
<div class="cell">
<details>
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Prueba de los ejes canónicos</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(tax.rda, <span class="at">by =</span> <span class="st">"axis"</span>, <span class="at">permutations =</span> <span class="fu">how</span>(<span class="at">nperm =</span> <span class="dv">1000</span>))</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Permutation test for rda under reduced model
Forward tests for axes
Permutation: free
Number of permutations: 1000

Model: rda(formula = tax.hel ~ pH + `%OD` + OD + Conduct + TDS + UPS + Temp, data = amb2[, -c(1:4)])
         Df Variance      F  Pr(&gt;F)  
RDA1      1 0.087483 4.0895 0.02797 *
RDA2      1 0.029076 1.3592 0.96204  
RDA3      1 0.022290 1.0420 0.99500  
RDA4      1 0.020755 0.9702 0.99500  
RDA5      1 0.014521 0.6788 0.99700  
RDA6      1 0.006356 0.2971 1.00000  
RDA7      1 0.003866 0.1807          
Residual 14 0.299493                 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p><b style="color:#1f78b4;"></b></p><b style="color:#1f78b4;">
</b></section><b style="color:#1f78b4;">
</b><section id="paso-6.-factor-de-inflación-de-la-varianza-vif-del-rda" class="level3"><b style="color:#1f78b4;">
<h3 class="anchored" data-anchor-id="paso-6.-factor-de-inflación-de-la-varianza-vif-del-rda">Paso 6. Factor de inflación de la varianza (VIF) del RDA</h3>
</b><p><b style="color:#1f78b4;"></b></p>
<div class="cell">
<details>
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Factor de inflación</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">vif.cca</span>(tax.rda), <span class="dv">2</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>     pH   `%OD`      OD Conduct     TDS     UPS    Temp 
   1.86    4.71    5.06    3.09    7.17    6.28    1.80 </code></pre>
</div>
</div>
<p>Los resultados están por debajo de un VIF de 10, por lo que todas las variables son importantes para el análisis.</p>
<p><b style="color:#1f78b4;"></b></p><b style="color:#1f78b4;">
</b></section><b style="color:#1f78b4;">
</b><section id="paso-7.-criterios-de-selección-de-variables-ambientales-x" class="level3"><b style="color:#1f78b4;">
<h3 class="anchored" data-anchor-id="paso-7.-criterios-de-selección-de-variables-ambientales-x">Paso 7. Criterios de selección de variables ambientales (X)</h3>
</b><p><b style="color:#1f78b4;"></b></p>
<section id="forward-selection-usando-forward.sel" class="level4">
<h4 class="anchored" data-anchor-id="forward-selection-usando-forward.sel">7.1 Forward selection usando forward.sel()</h4>
<p>El comando <code>forward.sel</code>permitirá definir a las variables ambientales con importancia para ser relacionadas con los taxones en el RDA. Para este caso define a la <em>Conductividad</em> y a la <em>Velocidad del la Corriente</em>.</p>
<div class="cell">
<details>
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Factor de inflación</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="fu">forward.sel</span>(tax.hel, amb2[,<span class="sc">-</span><span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>)], <span class="at">adjR2thresh =</span> R2adj)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Testing variable 1
Testing variable 2
Procedure stopped (adjR2thresh criteria) adjR2cum = 0.089829 with 2 variables (&gt; 0.071513)</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>  variables order        R2     R2Cum   AdjR2Cum       F pvalue
1        OD     3 0.1031579 0.1031579 0.05831579 2.30047  0.013</code></pre>
</div>
</div>
</section>
<section id="eliminación-anticipada-backward-usando-ordistep-de-vegan" class="level4">
<h4 class="anchored" data-anchor-id="eliminación-anticipada-backward-usando-ordistep-de-vegan">7.2 Eliminación anticipada (Backward) usando “ordistep()” de vegan</h4>
<p>El anterior resultado es validado por esta función <code>ordistep</code>, la cual luego de varias corridas, define a las mismas variables ambientales <em>Conductividad</em> y a la <em>Velocidad del la Corriente</em>, pero incluye a la <em>Temperatura</em> como las significativas para el análisis RDA. Para continuar el ejercicio, a continuación se realizará un nuevo RDA (RDA parsimonioso) con estas tres variables.</p>
<div class="cell">
<details>
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 7.2 Eliminación anticipada (Backward) usando "ordistep()" de vegan</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>step.backward <span class="ot">&lt;-</span> <span class="fu">ordistep</span>(tax.rda,<span class="at">permutations =</span> <span class="fu">how</span>(<span class="at">nperm =</span> <span class="dv">499</span>))</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Start: tax.hel ~ pH + `%OD` + OD + Conduct + TDS + UPS + Temp 

          Df     AIC      F Pr(&gt;F)
- OD       1 -12.885 0.4284  0.954
- pH       1 -12.571 0.6359  0.846
- `%OD`    1 -12.628 0.5980  0.822
- UPS      1 -11.848 1.1244  0.352
- Temp     1 -11.709 1.2208  0.236
- TDS      1 -11.608 1.2907  0.228
- Conduct  1 -11.413 1.4265  0.186

Step: tax.hel ~ pH + `%OD` + Conduct + TDS + UPS + Temp 

          Df     AIC      F Pr(&gt;F)  
- pH       1 -13.883 0.6991  0.748  
- UPS      1 -13.229 1.1728  0.264  
- Conduct  1 -12.838 1.4622  0.176  
- Temp     1 -13.003 1.3397  0.170  
- TDS      1 -12.873 1.4363  0.124  
- `%OD`    1 -12.410 1.7860  0.062 .
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Step: tax.hel ~ `%OD` + Conduct + TDS + UPS + Temp 

          Df     AIC      F Pr(&gt;F)  
- UPS      1 -14.264 1.2213  0.236  
- Temp     1 -14.075 1.3704  0.168  
- TDS      1 -13.967 1.4555  0.138  
- Conduct  1 -13.684 1.6821  0.116  
- `%OD`    1 -13.029 2.2161  0.016 *
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Step: tax.hel ~ `%OD` + Conduct + TDS + Temp 

          Df     AIC      F Pr(&gt;F)   
- Temp     1 -14.476 1.4397  0.150   
- TDS      1 -14.374 1.5255  0.142   
- Conduct  1 -14.158 1.7083  0.078 . 
- `%OD`    1 -13.202 2.5387  0.004 **
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Step: tax.hel ~ `%OD` + Conduct + TDS 

          Df     AIC      F Pr(&gt;F)  
- TDS      1 -15.306 0.9830  0.418  
- Conduct  1 -14.612 1.5915  0.140  
- `%OD`    1 -13.937 2.2023  0.016 *
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Step: tax.hel ~ `%OD` + Conduct 

          Df     AIC      F Pr(&gt;F)  
- Conduct  1 -14.982 2.1169  0.022 *
- `%OD`    1 -14.819 2.2747  0.016 *
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p><b style="color:#1f78b4;"></b></p><b style="color:#1f78b4;">
</b></section><b style="color:#1f78b4;">
</b></section><b style="color:#1f78b4;">
</b><section id="paso-8.-r2-ajustado" class="level3"><b style="color:#1f78b4;">
<h3 class="anchored" data-anchor-id="paso-8.-r2-ajustado">Paso 8. R2 ajustado</h3>
</b><p><b style="color:#1f78b4;"></b></p>
<p>Al validar el ajuste del RDA con las dos variables seleccionadas, se obtiene un valor de 0.3 o 30% de ajuste.</p>
<div class="cell">
<details>
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Se define un R^2: 0.3 (30% de relación)</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="fu">RsquareAdj</span>(step.backward)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>$r.squared
[1] 0.1779442

$adj.r.squared
[1] 0.09141204</code></pre>
</div>
</div>
<p>#—-</p>
<p><b style="color:#1f78b4;"></b></p><b style="color:#1f78b4;">
</b></section><b style="color:#1f78b4;">
</b><section id="paso-12.-rda-con-paquete-ggplot2" class="level3"><b style="color:#1f78b4;">
<h3 class="anchored" data-anchor-id="paso-12.-rda-con-paquete-ggplot2">Paso 12. RDA con paquete ggplot2</h3>
</b><p><b style="color:#1f78b4;"></b></p>
<p>Se realizará la figura del RDA con el paquete <code>ggplot2</code>, dada su mejor presentación, comparado a las figuras anteriores, realizadas con el paquete <code>vegan</code>. Los siguientes comandos sirven para identificar las coorddenadas de los sitios (“<code>sites</code>”), los taxones (“<code>sp</code>”) y las variables ambientales (“<code>vectors</code>”).</p>
<div class="cell">
<details>
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Insumos del RDA parsimonioso o que resume a las tres variables</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="fu">rownames</span>(biol2) <span class="ot">&lt;-</span> biol2[,<span class="dv">1</span>]</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>amb2 <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(amb2)</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a><span class="fu">rownames</span>(amb2)  <span class="ot">&lt;-</span> amb2[,<span class="dv">1</span>]</span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>(rda.pars <span class="ot">&lt;-</span> <span class="fu">rda</span>(tax.hel <span class="sc">~</span> pH<span class="sc">+</span>OD<span class="sc">+</span>Conduct<span class="sc">+</span>TDS<span class="sc">+</span>UPS<span class="sc">+</span>Temp, <span class="at">data =</span> amb2))    <span class="co"># RDA resumido.</span></span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Call: rda(formula = tax.hel ~ pH + OD + Conduct + TDS + UPS + Temp, data =
amb2)

-- Model Summary --

              Inertia Proportion Rank
Total          0.4838     1.0000     
Constrained    0.1716     0.3546    6
Unconstrained  0.3123     0.6454   15

Inertia is variance

-- Eigenvalues --

Eigenvalues for constrained axes:
   RDA1    RDA2    RDA3    RDA4    RDA5    RDA6 
0.08068 0.02886 0.02219 0.02067 0.01451 0.00465 

Eigenvalues for unconstrained axes:
    PC1     PC2     PC3     PC4     PC5     PC6     PC7     PC8     PC9    PC10 
0.08186 0.05619 0.04167 0.03376 0.02300 0.02018 0.01308 0.01128 0.00929 0.00621 
   PC11    PC12    PC13    PC14    PC15 
0.00516 0.00390 0.00313 0.00215 0.00143 </code></pre>
</div>
<details>
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(<span class="fu">summary</span>(rda.pars))    <span class="co"># Insumos del RDA parsimonioso</span></span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "species"     "sites"       "constraints" "biplot"      "call"       
 [6] "tot.chi"     "constr.chi"  "unconst.chi" "cont"        "concont"    
[11] "scaling"     "digits"      "inertia"     "method"     </code></pre>
</div>
</div>
<p><b style="color:#fc8d62;"></b></p><b style="color:#fc8d62;">
</b><section id="coordenadas-de-los-sitios-y-el-factor-coord.sit" class="level4"><b style="color:#fc8d62;">
<h4 class="anchored" data-anchor-id="coordenadas-de-los-sitios-y-el-factor-coord.sit">12.1 Coordenadas de los sitios y el factor “coord.sit”</h4>
</b><p><b style="color:#fc8d62;"></b></p>
<div class="cell">
<details>
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 1) Coordenadas de los sitios y el factor (coord.sit)</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>coord.sit <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">summary</span>(rda.pars)<span class="sc">$</span><span class="st">"sites"</span>[,<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>])     <span class="co"># Coordenadas de los sitios</span></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>coord.sit<span class="sc">$</span>sitio <span class="ot">&lt;-</span> <span class="fu">rownames</span>(coord.sit)      <span class="co"># Crear una columna con nombres de los sitios</span></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>coord.sit<span class="sc">$</span>grp <span class="ot">&lt;-</span>  amb2<span class="sc">$</span>Moon                <span class="co"># Adicionar columna de grupos por Tributario</span></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(coord.sit)                             <span class="co"># vista resumida de las coordenadas de sitios</span></span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>               RDA1       RDA2   sitio      grp
Wanc.D1  0.58911795 -0.1440437 Wanc.D1 Wan.cres
Wanc.D2 -0.05035445  0.2334305 Wanc.D2 Wan.cres
Wanc.D3 -0.28544454 -0.5672835 Wanc.D3 Wan.cres
Wanc.N1 -0.41938633  0.2181309 Wanc.N1 Wan.cres
Wanc.N2 -0.44724903  0.3753993 Wanc.N2 Wan.cres
Wanc.N3 -0.32782470  0.1723011 Wanc.N3 Wan.cres</code></pre>
</div>
</div>
<p><b style="color:#fc8d62;"></b></p><b style="color:#fc8d62;">
</b></section><b style="color:#fc8d62;">
</b><section id="coordenadas-de-los-taxones-coord.tax" class="level4"><b style="color:#fc8d62;">
<h4 class="anchored" data-anchor-id="coordenadas-de-los-taxones-coord.tax">12.2 Coordenadas de los taxones “coord.tax”</h4>
</b><p><b style="color:#fc8d62;"></b></p>
<div class="cell">
<details>
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 2) Coordenadasde las especies (coord.tax) </span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>coord.tax <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">summary</span>(rda.pars)<span class="sc">$</span><span class="st">"species"</span>[,<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>])    <span class="co"># Dos primeros ejes</span></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>coord.tax<span class="sc">$</span>especies <span class="ot">&lt;-</span> <span class="fu">rownames</span>(coord.tax)       <span class="co"># Insertar columna con nombres de las especies</span></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(coord.tax) </span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>             RDA1         RDA2 especies
Achl  0.060537525 -0.062888083     Achl
Ancc -0.034366557 -0.052361878     Ancc
Aris  0.245373795  0.046613637     Aris
Barr -0.112650221  0.047414463     Barr
Bats -0.019716646  0.008681567     Bats
Carc -0.008684735  0.009325004     Carc</code></pre>
</div>
</div>
<p><b style="color:#fc8d62;"></b></p><b style="color:#fc8d62;">
</b></section><b style="color:#fc8d62;">
</b><section id="coordenadas-de-las-ambientales-coord.amb" class="level4"><b style="color:#fc8d62;">
<h4 class="anchored" data-anchor-id="coordenadas-de-las-ambientales-coord.amb">12.3 Coordenadas de las ambientales “coord.amb”</h4>
</b><p><b style="color:#fc8d62;"></b></p>
<div class="cell">
<details>
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 3) Coordenadasde las especies (coord.tax) </span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>amb1 <span class="ot">&lt;-</span> <span class="fu">envfit</span>(tax.rda, amb2[,<span class="sc">-</span><span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>)]) <span class="co"># Se pueden seleccionar variables con, p.max = 0.05</span></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>coord.amb <span class="ot">=</span> <span class="fu">as.data.frame</span>(<span class="fu">summary</span>(rda.pars)<span class="sc">$</span><span class="st">"biplot"</span>[,<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>])</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>coord.amb<span class="sc">$</span>amb <span class="ot">&lt;-</span> <span class="fu">rownames</span>(coord.amb)         <span class="co"># Insertar columna con nombres de las ambientales</span></span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>coord.amb <span class="ot">=</span> coord.amb <span class="co"># La 3 variables seleccionadas</span></span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(coord.amb) </span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>              RDA1        RDA2     amb
pH      -0.1643328  0.66097941      pH
OD      -0.6672741  0.56968533      OD
Conduct  0.5435740  0.36341066 Conduct
TDS      0.2837953  0.01677601     TDS
UPS      0.4663303 -0.18271086     UPS
Temp     0.4975694  0.31571654    Temp</code></pre>
</div>
</div>
<p><b style="color:#fc8d62;"></b></p><b style="color:#fc8d62;">
</b></section><b style="color:#fc8d62;">
</b><section id="figura-del-rda-con-vectores-de-especies" class="level4"><b style="color:#fc8d62;">
<h4 class="anchored" data-anchor-id="figura-del-rda-con-vectores-de-especies">12.4 Figura del RDA con vectores de especies</h4>
</b><p><b style="color:#fc8d62;"></b></p>
<div class="cell">
<details>
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Sitios</span></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text_repel</span>(<span class="at">data =</span> coord.sit,<span class="fu">aes</span>(RDA1,RDA2,<span class="at">label=</span><span class="fu">row.names</span>(coord.sit)),</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>                  <span class="at">size=</span><span class="dv">3</span>)<span class="sc">+</span>   <span class="co"># Muestra el cuadro de la figura</span></span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> coord.sit,<span class="fu">aes</span>(RDA1,RDA2,<span class="at">colour=</span>grp),<span class="at">size=</span><span class="dv">4</span>)<span class="sc">+</span></span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_shape_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="dv">21</span><span class="sc">:</span><span class="dv">25</span>))<span class="sc">+</span></span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Taxones  </span></span>
<span id="cb40-8"><a href="#cb40-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_segment</span>(<span class="at">data =</span> coord.tax,<span class="fu">aes</span>(<span class="at">x =</span> <span class="dv">0</span>, <span class="at">y =</span> <span class="dv">0</span>, <span class="at">xend =</span> RDA1<span class="sc">*</span><span class="dv">2</span>, <span class="at">yend =</span> RDA2<span class="sc">*</span><span class="dv">2</span>), </span>
<span id="cb40-9"><a href="#cb40-9" aria-hidden="true" tabindex="-1"></a>               <span class="at">arrow =</span> <span class="fu">arrow</span>(<span class="at">angle=</span><span class="fl">22.5</span>,<span class="at">length =</span> <span class="fu">unit</span>(<span class="fl">0.25</span>,<span class="st">"cm"</span>),</span>
<span id="cb40-10"><a href="#cb40-10" aria-hidden="true" tabindex="-1"></a>                             <span class="at">type =</span> <span class="st">"closed"</span>),<span class="at">linetype=</span><span class="dv">1</span>, <span class="at">size=</span><span class="fl">0.6</span>,<span class="at">colour =</span> <span class="st">"red"</span>)<span class="sc">+</span></span>
<span id="cb40-11"><a href="#cb40-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text_repel</span>(<span class="at">data =</span> coord.tax,<span class="fu">aes</span>(RDA1<span class="sc">*</span><span class="dv">2</span>,RDA2<span class="sc">*</span><span class="dv">2</span>,<span class="at">label=</span>especies),<span class="at">colour =</span> <span class="st">"red"</span>)<span class="sc">+</span></span>
<span id="cb40-12"><a href="#cb40-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-13"><a href="#cb40-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept=</span><span class="dv">0</span>,<span class="at">linetype=</span><span class="dv">3</span>,<span class="at">size=</span><span class="dv">1</span>) <span class="sc">+</span> </span>
<span id="cb40-14"><a href="#cb40-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept=</span><span class="dv">0</span>,<span class="at">linetype=</span><span class="dv">3</span>,<span class="at">size=</span><span class="dv">1</span>)<span class="sc">+</span></span>
<span id="cb40-15"><a href="#cb40-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">guides</span>(<span class="at">shape=</span><span class="fu">guide_legend</span>(<span class="at">title=</span><span class="cn">NULL</span>,<span class="at">color=</span><span class="st">"black"</span>),</span>
<span id="cb40-16"><a href="#cb40-16" aria-hidden="true" tabindex="-1"></a>         <span class="at">fill=</span><span class="fu">guide_legend</span>(<span class="at">title=</span><span class="cn">NULL</span>))<span class="sc">+</span></span>
<span id="cb40-17"><a href="#cb40-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()<span class="sc">+</span><span class="fu">theme</span>(<span class="at">panel.grid=</span><span class="fu">element_blank</span>())</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-figura3" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="multivar1.eng.peces_files/figure-html/fig-figura3-1.svg" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Figura&nbsp;8: Figuras del RDA con las variables biológicas y los sitios</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p><b style="color:#fc8d62;"></b></p><b style="color:#fc8d62;">
</b></section><b style="color:#fc8d62;">
</b><section id="figura-con-vectores-de-especies-y-ambientales" class="level4"><b style="color:#fc8d62;">
<h4 class="anchored" data-anchor-id="figura-con-vectores-de-especies-y-ambientales">12.6 Figura con vectores de especies y ambientales</h4>
</b><p><b style="color:#fc8d62;"></b></p>
<div class="cell">
<details>
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Factor </span></span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_mark_ellipse</span>(<span class="at">data=</span>coord.sit, <span class="fu">aes</span>(<span class="at">x=</span>RDA1,<span class="at">y=</span>RDA2,<span class="at">fill=</span>grp,<span class="at">group=</span>grp),<span class="at">alpha=</span><span class="fl">0.10</span>)  <span class="sc">+</span></span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Sitios</span></span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text_repel</span>(<span class="at">data =</span> coord.sit,<span class="fu">aes</span>(RDA1,RDA2,<span class="at">label=</span><span class="fu">row.names</span>(coord.sit)),</span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a>                  <span class="at">size=</span><span class="dv">3</span>)<span class="sc">+</span>   <span class="co"># Muestra el cuadro de la figura</span></span>
<span id="cb41-8"><a href="#cb41-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> coord.sit,<span class="fu">aes</span>(RDA1,RDA2,<span class="at">colour=</span>grp),<span class="at">size=</span><span class="dv">4</span>)<span class="sc">+</span></span>
<span id="cb41-9"><a href="#cb41-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_shape_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="dv">21</span><span class="sc">:</span><span class="dv">25</span>))<span class="sc">+</span></span>
<span id="cb41-10"><a href="#cb41-10" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb41-11"><a href="#cb41-11" aria-hidden="true" tabindex="-1"></a>  <span class="co"># especies  </span></span>
<span id="cb41-12"><a href="#cb41-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_segment</span>(<span class="at">data =</span> coord.tax,<span class="fu">aes</span>(<span class="at">x =</span> <span class="dv">0</span>, <span class="at">y =</span> <span class="dv">0</span>, <span class="at">xend =</span> RDA1, <span class="at">yend =</span> RDA2), </span>
<span id="cb41-13"><a href="#cb41-13" aria-hidden="true" tabindex="-1"></a>               <span class="at">arrow =</span> <span class="fu">arrow</span>(<span class="at">angle=</span><span class="dv">0</span>,<span class="at">length =</span> <span class="fu">unit</span>(<span class="dv">0</span>,<span class="st">"cm"</span>),</span>
<span id="cb41-14"><a href="#cb41-14" aria-hidden="true" tabindex="-1"></a>                             <span class="at">type =</span> <span class="st">"closed"</span>),<span class="at">linetype=</span><span class="dv">0</span>, <span class="at">size=</span><span class="dv">0</span>,<span class="at">colour =</span> <span class="st">"red"</span>)<span class="sc">+</span></span>
<span id="cb41-15"><a href="#cb41-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text_repel</span>(<span class="at">data =</span> coord.tax,<span class="fu">aes</span>(RDA1,RDA2,<span class="at">label=</span>especies),<span class="at">colour =</span> <span class="st">"red"</span>)<span class="sc">+</span></span>
<span id="cb41-16"><a href="#cb41-16" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Ambiental  </span></span>
<span id="cb41-17"><a href="#cb41-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_segment</span>(<span class="at">data =</span> coord.amb,<span class="fu">aes</span>(<span class="at">x =</span> <span class="dv">0</span>, <span class="at">y =</span> <span class="dv">0</span>, <span class="at">xend =</span> RDA1, <span class="at">yend =</span> RDA2), </span>
<span id="cb41-18"><a href="#cb41-18" aria-hidden="true" tabindex="-1"></a>               <span class="at">arrow =</span> <span class="fu">arrow</span>(<span class="at">angle=</span><span class="fl">22.5</span>,<span class="at">length =</span> <span class="fu">unit</span>(<span class="fl">0.25</span>,<span class="st">"cm"</span>),</span>
<span id="cb41-19"><a href="#cb41-19" aria-hidden="true" tabindex="-1"></a>                             <span class="at">type =</span> <span class="st">"closed"</span>),<span class="at">linetype=</span><span class="dv">1</span>, <span class="at">size=</span><span class="fl">0.6</span>,<span class="at">colour =</span> <span class="st">"blue"</span>)<span class="sc">+</span></span>
<span id="cb41-20"><a href="#cb41-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text_repel</span>(<span class="at">data =</span> coord.amb,<span class="fu">aes</span>(RDA1,RDA2,<span class="at">label=</span><span class="fu">row.names</span>(coord.amb)),<span class="at">colour =</span> <span class="st">"#00abff"</span>)<span class="sc">+</span></span>
<span id="cb41-21"><a href="#cb41-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-22"><a href="#cb41-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept=</span><span class="dv">0</span>,<span class="at">linetype=</span><span class="dv">3</span>,<span class="at">size=</span><span class="dv">1</span>) <span class="sc">+</span> </span>
<span id="cb41-23"><a href="#cb41-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept=</span><span class="dv">0</span>,<span class="at">linetype=</span><span class="dv">3</span>,<span class="at">size=</span><span class="dv">1</span>)<span class="sc">+</span></span>
<span id="cb41-24"><a href="#cb41-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">guides</span>(<span class="at">shape=</span><span class="fu">guide_legend</span>(<span class="at">title=</span><span class="cn">NULL</span>,<span class="at">color=</span><span class="st">"black"</span>),</span>
<span id="cb41-25"><a href="#cb41-25" aria-hidden="true" tabindex="-1"></a>         <span class="at">fill=</span><span class="fu">guide_legend</span>(<span class="at">title=</span><span class="cn">NULL</span>))<span class="sc">+</span></span>
<span id="cb41-26"><a href="#cb41-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()<span class="sc">+</span><span class="fu">theme</span>(<span class="at">panel.grid=</span><span class="fu">element_blank</span>())</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-figura5" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="multivar1.eng.peces_files/figure-html/fig-figura5-1.svg" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Figura&nbsp;9: Figuras del RDA con las variables biológicas, las ambientales y los sitios</figcaption><p></p>
</figure>
</div>
</div>
</div>
<hr>
</section>
</section>
</section>
<section id="bioenv" class="level2">
<h2 class="anchored" data-anchor-id="bioenv">4. Bioenv</h2>
<div class="cell">
<details>
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Igualar dimensiones de las matrices biológica y ambiental</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Base de datos amb</span></span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>amb1 <span class="ot">&lt;-</span> <span class="fu">read_xlsx</span>(<span class="st">"datos.eng3.xlsx"</span>, <span class="st">"env1"</span>)</span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Impresión de la base ambiental</span></span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a>amb1 <span class="ot">=</span><span class="fu">na.omit</span>(amb1)</span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Quito la fila Wax. gibb - Day, porque no está en los biológicos</span></span>
<span id="cb42-8"><a href="#cb42-8" aria-hidden="true" tabindex="-1"></a>amb2 <span class="ot">=</span> amb1[<span class="sc">-</span><span class="dv">20</span>,]   <span class="co"># Quitar fila</span></span>
<span id="cb42-9"><a href="#cb42-9" aria-hidden="true" tabindex="-1"></a>amb2 <span class="ot">=</span> amb2[<span class="sc">-</span><span class="fu">c</span>(<span class="dv">5</span>)]  <span class="co"># Quitar columna hour</span></span>
<span id="cb42-10"><a href="#cb42-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-11"><a href="#cb42-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Base biológica</span></span>
<span id="cb42-12"><a href="#cb42-12" aria-hidden="true" tabindex="-1"></a>biol1 <span class="ot">&lt;-</span> <span class="fu">read_xlsx</span>(<span class="st">"datos.eng3.xlsx"</span>, <span class="st">"Taxa1"</span>)</span>
<span id="cb42-13"><a href="#cb42-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Abreviar los nombres de las especies, sin abreviar Moom y Time.</span></span>
<span id="cb42-14"><a href="#cb42-14" aria-hidden="true" tabindex="-1"></a>biol <span class="ot">&lt;-</span> biol1[, <span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>, <span class="sc">-</span><span class="dv">2</span>)] <span class="sc">%&gt;%</span></span>
<span id="cb42-15"><a href="#cb42-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename_with</span>(<span class="sc">~</span> {</span>
<span id="cb42-16"><a href="#cb42-16" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Generar las abreviaturas y limitar a 4 caracteres</span></span>
<span id="cb42-17"><a href="#cb42-17" aria-hidden="true" tabindex="-1"></a>    abrev <span class="ot">&lt;-</span> <span class="fu">abbreviate</span>(., <span class="at">minlength =</span> <span class="dv">4</span>, <span class="at">use.classes =</span> <span class="cn">FALSE</span>)</span>
<span id="cb42-18"><a href="#cb42-18" aria-hidden="true" tabindex="-1"></a>    abrev <span class="ot">&lt;-</span> <span class="fu">substr</span>(abrev, <span class="dv">1</span>, <span class="dv">4</span>)  <span class="co"># Limitar a exactamente 4 caracteres</span></span>
<span id="cb42-19"><a href="#cb42-19" aria-hidden="true" tabindex="-1"></a>    <span class="fu">make.unique</span>(abrev)  <span class="co"># Asegurarse de que sean únicos</span></span>
<span id="cb42-20"><a href="#cb42-20" aria-hidden="true" tabindex="-1"></a>  })</span>
<span id="cb42-21"><a href="#cb42-21" aria-hidden="true" tabindex="-1"></a><span class="co"># Dataframe definitivo abreviado</span></span>
<span id="cb42-22"><a href="#cb42-22" aria-hidden="true" tabindex="-1"></a>biol <span class="ot">&lt;-</span> </span>
<span id="cb42-23"><a href="#cb42-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">data.frame</span>(biol1[,<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>],biol)</span>
<span id="cb42-24"><a href="#cb42-24" aria-hidden="true" tabindex="-1"></a><span class="co"># Impresión de la base biológica</span></span>
<span id="cb42-25"><a href="#cb42-25" aria-hidden="true" tabindex="-1"></a><span class="co"># Quito la fila Wax.cres - Night, porque no está en las ambientales</span></span>
<span id="cb42-26"><a href="#cb42-26" aria-hidden="true" tabindex="-1"></a>biol2 <span class="ot">=</span> biol[<span class="sc">-</span><span class="dv">18</span>,] </span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>TDS y UPS son las que mejor se correlacionan con la diversidad de peces</p>
<div class="cell">
<details>
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>bioenv <span class="ot">&lt;-</span> <span class="fu">bioenv</span>(biol2[,<span class="sc">-</span><span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>)] <span class="sc">~</span> pH <span class="sc">+</span> OD <span class="sc">+</span> Conduct <span class="sc">+</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>                TDS <span class="sc">+</span> UPS <span class="sc">+</span> Temp, amb2)</span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>bioenv</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
bioenv(formula = biol2[, -c(1:4)] ~ pH + OD + Conduct + TDS +      UPS + Temp, data = amb2) 

Subset of environmental variables with best correlation to community data.

Correlations:    spearman 
Dissimilarities: bray 
Metric:          euclidean 

Best model has 2 parameters (max. 6 allowed):
TDS UPS
with correlation  0.1847841 </code></pre>
</div>
<details>
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="do">## IGNORE_RDIFF_BEGIN</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(bioenv)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>                           size correlation
UPS                           1      0.1616
TDS UPS                       2      0.1848
Conduct TDS UPS               3      0.1632
OD Conduct TDS UPS            4      0.1479
pH OD Conduct TDS UPS         5      0.0821
pH OD Conduct TDS UPS Temp    6     -0.0019</code></pre>
</div>
</div>
<hr>
<p><b style="color:#fc8d62;"></b></p><b style="color:#fc8d62;">
</b></section><b style="color:#fc8d62;">
</b><section id="análisis-de-clúster-cla" class="level2"><b style="color:#fc8d62;">
<h2 class="anchored" data-anchor-id="análisis-de-clúster-cla">5. Análisis de Clúster (CLA)</h2>
</b><p><b style="color:#fc8d62;"></b></p>
<p>Este análisis fue solicitado por los evaluadores, basado en la Abundance de los trece Species taxonómicos, se pretende clasificar a las localidades en Species y compararlos con las Moon del estudio.</p>
<p><b style="color:#1f78b4;"></b></p><b style="color:#1f78b4;">
</b><section id="cargar-librerías" class="level3"><b style="color:#1f78b4;">
<h3 class="anchored" data-anchor-id="cargar-librerías">Cargar Librerías</h3>
</b><p><b style="color:#1f78b4;"></b></p>
<p>Se cargan las librerías requeridas para el análisis.</p>
<div class="cell">

</div>
<p><b style="color:#fc8d62;"></b></p><b style="color:#fc8d62;">
</b></section><b style="color:#fc8d62;">
</b><section id="paso-1.-distancia-entre-observaciones" class="level3"><b style="color:#fc8d62;">
<h3 class="anchored" data-anchor-id="paso-1.-distancia-entre-observaciones">Paso 1. Distancia entre observaciones</h3>
</b><p><b style="color:#fc8d62;"></b></p>
<p>Se aplicará la distancia Bray Curtis para las variables biológicas, dada la poca linealidad en sus relaciones.</p>
<div class="cell">

</div>
<p><b style="color:#fc8d62;"></b></p><b style="color:#fc8d62;">
</b></section><b style="color:#fc8d62;">
</b><section id="paso-2.-elección-del-método-de-agrupación-de-mayor-ajuste" class="level3"><b style="color:#fc8d62;">
<h3 class="anchored" data-anchor-id="paso-2.-elección-del-método-de-agrupación-de-mayor-ajuste">Paso 2. Elección del método de agrupación de mayor ajuste</h3>
</b><p><b style="color:#fc8d62;"></b></p>
<section id="cálculo-de-los-siete-dendogramas" class="level4">
<h4 class="anchored" data-anchor-id="cálculo-de-los-siete-dendogramas">2.1 Cálculo de los siete dendogramas</h4>
<div class="cell">

</div>
</section>
<section id="cálculo-de-las-correlaciones-cofenéticas" class="level4">
<h4 class="anchored" data-anchor-id="cálculo-de-las-correlaciones-cofenéticas">2.2 Cálculo de las correlaciones cofenéticas</h4>
<div class="cell">

</div>
<p>El método de <strong>agrupación UPGMA</strong> es el que presentó el mejor ajuste cofenético.</p>
<div class="cell">
<div class="cell-output-display">

<table class=" lightable-classic" style="font-family: Cambria; width: auto !important; margin-left: auto; margin-right: auto;">
<caption></caption>
 <thead>
  <tr>
   <th style="text-align:left;">   </th>
   <th style="text-align:right;"> Met </th>
   <th style="text-align:right;"> Cofen </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> upgma </td>
   <td style="text-align:right;"> 3 </td>
   <td style="text-align:right;"> 0.833 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> upgmc </td>
   <td style="text-align:right;"> 4 </td>
   <td style="text-align:right;"> 0.828 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> simple </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 0.813 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> wpgma </td>
   <td style="text-align:right;"> 5 </td>
   <td style="text-align:right;"> 0.798 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> compl </td>
   <td style="text-align:right;"> 2 </td>
   <td style="text-align:right;"> 0.745 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> wpgmc </td>
   <td style="text-align:right;"> 6 </td>
   <td style="text-align:right;"> 0.721 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ward </td>
   <td style="text-align:right;"> 7 </td>
   <td style="text-align:right;"> 0.475 </td>
  </tr>
</tbody>
</table>

</div>
</div>
<p><b style="color:#fc8d62;"></b></p><b style="color:#fc8d62;">
</b></section><b style="color:#fc8d62;">
</b></section><b style="color:#fc8d62;">
</b><section id="paso-3.-número-de-species-formados" class="level3"><b style="color:#fc8d62;">
<h3 class="anchored" data-anchor-id="paso-3.-número-de-species-formados">Paso 3. Número de Species formados</h3>
</b><p><b style="color:#fc8d62;"></b></p>
<section id="método-de-silueta" class="level4">
<h4 class="anchored" data-anchor-id="método-de-silueta">3.1 Método de silueta</h4>
<div class="cell">

</div>
<p>Esta ténica muestra que la mayor amplitud se presenta en la formación de <strong>diez Species</strong> o clúester, que reunen a las observaciones clasificadas.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<p><img src="multivar1.eng.peces_files/figure-html/unnamed-chunk-55-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code> Silueta-Número óptimo de Clusters k= 2 
 Con una aplitud promedio de silueta 0.2901447 </code></pre>
</div>
</div>
</section>
<section id="dendograma-jerárquico-final" class="level4">
<h4 class="anchored" data-anchor-id="dendograma-jerárquico-final">3.3 Dendograma jerárquico final</h4>
<p>Dendograma generado con el método upgma, la distancia Bray y los tres Species formados.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="multivar1.eng.peces_files/figure-html/unnamed-chunk-57-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="dendograma-no-jerárquico-final" class="level4">
<h4 class="anchored" data-anchor-id="dendograma-no-jerárquico-final">3.4 Dendograma no jerárquico final</h4>
<div class="cell">

</div>
<div class="cell">
<div class="cell-output-display">

<table class=" lightable-classic" style="font-family: Cambria; width: auto !important; margin-left: auto; margin-right: auto;">
<caption></caption>
 <thead>
  <tr>
   <th style="text-align:left;">   </th>
   <th style="text-align:right;"> grp </th>
   <th style="text-align:right;"> Achl </th>
   <th style="text-align:right;"> Ancc </th>
   <th style="text-align:right;"> Aris </th>
   <th style="text-align:right;"> Barr </th>
   <th style="text-align:right;"> Bats </th>
   <th style="text-align:right;"> Carc </th>
   <th style="text-align:right;"> Carh </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> Wanc.D1 </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 0.5222330 </td>
   <td style="text-align:right;"> 0.0000000 </td>
   <td style="text-align:right;"> 0.4264014 </td>
   <td style="text-align:right;"> 0.0000000 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0.0000000 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Wanc.D2 </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 0.0000000 </td>
   <td style="text-align:right;"> 0.2294157 </td>
   <td style="text-align:right;"> 0.3244428 </td>
   <td style="text-align:right;"> 0.0000000 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0.2294157 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Wanc.D3 </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 0.3216338 </td>
   <td style="text-align:right;"> 0.2626129 </td>
   <td style="text-align:right;"> 0.4548588 </td>
   <td style="text-align:right;"> 0.0000000 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0.0000000 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Wanc.N1 </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 0.2294157 </td>
   <td style="text-align:right;"> 0.0000000 </td>
   <td style="text-align:right;"> 0.4188539 </td>
   <td style="text-align:right;"> 0.1873172 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0.0000000 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Wanc.N2 </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 0.1170411 </td>
   <td style="text-align:right;"> 0.1655212 </td>
   <td style="text-align:right;"> 0.3310424 </td>
   <td style="text-align:right;"> 0.2617120 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0.0000000 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Wanc.N3 </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 0.1507557 </td>
   <td style="text-align:right;"> 0.3370999 </td>
   <td style="text-align:right;"> 0.5000000 </td>
   <td style="text-align:right;"> 0.1507557 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0.0000000 </td>
  </tr>
</tbody>
</table>

</div>
</div>
<div class="cell">
<div class="cell-output-display">
<p><img src="multivar1.eng.peces_files/figure-html/unnamed-chunk-60-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><b style="color:#fc8d62;"></b></p><b style="color:#fc8d62;">
</b></section><b style="color:#fc8d62;">
</b></section><b style="color:#fc8d62;">
</b><section id="paso-4.-aporte-de-las-variables-a-la-clasificación" class="level3"><b style="color:#fc8d62;">
<h3 class="anchored" data-anchor-id="paso-4.-aporte-de-las-variables-a-la-clasificación">Paso 4. Aporte de las variables a la clasificación</h3>
</b><p><b style="color:#fc8d62;"></b></p>
<p>En rojo se identifica a los Species taxonómicos que por su patrón de Abundance, aportan a la clasificación de los sitios.</p>
<div class="cell">

</div>
<div class="cell">
<div class="cell-output-display">
<p><img src="multivar1.eng.peces_files/figure-html/unnamed-chunk-62-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">

</div>
<div class="cell">

</div>
<div class="cell">

</div>
<p>Para este caso, el aporte de los taxones se da para las Moon.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="multivar1.eng.peces_files/figure-html/unnamed-chunk-66-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<hr>
<p><b style="color:#1f78b4;"></b></p><b style="color:#1f78b4;">
</b></section><b style="color:#1f78b4;">
</b></section><b style="color:#1f78b4;">
</b><section id="análisis-discriminante-lineal-lda" class="level2"><b style="color:#1f78b4;">
<h2 class="anchored" data-anchor-id="análisis-discriminante-lineal-lda">6. Análisis Discriminante Lineal (LDA)</h2>
</b><p><b style="color:#1f78b4;"></b></p>
<p>Este análisis se realiza para intentar optimizar la separación de las Moon, por la información de las Abundances de los diferentes Species taxonómicos. Se incorpora a la variante de discriminante canónico, para analizar el aporte de los taxones en la clasificación.</p>
<p><b style="color:#1f78b4;"></b></p><b style="color:#1f78b4;">
</b><section id="cargar-librerías-1" class="level3"><b style="color:#1f78b4;">
<h3 class="anchored" data-anchor-id="cargar-librerías-1">Cargar Librerías</h3>
</b><p><b style="color:#1f78b4;"></b></p>
<p>Se cargan diferentes librerías requeridas para el lda.</p>
<div class="cell">

</div>
<p>La <strong>?@tbl-tbl6</strong>, es la misma <strong>?@tbl-tbl6</strong> utilizada para la mayoría de los análisis anteriores.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-tbl7" class="anchored">

<table class=" lightable-classic" style="font-family: Cambria; width: auto !important; margin-left: auto; margin-right: auto;">
<caption>Tabla&nbsp;2:  Base de datos con taxones abreviados y referencias de los sitios </caption>
 <thead>
  <tr>
   <th style="text-align:left;"> Cod </th>
   <th style="text-align:left;"> Moon </th>
   <th style="text-align:left;"> Time </th>
   <th style="text-align:right;"> Zone </th>
   <th style="text-align:right;"> Achl </th>
   <th style="text-align:right;"> Ancc </th>
   <th style="text-align:right;"> Aris </th>
   <th style="text-align:right;"> Barr </th>
   <th style="text-align:right;"> Bats </th>
   <th style="text-align:right;"> Carc </th>
   <th style="text-align:right;"> Carh </th>
   <th style="text-align:right;"> Carl </th>
   <th style="text-align:right;"> Catm </th>
   <th style="text-align:right;"> Cene </th>
   <th style="text-align:right;"> Cenp </th>
   <th style="text-align:right;"> Cenu </th>
   <th style="text-align:right;"> Cete </th>
   <th style="text-align:right;"> Chaf </th>
   <th style="text-align:right;"> Cits </th>
   <th style="text-align:right;"> Dasg </th>
   <th style="text-align:right;"> Diar </th>
   <th style="text-align:right;"> Epii </th>
   <th style="text-align:right;"> Eugp </th>
   <th style="text-align:right;"> Gerc </th>
   <th style="text-align:right;"> Gobd </th>
   <th style="text-align:right;"> Gymo </th>
   <th style="text-align:right;"> Luta </th>
   <th style="text-align:right;"> Lutj </th>
   <th style="text-align:right;"> Lycg </th>
   <th style="text-align:right;"> Mega </th>
   <th style="text-align:right;"> Mena </th>
   <th style="text-align:right;"> Mugi </th>
   <th style="text-align:right;"> Olig </th>
   <th style="text-align:right;"> Olig.1 </th>
   <th style="text-align:right;"> Selv </th>
   <th style="text-align:right;"> Spht </th>
   <th style="text-align:right;"> Stes </th>
   <th style="text-align:right;"> Strt </th>
   <th style="text-align:right;"> Tril </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> Wanc.D1 </td>
   <td style="text-align:left;"> Wan.cres </td>
   <td style="text-align:left;"> Day </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 3 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 2 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 2 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 2 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Wanc.D2 </td>
   <td style="text-align:left;"> Wan.cres </td>
   <td style="text-align:left;"> Day </td>
   <td style="text-align:right;"> 2 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 2 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 5 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 3 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 2 </td>
   <td style="text-align:right;"> 2 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Wanc.D3 </td>
   <td style="text-align:left;"> Wan.cres </td>
   <td style="text-align:left;"> Day </td>
   <td style="text-align:right;"> 3 </td>
   <td style="text-align:right;"> 3 </td>
   <td style="text-align:right;"> 2 </td>
   <td style="text-align:right;"> 6 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 8 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 3 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 2 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Wanc.N1 </td>
   <td style="text-align:left;"> Wan.cres </td>
   <td style="text-align:left;"> Night </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 3 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 10 </td>
   <td style="text-align:right;"> 2 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 5 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 3 </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 20 </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 5 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 4 </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 2 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Wanc.N2 </td>
   <td style="text-align:left;"> Wan.cres </td>
   <td style="text-align:left;"> Night </td>
   <td style="text-align:right;"> 2 </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 2 </td>
   <td style="text-align:right;"> 8 </td>
   <td style="text-align:right;"> 5 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 5 </td>
   <td style="text-align:right;"> 7 </td>
   <td style="text-align:right;"> 3 </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 19 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 4 </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 4 </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 6 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 2 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Wanc.N3 </td>
   <td style="text-align:left;"> Wan.cres </td>
   <td style="text-align:left;"> Night </td>
   <td style="text-align:right;"> 3 </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 5 </td>
   <td style="text-align:right;"> 11 </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 3 </td>
   <td style="text-align:right;"> 2 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 12 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 2 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 4 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 1 </td>
  </tr>
</tbody>
</table>

</div>
</div>
</div>
<p>Se vuelve a mostrar la resolución de los taxones y de las variables ambientales para clasificar a las Moon o sitios de muestreo.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="multivar1.eng.peces_files/figure-html/unnamed-chunk-69-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<details>
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Base de datos amb</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>amb1 <span class="ot">&lt;-</span> <span class="fu">read_xlsx</span>(<span class="st">"datos.eng3.xlsx"</span>, <span class="st">"env1"</span>)</span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Impresión de la base ambiental</span></span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a>amb1 <span class="ot">=</span><span class="fu">na.omit</span>(amb1)</span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Quito la fila Wax. gibb - Day, porque no está en los biológicos</span></span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a>amb2 <span class="ot">=</span> amb1[<span class="sc">-</span><span class="dv">20</span>,]   <span class="co"># Quitar fila</span></span>
<span id="cb49-8"><a href="#cb49-8" aria-hidden="true" tabindex="-1"></a>amb2 <span class="ot">=</span> amb2[<span class="sc">-</span><span class="fu">c</span>(<span class="dv">5</span>)]  <span class="co"># Quitar columna hour</span></span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell">
<div class="cell-output-display">
<p><img src="multivar1.eng.peces_files/figure-html/unnamed-chunk-71-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><b style="color:#fc8d62;"></b></p><b style="color:#fc8d62;">
</b></section><b style="color:#fc8d62;">
</b><section id="paso-1.-selección-de-una-muestra-aleatoria-para-el-lda" class="level3"><b style="color:#fc8d62;">
<h3 class="anchored" data-anchor-id="paso-1.-selección-de-una-muestra-aleatoria-para-el-lda">Paso 1. selección de una muestra aleatoria para el lda</h3>
</b><p><b style="color:#fc8d62;"></b></p>
<p><strong>División de los datos en conjuntos de entrenamiento y prueba</strong>. Se recomienda estandarizar o normalizar las variables predictoras (Abundances de taxones) para que no haya un efecto de la escala. Algunos autores recomiendan dividir los datos de entrenamiento en un 60% y los datos de la prueba en 40% <a href="https://finnstats.com/2021/05/02/linear-discriminant-analysis/">FINNSTATS</a> o datos de entrenamiento en un 80% y los de prueba en un 20%. <a href="http://www.sthda.com/english/articles/36-classification-methods-essentials/146-discriminant-analysis-essentials-in-r/">STHDA</a>. Se utilizará la segunda propuesta para este ejercicio.</p>
<p><strong>1.&nbsp;División de los datos en conjuntos de entrenamiento y prueba</strong></p>
<p><strong>Nota</strong>: No se realizarà el lda con especies, porque las matrices son singulares y hay cilinealidad en algunas variables.</p>
<div class="cell">

</div>
<ol start="2" type="1">
<li><strong>Normalizar los datos. Las variables categóricas (Moon) se ignoran automáticamente.</strong></li>
</ol>
<div class="cell">

</div>
<p><b style="color:#1f78b4;"></b></p><b style="color:#1f78b4;">
</b></section><b style="color:#1f78b4;">
</b><section id="paso-2.-supuestos-de-normalidad-y-homogeneidad-de-covarianzas" class="level3"><b style="color:#1f78b4;">
<h3 class="anchored" data-anchor-id="paso-2.-supuestos-de-normalidad-y-homogeneidad-de-covarianzas">Paso 2. Supuestos de normalidad y homogeneidad de covarianzas</h3>
</b><p><b style="color:#1f78b4;"></b></p>
<p><b style="color:#fc8d62;"></b></p><b style="color:#fc8d62;">
</b><section id="supuesto-1.-normalidad-multivariada" class="level4"><b style="color:#fc8d62;">
<h4 class="anchored" data-anchor-id="supuesto-1.-normalidad-multivariada">Supuesto 1. Normalidad multivariada</h4>
</b><p><b style="color:#fc8d62;"></b></p>
<p>Este es uno de los requisitos que deben presentar los datos, para utilizar al lda como un modelo lineal. En caso de que no se cumpla este supuesto o no se pueda ejecutar, puede usarse el lda como un análisis exploratorio.</p>
<div class="cell">

</div>
<p>Se corrió el diagnóstico de normalidad multivariada para cada Moon, pero las muestras son matrices singulares, todas las matrices son singulares, impidiendo la ejecución del procedimiento.</p>
<div class="cell">

</div>
<p><b style="color:#fc8d62;"></b></p><b style="color:#fc8d62;">
</b></section><b style="color:#fc8d62;">
</b><section id="supuesto-2.-homogeneidad-de-covarianzas-esfericidad" class="level4"><b style="color:#fc8d62;">
<h4 class="anchored" data-anchor-id="supuesto-2.-homogeneidad-de-covarianzas-esfericidad">Supuesto 2. Homogeneidad de covarianzas (esfericidad)</h4>
</b><p><b style="color:#fc8d62;"></b></p>
<p>Se realizaron dos anovas permutacionales, las cuales permitieron demostrar que se cumple el supuesto de homogeneidad de covarianzas (valor p es mayor a 0.05).</p>
<div class="cell">

</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: Distances
          Df  Sum Sq Mean Sq F value Pr(&gt;F)
Groups     3  4.5893  1.5298  1.1406 0.3668
Residuals 14 18.7773  1.3412               </code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Permutation test for homogeneity of multivariate dispersions
Permutation: free
Number of permutations: 999

Response: Distances
          Df  Sum Sq Mean Sq      F N.Perm Pr(&gt;F)
Groups     3  4.5893  1.5298 1.1406    999  0.377
Residuals 14 18.7773  1.3412                     </code></pre>
</div>
</div>
<p><b style="color:#fc8d62;"></b></p><b style="color:#fc8d62;">
</b></section><b style="color:#fc8d62;">
</b></section><b style="color:#fc8d62;">
</b><section id="paso-3.-análisis-discriminante-lineal-de-fisher" class="level3"><b style="color:#fc8d62;">
<h3 class="anchored" data-anchor-id="paso-3.-análisis-discriminante-lineal-de-fisher">Paso 3. Análisis discriminante lineal de Fisher</h3>
</b><p><b style="color:#fc8d62;"></b></p>
<p>Se analizará el desempeño del modelo discriminante lineal, para clasificar a las seis Moon, basado en las Abundances de los Species taxonómicos.</p>
<div class="cell">

</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code> Wan.cres  Wan.gibb Wax. gibb  Wax.cres 
     0.28      0.28      0.22      0.22 </code></pre>
</div>
</div>
<p>La función de desempeño, genera la siguiente tabla de contingencia, en la que a excepción de la Moon 2 (la más diferente), muestra una mezcla de observaciones que no permiten diferenciar claramente a la Moon, eso se da por la similitud en la composición y Abundance de los Species taxonómicos entre Moon.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>           group
Moon        Wan.cres Wan.gibb Wax. gibb Wax.cres
  Wan.cres         5        0         0        0
  Wan.gibb         0        5         0        0
  Wax. gibb        0        1         3        0
  Wax.cres         0        0         1        3</code></pre>
</div>
</div>
<p>El siguiente resultado muestra el porcentaje de acierto en la clasificación de las Moon, el cual es bajo en la mayoría de los casos.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code> Wan.cres  Wan.gibb Wax. gibb  Wax.cres 
      100       100        75        75 </code></pre>
</div>
</div>
<p><b style="color:#fc8d62;"></b></p><b style="color:#fc8d62;">
</b></section><b style="color:#fc8d62;">
</b><section id="paso-4.-visualización-grafica-del-lda" class="level3"><b style="color:#fc8d62;">
<h3 class="anchored" data-anchor-id="paso-4.-visualización-grafica-del-lda">Paso 4. Visualización grafica del LDA</h3>
</b><p><b style="color:#fc8d62;"></b></p>
<p>Se utilizará el paquete ggplot2 como se ha venido empleando en las diferentes técnicas, debido a su buen nivel de resolución para visualizar patrones en los datos.</p>
<div class="cell">

</div>
<div class="cell">

</div>
<p>La siguiente figura corrobora la separación de la Moon 2, debido a su diferencia en la composición y Abundance de taxones encontrados. El resto de localidades presentan una mezcla o mayor similitud taxonómica.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="multivar1.eng.peces_files/figure-html/unnamed-chunk-85-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">

</div>
<div class="cell">

</div>
<div class="cell">

</div>
<p>El siguiente <strong>análisis discriminante canónico</strong>, permite demostrar que la diferencia de la Moon 2, se debe a la composición y Abundance de taxones como <strong>Srgs, Lcfr, Lrdp y Hvdp</strong>.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="multivar1.eng.peces_files/figure-html/unnamed-chunk-89-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<hr>
<p><b style="color:#1f78b4;"></b></p><b style="color:#1f78b4;">
</b></section><b style="color:#1f78b4;">
</b></section><b style="color:#1f78b4;">
</b><section id="manovas---species-taxonómicos-de-biol2" class="level2"><b style="color:#1f78b4;">
<h2 class="anchored" data-anchor-id="manovas---species-taxonómicos-de-biol2">7. Manovas - Species Taxonómicos de biol2</h2>
</b><p><b style="color:#1f78b4;"></b></p>
<p>El siguiente manova se emplea para probar la hipótesis de diferencias entre las Moon, de acuerdo a la Abundance y composición de los Species taxonómicos. Como es un modelo lineal paramétrico, se deben probar los supuestos paramétricos encontrando que no se cumple la normalidad multivariada de los residuales, por lo cual, posteriormente se realizaran permanovas que no requieren este supuesto.</p>
<p><b style="color:#fc8d62;"></b></p><b style="color:#fc8d62;">
</b><section id="paso-1.-análisis-de-varinaza-multivariado---manova" class="level3"><b style="color:#fc8d62;">
<h3 class="anchored" data-anchor-id="paso-1.-análisis-de-varinaza-multivariado---manova">Paso 1. Análisis de Varinaza Multivariado - MANOVA</h3>
</b><p><b style="color:#fc8d62;"></b></p>
<section id="respuesta-de-cada-variable-a-las-diferencias-entre-moon" class="level4">
<h4 class="anchored" data-anchor-id="respuesta-de-cada-variable-a-las-diferencias-entre-moon">1.1 Respuesta de cada variable a las diferencias entre Moon</h4>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code> [1] "Cod"     "Moon"    "Time"    "Zone"    "pH"      "X.OD"    "OD"     
 [8] "Conduct" "TDS"     "UPS"     "Temp"   </code></pre>
</div>
</div>
<p>solo la temperatura y TDS marcan diferencias para Moon (valor p &lt; 0,05)</p>
<div class="cell">
<div class="cell-output-display">

<table class=" lightable-classic" style="font-family: Cambria; width: auto !important; margin-left: auto; margin-right: auto;">
<caption></caption>
 <thead>
  <tr>
   <th style="text-align:left;"> Variable </th>
   <th style="text-align:right;"> p.Moon </th>
   <th style="text-align:right;"> p.Time </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> pH </td>
   <td style="text-align:right;"> 0.4574 </td>
   <td style="text-align:right;"> 0.3792 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> X.OD </td>
   <td style="text-align:right;"> 0.0309 </td>
   <td style="text-align:right;"> 0.0387 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> OD </td>
   <td style="text-align:right;"> 0.2254 </td>
   <td style="text-align:right;"> 0.1485 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Conduct </td>
   <td style="text-align:right;"> 0.0492 </td>
   <td style="text-align:right;"> 0.4676 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> TDS </td>
   <td style="text-align:right;"> 0.0435 </td>
   <td style="text-align:right;"> 0.8868 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> UPS </td>
   <td style="text-align:right;"> 0.0456 </td>
   <td style="text-align:right;"> 0.6437 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Temp </td>
   <td style="text-align:right;"> 0.0008 </td>
   <td style="text-align:right;"> 0.0772 </td>
  </tr>
</tbody>
</table>

</div>
</div>
</section>
<section id="cuatro-tipos-de-manova" class="level4">
<h4 class="anchored" data-anchor-id="cuatro-tipos-de-manova">1.2 Cuatro tipos de MANOVA</h4>
<p>Solo el test de Roy muestra diferencias significativas en la Abundancia y composición para Moon (valor p &lt; 0.05)</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>          Df  Pillai approx F num Df den Df  Pr(&gt;F)  
Moon       3 1.82392   1.9940     21     27 0.04604 *
Time       1 0.70028   2.3364      7      7 0.14269  
Residuals 13                                         
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>          Df    Wilks approx F num Df den Df  Pr(&gt;F)  
Moon       3 0.036827   2.1215     21  20.65 0.04711 *
Time       1 0.299722   2.3364      7   7.00 0.14269  
Residuals 13                                          
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>          Df Hotelling-Lawley approx F num Df den Df  Pr(&gt;F)  
Moon       3           7.3829   1.9922     21     17 0.07677 .
Time       1           2.3364   2.3364      7      7 0.14269  
Residuals 13                                                  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>          Df    Roy approx F num Df den Df   Pr(&gt;F)   
Moon       3 4.4009   5.6582      7      9 0.009738 **
Time       1 2.3364   2.3364      7      7 0.142686   
Residuals 13                                          
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
</section>
<section id="supuesto-de-normalidad-de-los-residuales-del-manova" class="level4">
<h4 class="anchored" data-anchor-id="supuesto-de-normalidad-de-los-residuales-del-manova">1.3. Supuesto de normalidad de los residuales del MANOVA</h4>
<p>No se cumple el supuesto de normalidad multivariada sobre los residuales del Manova (W = 0.65, p-value = 2.8e-06). En este sentido, el MANOVA no puede ser utilizado para probar diferencias entre la Moon.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  Z
W = 0.68385, p-value = 5.213e-05</code></pre>
</div>
</div>
<div class="cell">

</div>
<div class="cell">

</div>
<div class="cell">
<div class="cell-output-display">
<p><img src="multivar1.eng.peces_files/figure-html/unnamed-chunk-96-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="supuesto-de-independencia" class="level4">
<h4 class="anchored" data-anchor-id="supuesto-de-independencia">1.4. Supuesto de independencia</h4>
<p>Se cumple este supuesto (valor p &gt; 0.05).</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code> lag Autocorrelation D-W Statistic p-value
   1      -0.4218554      2.660431   0.324
 Alternative hypothesis: rho != 0</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code> lag Autocorrelation D-W Statistic p-value
   1       0.1017075      1.715878   0.474
 Alternative hypothesis: rho != 0</code></pre>
</div>
</div>
<hr>
<p><b style="color:#fc8d62;"></b></p><b style="color:#fc8d62;">
</b></section><b style="color:#fc8d62;">
</b></section><b style="color:#fc8d62;">
</b><section id="permanova---ambientales.-permanova-de-dos-factores-a-2-vías" class="level3"><b style="color:#fc8d62;">
<h3 class="anchored" data-anchor-id="permanova---ambientales.-permanova-de-dos-factores-a-2-vías">Permanova - Ambientales. Permanova de dos factores (a 2 vías)</h3>
</b><p><b style="color:#fc8d62;"></b></p>
<p>De acuerdo a la teoría, esta prueba suele ser más robsta que el anosim, para encontrar diferencias entre los Species en comparación.</p>
<p><b style="color:#66c2a5;"></b></p><b style="color:#66c2a5;">
</b><section id="paso-1.-disancia-entre-observaciones-hellinger-para-este-caso" class="level4"><b style="color:#66c2a5;">
<h4 class="anchored" data-anchor-id="paso-1.-disancia-entre-observaciones-hellinger-para-este-caso">Paso 1. Disancia entre observaciones (Hellinger para este caso)</h4>
</b><p><b style="color:#66c2a5;"></b></p>
<p>Distancia Bray para ambientales</p>
<div class="cell">

</div>
<p><b style="color:#66c2a5;"></b></p><b style="color:#66c2a5;">
</b></section><b style="color:#66c2a5;">
</b><section id="paso-2.-prueba-de-hipótesis-de-igualdad-de-medias-multivariadas" class="level4"><b style="color:#66c2a5;">
<h4 class="anchored" data-anchor-id="paso-2.-prueba-de-hipótesis-de-igualdad-de-medias-multivariadas">Paso 2. Prueba de hipótesis de igualdad de medias multivariadas</h4>
</b><p><b style="color:#66c2a5;"></b></p>
<p>Se presentan diferencias entre las Moon similar al anosim (Seudo F= 2.73; g.l.= 5, 18; p= 0.012).</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Permutation test for adonis under reduced model
Permutation: free
Number of permutations: 1000

adonis2(formula = d.amb ~ amb2$Moon + amb2$Time, permutations = 1000)
         Df SumOfSqs      R2      F  Pr(&gt;F)  
Model     4 0.023156 0.36979 2.4938 0.01199 *
Residual 17 0.039464 0.63021                 
Total    21 0.062620 1.00000                 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>No hay efectos de las variables.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Permutation: free
Number of permutations: 1000

Terms added sequentially (first to last)

          Df SumsOfSqs   MeanSqs F.Model      R2   Pr(&gt;F)    
pH         1  0.005158 0.0051576  189.09 0.08236 0.000999 ***
X.OD       1  0.013476 0.0134762  494.08 0.21520 0.000999 ***
OD         1  0.011578 0.0115780  424.48 0.18489 0.000999 ***
Conduct    1  0.023103 0.0231030  847.02 0.36894 0.000999 ***
TDS        1  0.006065 0.0060649  222.36 0.09685 0.000999 ***
UPS        1  0.002072 0.0020724   75.98 0.03309 0.000999 ***
Temp       1  0.000787 0.0007866   28.84 0.01256 0.000999 ***
Residuals 14  0.000382 0.0000273         0.00610             
Total     21  0.062620                   1.00000             
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<hr>
<p><b style="color:#fc8d62;"></b></p><b style="color:#fc8d62;">
</b></section><b style="color:#fc8d62;">
</b></section><b style="color:#fc8d62;">
</b><section id="permanova---biológicas.-permanova-de-dos-factores-a-2-vías" class="level3"><b style="color:#fc8d62;">
<h3 class="anchored" data-anchor-id="permanova---biológicas.-permanova-de-dos-factores-a-2-vías">Permanova - Biológicas. Permanova de dos factores (a 2 vías)</h3>
</b><p><b style="color:#fc8d62;"></b></p>
<p>De acuerdo a la teoría, esta prueba suele ser más robsta que el anosim, para encontrar diferencias entre los Species en comparación.</p>
<p><b style="color:#66c2a5;"></b></p><b style="color:#66c2a5;">
</b><section id="paso-1.-disancia-entre-observaciones-hellinger-para-este-caso-1" class="level4"><b style="color:#66c2a5;">
<h4 class="anchored" data-anchor-id="paso-1.-disancia-entre-observaciones-hellinger-para-este-caso-1">Paso 1. Disancia entre observaciones (Hellinger para este caso)</h4>
</b><p><b style="color:#66c2a5;"></b></p>
<p>Distancia Bray para ambientales</p>
<div class="cell">

</div>
<p><b style="color:#66c2a5;"></b></p><b style="color:#66c2a5;">
</b></section><b style="color:#66c2a5;">
</b><section id="paso-2.-prueba-de-hipótesis-de-igualdad-de-medias-multivariadas-1" class="level4"><b style="color:#66c2a5;">
<h4 class="anchored" data-anchor-id="paso-2.-prueba-de-hipótesis-de-igualdad-de-medias-multivariadas-1">Paso 2. Prueba de hipótesis de igualdad de medias multivariadas</h4>
</b><p><b style="color:#66c2a5;"></b></p>
<p>Se presentan diferencias entre las Moon similar al anosim (Seudo F= 2.73; g.l.= 5, 18; p= 0.012).</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Permutation test for adonis under reduced model
Permutation: free
Number of permutations: 1000

adonis2(formula = d.tax ~ amb2$Moon + amb2$Time, permutations = 1000)
         Df SumOfSqs      R2      F  Pr(&gt;F)  
Model     4   1.2578 0.29539 1.7817 0.01598 *
Residual 17   3.0003 0.70461                 
Total    21   4.2581 1.00000                 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>No uso todas las especies, para que genere un valor de p.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Permutation test for adonis under reduced model
Permutation: free
Number of permutations: 1000

adonis2(formula = d.tax ~ Achl + Ancc + Aris + Barr + Bats + Carc + Carh + Carl + Catm + Cene + Cenp + Cenu + Cete + Chaf + Cits + Dasg + Diar + Epii + Eugp + Gerc, permutations = 1000)
         Df SumOfSqs     R2      F  Pr(&gt;F)  
Model    18   3.9417 0.9257 2.0764 0.02597 *
Residual  3   0.3164 0.0743                 
Total    21   4.2581 1.0000                 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
</section>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copiado");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copiado");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>