<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Fase 4 – Manuscrito BST en el PNNT</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-a0f9fd0d421825b736dc1bbcbcba2219.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Manuscrito BST en el PNNT</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Resumen</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./fase3.html"> 
<span class="menu-text">Fase 3</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./fase4.html" aria-current="page"> 
<span class="menu-text">Fase 4</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#nota-sobre-el-análisis" id="toc-nota-sobre-el-análisis" class="nav-link active" data-scroll-target="#nota-sobre-el-análisis">Nota sobre el análisis</a></li>
  <li><a href="#propósito" id="toc-propósito" class="nav-link" data-scroll-target="#propósito">Propósito</a></li>
  <li><a href="#paquetes" id="toc-paquetes" class="nav-link" data-scroll-target="#paquetes">Paquetes</a></li>
  <li><a href="#lectura-limpieza-y-auditoría-de-diseño" id="toc-lectura-limpieza-y-auditoría-de-diseño" class="nav-link" data-scroll-target="#lectura-limpieza-y-auditoría-de-diseño">Lectura, limpieza y auditoría de diseño</a></li>
  <li><a href="#matrices-especie-unidad" id="toc-matrices-especie-unidad" class="nav-link" data-scroll-target="#matrices-especie-unidad">Matrices especie × unidad</a></li>
  <li><a href="#ivi-por-sitio" id="toc-ivi-por-sitio" class="nav-link" data-scroll-target="#ivi-por-sitio">IVI por Sitio</a></li>
  <li><a href="#abundancia-general-y-rad-distribución-rango-abundancia" id="toc-abundancia-general-y-rad-distribución-rango-abundancia" class="nav-link" data-scroll-target="#abundancia-general-y-rad-distribución-rango-abundancia">Abundancia general y RAD — distribución rango-abundancia</a></li>
  <li><a href="#números-de-hill-completitud-y-rarefacciónextrapolación-inext" id="toc-números-de-hill-completitud-y-rarefacciónextrapolación-inext" class="nav-link" data-scroll-target="#números-de-hill-completitud-y-rarefacciónextrapolación-inext">Números de Hill, completitud y rarefacción/extrapolación (iNEXT)</a></li>
  <li><a href="#partición-γ-α-β-con-inext.beta3d-estandarizada-por-cobertura" id="toc-partición-γ-α-β-con-inext.beta3d-estandarizada-por-cobertura" class="nav-link" data-scroll-target="#partición-γ-α-β-con-inext.beta3d-estandarizada-por-cobertura">Partición γ-α-β con <code>iNEXT.beta3D</code> (estandarizada por cobertura)</a></li>
  <li><a href="#partición-γ-α-β-de-números-de-hill-verificación-cruzada-jost-2007-chao-et-al.-2012" id="toc-partición-γ-α-β-de-números-de-hill-verificación-cruzada-jost-2007-chao-et-al.-2012" class="nav-link" data-scroll-target="#partición-γ-α-β-de-números-de-hill-verificación-cruzada-jost-2007-chao-et-al.-2012">Partición γ-α-β de números de Hill — verificación cruzada (Jost 2007 / Chao et al.&nbsp;2012)</a></li>
  <li><a href="#permanova-anidada-betadisper-y-simper" id="toc-permanova-anidada-betadisper-y-simper" class="nav-link" data-scroll-target="#permanova-anidada-betadisper-y-simper">PERMANOVA anidada, betadisper y SIMPER</a></li>
  <li><a href="#manyglm-binomial-negativa-principal-y-poisson-sensibilidad" id="toc-manyglm-binomial-negativa-principal-y-poisson-sensibilidad" class="nav-link" data-scroll-target="#manyglm-binomial-negativa-principal-y-poisson-sensibilidad">manyGLM — Binomial Negativa (principal) y Poisson (sensibilidad)</a></li>
  <li><a href="#síntesis-de-fase-4-y-decisiones-pendientes-antes-de-fase-5" id="toc-síntesis-de-fase-4-y-decisiones-pendientes-antes-de-fase-5" class="nav-link" data-scroll-target="#síntesis-de-fase-4-y-decisiones-pendientes-antes-de-fase-5">Síntesis de Fase 4 y decisiones pendientes antes de Fase 5</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Fase 4</h1>
<p class="subtitle lead">Diversidad taxonómica (TD) - Hill/iNEXT, partición γ-α-β, IVI/RAD, PERMANOVA anidada, SIMPER, betadisper y manyGLM</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Fig_portadas/fase4.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:90.0%" data-fig-pos="H"></p>
</figure>
</div>
</div>
</div>
<section id="nota-sobre-el-análisis" class="level2">
<h2 class="anchored" data-anchor-id="nota-sobre-el-análisis">Nota sobre el análisis</h2>
<p>Fase 4 es <strong>independiente de la Fase 3</strong> (grupos funcionales) — se calcula sobre el censo estructural completo (<code>Datos_estructura_PNNT.xlsx</code>, hoja <code>BSG</code>, 4070 individuos con DAP ≥ 10 cm) y no usa la matriz de rasgos ni los grupos a posteriori. Confirma lo anotado al cierre de Fase 3.</p>
</section>
<section id="propósito" class="level2">
<h2 class="anchored" data-anchor-id="propósito">Propósito</h2>
<p>Caracterizar la diversidad taxonómica del bosque seco del PNNT a lo largo del diseño espacial <strong>Sitio anidado en Franja</strong> (9 Sitios, 3 por Franja; 225 Subparcelas, 25 por Sitio), siguiendo el marco de números de Hill (Chao et al.), partición γ-α-β, IVI/RAD clásicos, y el bloque multivariado (PERMANOVA/SIMPER/betadisper/manyGLM) del proyecto BST adaptado a un diseño espacial (no temporal) con dos niveles de anidamiento.</p>
</section>
<section id="paquetes" class="level2">
<h2 class="anchored" data-anchor-id="paquetes">Paquetes</h2>
<p><strong>Nota sobre <code>iNEXT.beta3D</code>:</strong> no está en CRAN (se instala vía <code>devtools::install_github</code>, junto con sus dependencias <code>iNEXT.3D</code>, <code>phyclust</code> y <code>tidytree</code>) — igual que en <code>datos_Osorio_2026.qmd</code> y <code>7_div_tax.qmd</code>. El esquema visual de esta Fase 4 (barras de abundancia acumulada, RAD con etiquetas y paleta naranja-roja, y las curvas γ-α-β por cobertura) replica el usado en esos dos scripts de referencia del grupo (Anvidea cap. 7 / Osorio RBT).</p>
</section>
<section id="lectura-limpieza-y-auditoría-de-diseño" class="level2">
<h2 class="anchored" data-anchor-id="lectura-limpieza-y-auditoría-de-diseño">Lectura, limpieza y auditoría de diseño</h2>
<p><strong>Hallazgos de auditoría (no bloquean el análisis, se documentan):</strong></p>
<ul>
<li>73 nombres de especie únicos tras la limpieza; uno es <code>"Indeterminada"</code> (1 individuo, sin identificación) y se <strong>excluye</strong> de las matrices especie × unidad (decisión estándar: no aporta información taxonómica). <code>"Matayba sp."</code> (15 individuos, identificado a género) se <strong>conserva</strong> como morfoespecie válida → quedan <strong>72 unidades taxonómicas</strong>.</li>
<li>16 individuos (todos en el Sitio <code>QRD</code>) tenían DAP entre 9.55 y 9.87 cm, levemente bajo el umbral de inclusión de 10 cm del censo — coincide exactamente con los límites de clase diamétrica (9.55 ≈ CAP 30 cm/π; 9.87 ≈ CAP 31 cm/π), consistente con redondeo en el borde de clase y no con un error de captura. <strong>Decisión (confirmada, 12-sep-2026): se excluyen</strong> aplicando el corte estricto DAP ≥ 10.00 cm — verificado que el impacto es mínimo: ninguna especie desaparece de QRD (39 especies antes y después), solo baja de 421 a 405 individuos (−3.8 % en ese Sitio, −0.39 % del censo total), repartidos en 9 de las 25 Subparcelas, ninguna llega a cero individuos. No cambia riqueza, significancias, ni ninguna comparación entre Franjas reportada en este documento.</li>
<li>Diseño confirmado: <strong>9 Sitios (3 por cada una de las 3 Franjas), con 25 Subparcelas cada uno = 225 unidades</strong>, perfectamente balanceado → el anidamiento Sitio(Franja) es totalmente viable, con la Subparcela como unidad de réplica real para el bloque multivariado.</li>
</ul>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>     Franja
Sitio 750-850 850-950 950-1050
  BCC     481       0        0
  BCS       0     540        0
  CHG     438       0        0
  CMZ       0     413        0
  GQT       0       0      588
  GRC       0     363        0
  LEC       0       0      505
  PLC     321       0        0
  QRD       0       0      421</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 9 × 2
  Sitio     n
  &lt;fct&gt; &lt;int&gt;
1 BCC      25
2 BCS      25
3 CHG      25
4 CMZ      25
5 GQT      25
6 GRC      25
7 LEC      25
8 PLC      25
9 QRD      25</code></pre>
</div>
</div>
</section>
<section id="matrices-especie-unidad" class="level2">
<h2 class="anchored" data-anchor-id="matrices-especie-unidad">Matrices especie × unidad</h2>
</section>
<section id="ivi-por-sitio" class="level2">
<h2 class="anchored" data-anchor-id="ivi-por-sitio">IVI por Sitio</h2>
<p>Densidad relativa (nº individuos) + dominancia relativa (área basal) + frecuencia relativa (% de subparcelas con presencia de la especie dentro de su Sitio); escala 0–300 (convención clásica de Curtis &amp; McIntosh).</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Top 10 especies por IVI medio entre los 9 Sitios</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Especie</th>
<th style="text-align: right;">IVI_medio</th>
<th style="text-align: right;">n_sitios</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Brosimum alicastrum</td>
<td style="text-align: right;">42.46</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="even">
<td style="text-align: left;">Handroanthus billbergii</td>
<td style="text-align: right;">26.08</td>
<td style="text-align: right;">6</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Mimosa arenosa</td>
<td style="text-align: right;">22.15</td>
<td style="text-align: right;">6</td>
</tr>
<tr class="even">
<td style="text-align: left;">Pradosia colombiana</td>
<td style="text-align: right;">21.25</td>
<td style="text-align: right;">4</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Bursera simaruba</td>
<td style="text-align: right;">20.62</td>
<td style="text-align: right;">8</td>
</tr>
<tr class="even">
<td style="text-align: left;">Haematoxylum brasiletto</td>
<td style="text-align: right;">18.62</td>
<td style="text-align: right;">4</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Anacardium excelsum</td>
<td style="text-align: right;">18.47</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">Platymiscium pinnatum</td>
<td style="text-align: right;">17.16</td>
<td style="text-align: right;">9</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Pseudobombax septenatum</td>
<td style="text-align: right;">16.91</td>
<td style="text-align: right;">8</td>
</tr>
<tr class="even">
<td style="text-align: left;">Pterocarpus rohrii</td>
<td style="text-align: right;">16.72</td>
<td style="text-align: right;">7</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><code>Platymiscium pinnatum</code> es la única especie presente en los 9 Sitios; el IVI más alto lo tiene <code>Brosimum alicastrum</code> (42.5, pero solo en 3 Sitios, donde domina fuertemente), seguida de <code>Handroanthus billbergii</code> y <code>Mimosa arenosa</code> (más generalistas, presentes en 6 Sitios cada una).</p>
</section>
<section id="abundancia-general-y-rad-distribución-rango-abundancia" class="level2">
<h2 class="anchored" data-anchor-id="abundancia-general-y-rad-distribución-rango-abundancia">Abundancia general y RAD — distribución rango-abundancia</h2>
<p>Esquema visual replicado de <code>datos_Osorio_2026.qmd</code> (fig-1 y fig-c7-3): barras de abundancia acumulada para las especies dominantes, y curvas RAD con puntos etiquetados en escala log10, facetadas por unidad de comparación (allí Periodo L/S; aquí Franja).</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-abundancia-top20" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-abundancia-top20-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="fase4_files/figure-html/fig-abundancia-top20-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-abundancia-top20-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Especies más abundantes del censo estructural completo (barras de abundancia acumulada, estilo fig-1 de Osorio et al.)
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-rad-estilo-osorio" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-rad-estilo-osorio-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="fase4_files/figure-html/fig-rad-estilo-osorio-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-rad-estilo-osorio-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: RAD por Franja para las 20 especies dominantes del censo total (estilo fig-c7-3 de Osorio et al.)
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>750-850 -&gt; mejor modelo (AIC): Preemption  (AIC= 237.8 )</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>850-950 -&gt; mejor modelo (AIC): Lognormal  (AIC= 287.9 )
950-1050 -&gt; mejor modelo (AIC): Preemption  (AIC= 237.5 )</code></pre>
</div>
</div>
<p>Las dos franjas extremas del gradiente (750-850 y 950-1050) se ajustan mejor a un modelo de <strong>Preemption</strong> (dominancia fuerte y concentrada de pocas especies); la franja intermedia (850-950) se ajusta mejor a <strong>Log-normal</strong> (comunidad más equitativa, sin una especie que domine desproporcionadamente). Es un patrón a discutir con cautela — no necesariamente lineal a lo largo del gradiente hídrico.</p>
</section>
<section id="números-de-hill-completitud-y-rarefacciónextrapolación-inext" class="level2">
<h2 class="anchored" data-anchor-id="números-de-hill-completitud-y-rarefacciónextrapolación-inext">Números de Hill, completitud y rarefacción/extrapolación (iNEXT)</h2>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Completitud muestral (cobertura, SC) por Sitio</caption>
<colgroup>
<col style="width: 18%">
<col style="width: 6%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 6%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Assemblage</th>
<th style="text-align: right;">n</th>
<th style="text-align: right;">S.obs</th>
<th style="text-align: right;">SC</th>
<th style="text-align: right;">f1</th>
<th style="text-align: right;">f2</th>
<th style="text-align: right;">f3</th>
<th style="text-align: right;">f4</th>
<th style="text-align: right;">f5</th>
<th style="text-align: right;">f6</th>
<th style="text-align: right;">f7</th>
<th style="text-align: right;">f8</th>
<th style="text-align: right;">f9</th>
<th style="text-align: right;">f10</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">BCC</td>
<td style="text-align: right;">481</td>
<td style="text-align: right;">22</td>
<td style="text-align: right;">0.992</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">BCS</td>
<td style="text-align: right;">540</td>
<td style="text-align: right;">24</td>
<td style="text-align: right;">0.998</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">CHG</td>
<td style="text-align: right;">438</td>
<td style="text-align: right;">21</td>
<td style="text-align: right;">0.996</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">CMZ</td>
<td style="text-align: right;">413</td>
<td style="text-align: right;">35</td>
<td style="text-align: right;">0.976</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">GQT</td>
<td style="text-align: right;">588</td>
<td style="text-align: right;">26</td>
<td style="text-align: right;">0.998</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">GRC</td>
<td style="text-align: right;">362</td>
<td style="text-align: right;">36</td>
<td style="text-align: right;">0.978</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">LEC</td>
<td style="text-align: right;">505</td>
<td style="text-align: right;">27</td>
<td style="text-align: right;">0.982</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">PLC</td>
<td style="text-align: right;">321</td>
<td style="text-align: right;">27</td>
<td style="text-align: right;">0.972</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">QRD</td>
<td style="text-align: right;">405</td>
<td style="text-align: right;">39</td>
<td style="text-align: right;">0.983</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
<p>Rarefacción/extrapolación (q=0,1,2) por Franja</p>
</div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Completitud muestral (cobertura, SC) por Franja</caption>
<colgroup>
<col style="width: 18%">
<col style="width: 8%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 6%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Assemblage</th>
<th style="text-align: right;">n</th>
<th style="text-align: right;">S.obs</th>
<th style="text-align: right;">SC</th>
<th style="text-align: right;">f1</th>
<th style="text-align: right;">f2</th>
<th style="text-align: right;">f3</th>
<th style="text-align: right;">f4</th>
<th style="text-align: right;">f5</th>
<th style="text-align: right;">f6</th>
<th style="text-align: right;">f7</th>
<th style="text-align: right;">f8</th>
<th style="text-align: right;">f9</th>
<th style="text-align: right;">f10</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">750-850</td>
<td style="text-align: right;">1240</td>
<td style="text-align: right;">43</td>
<td style="text-align: right;">0.994</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">850-950</td>
<td style="text-align: right;">1315</td>
<td style="text-align: right;">57</td>
<td style="text-align: right;">0.995</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">950-1050</td>
<td style="text-align: right;">1498</td>
<td style="text-align: right;">53</td>
<td style="text-align: right;">0.993</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
<p>Rarefacción/extrapolación (q=0,1,2) por Franja</p>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="fase4_files/figure-html/inext-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Rarefacción/extrapolación (q=0,1,2) por Franja</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>Lectura:</strong> la cobertura de muestra es muy alta en todos los Sitios y Franjas (97.2–99.8 %) — el censo captura casi toda la diversidad detectable con este esfuerzo, y las comparaciones entre unidades son legítimas (no están sesgadas por diferencias de esfuerzo de muestreo). La Franja 750-850 tiene consistentemente menor diversidad en q=0,1,2 que las otras dos, con bandas de confianza que no se solapan con 850-950; las franjas 850-950 y 950-1050 son muy similares entre sí en los tres órdenes.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Estimadores asintóticos de diversidad (Hill q=0,1,2) por Franja</caption>
<colgroup>
<col style="width: 16%">
<col style="width: 27%">
<col style="width: 13%">
<col style="width: 15%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Assemblage</th>
<th style="text-align: left;">Diversity</th>
<th style="text-align: right;">Observed</th>
<th style="text-align: right;">Estimator</th>
<th style="text-align: right;">s.e.</th>
<th style="text-align: right;">LCL</th>
<th style="text-align: right;">UCL</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">750-850</td>
<td style="text-align: left;">Species richness</td>
<td style="text-align: right;">43.00</td>
<td style="text-align: right;">50.99</td>
<td style="text-align: right;">13.87</td>
<td style="text-align: right;">43.00</td>
<td style="text-align: right;">78.17</td>
</tr>
<tr class="even">
<td style="text-align: left;">750-850</td>
<td style="text-align: left;">Shannon diversity</td>
<td style="text-align: right;">20.73</td>
<td style="text-align: right;">21.19</td>
<td style="text-align: right;">0.61</td>
<td style="text-align: right;">19.98</td>
<td style="text-align: right;">22.39</td>
</tr>
<tr class="odd">
<td style="text-align: left;">750-850</td>
<td style="text-align: left;">Simpson diversity</td>
<td style="text-align: right;">14.67</td>
<td style="text-align: right;">14.84</td>
<td style="text-align: right;">0.62</td>
<td style="text-align: right;">13.61</td>
<td style="text-align: right;">16.06</td>
</tr>
<tr class="even">
<td style="text-align: left;">850-950</td>
<td style="text-align: left;">Species richness</td>
<td style="text-align: right;">57.00</td>
<td style="text-align: right;">63.12</td>
<td style="text-align: right;">10.34</td>
<td style="text-align: right;">57.00</td>
<td style="text-align: right;">83.38</td>
</tr>
<tr class="odd">
<td style="text-align: left;">850-950</td>
<td style="text-align: left;">Shannon diversity</td>
<td style="text-align: right;">28.12</td>
<td style="text-align: right;">28.83</td>
<td style="text-align: right;">0.77</td>
<td style="text-align: right;">27.32</td>
<td style="text-align: right;">30.35</td>
</tr>
<tr class="even">
<td style="text-align: left;">850-950</td>
<td style="text-align: left;">Simpson diversity</td>
<td style="text-align: right;">18.94</td>
<td style="text-align: right;">19.21</td>
<td style="text-align: right;">0.81</td>
<td style="text-align: right;">17.62</td>
<td style="text-align: right;">20.80</td>
</tr>
<tr class="odd">
<td style="text-align: left;">950-1050</td>
<td style="text-align: left;">Species richness</td>
<td style="text-align: right;">53.00</td>
<td style="text-align: right;">65.49</td>
<td style="text-align: right;">17.04</td>
<td style="text-align: right;">53.00</td>
<td style="text-align: right;">98.88</td>
</tr>
<tr class="even">
<td style="text-align: left;">950-1050</td>
<td style="text-align: left;">Shannon diversity</td>
<td style="text-align: right;">26.14</td>
<td style="text-align: right;">26.74</td>
<td style="text-align: right;">0.71</td>
<td style="text-align: right;">25.36</td>
<td style="text-align: right;">28.12</td>
</tr>
<tr class="odd">
<td style="text-align: left;">950-1050</td>
<td style="text-align: left;">Simpson diversity</td>
<td style="text-align: right;">19.40</td>
<td style="text-align: right;">19.64</td>
<td style="text-align: right;">0.70</td>
<td style="text-align: right;">18.27</td>
<td style="text-align: right;">21.01</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="partición-γ-α-β-con-inext.beta3d-estandarizada-por-cobertura" class="level2">
<h2 class="anchored" data-anchor-id="partición-γ-α-β-con-inext.beta3d-estandarizada-por-cobertura">Partición γ-α-β con <code>iNEXT.beta3D</code> (estandarizada por cobertura)</h2>
<p>Réplica del esquema de <code>datos_Osorio_2026.qmd</code> (sección de diversidad beta con <code>iNEXTbeta3D()</code>/<code>ggiNEXTbeta3D()</code>), adaptado de una comparación de 2 periodos (L vs.&nbsp;S) a nuestras 3 Franjas. A diferencia de la partición manual (más abajo, con pesos iguales sobre abundancias crudas), este método <strong>estandariza por cobertura de muestra</strong>, controlando diferencias de esfuerzo/tamaño de muestra entre unidades — es el resultado que se recomienda citar como principal.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-beta3d-franja" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-beta3d-franja-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="fase4_files/figure-html/fig-beta3d-franja-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-beta3d-franja-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Partición γ-α-β (iNEXT.beta3D, base=‘coverage’) entre las 3 Franjas del PNNT
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-beta3d-sitio-en-franja" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-beta3d-sitio-en-franja-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="fase4_files/figure-html/fig-beta3d-sitio-en-franja-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-beta3d-sitio-en-franja-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Partición γ-α-β (iNEXT.beta3D): Sitios dentro de cada Franja
</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>Lectura (con intervalos de confianza por bootstrap, n=30):</strong> la β entre Franjas (q=0: 1.29 [1.14–1.43]; q=1: 1.39 [1.37–1.41]; q=2: 1.48 [1.44–1.51]) es menor que la β entre Sitios dentro de Franja en los tres órdenes — el recambio ocurre principalmente a escala de Sitio, no de Franja. Sobre la Franja 750-850: en <strong>q=2</strong> tiene una β claramente menor (1.79 [1.70–1.87]) que 850-950 (2.30 [2.18–2.41]) y 950-1050 (2.30 [2.21–2.40]) — intervalos que <strong>no se solapan</strong>, la diferencia es sólida. En <strong>q=1</strong> la misma tendencia aparece pero de forma marginal (1.78 [1.71–1.84] vs.&nbsp;1.90 [1.83–1.97] en ambas) — los intervalos casi no se tocan. En <strong>q=0</strong> (riqueza) los intervalos de las tres Franjas se solapan ampliamente (1.65 [1.29–2.02]; 1.51 [1.25–1.78]; 1.73 [1.42–2.05]) — <strong>no</strong> hay evidencia estadística sólida de diferencia en riqueza pura del recambio entre Sitios, a pesar de que el valor puntual sugiera un patrón. Esta gradación por orden q es un matiz importante que la partición manual (sin bootstrap) no permitía ver: <strong>la Franja seca es más homogénea internamente en la fracción dominante del ensamblaje (q=2), pero no hay evidencia firme de que lo sea en riqueza cruda (q=0).</strong></p>
</section>
<section id="partición-γ-α-β-de-números-de-hill-verificación-cruzada-jost-2007-chao-et-al.-2012" class="level2">
<h2 class="anchored" data-anchor-id="partición-γ-α-β-de-números-de-hill-verificación-cruzada-jost-2007-chao-et-al.-2012">Partición γ-α-β de números de Hill — verificación cruzada (Jost 2007 / Chao et al.&nbsp;2012)</h2>
<p>Fórmulas cerradas, ponderación igual por unidad, <strong>sin</strong> estandarizar por cobertura (a diferencia de <code>iNEXT.beta3D</code> arriba). Se conserva como verificación independiente — los valores de β coinciden estrechamente con los de <code>iNEXT.beta3D</code> en q=1 y q=2 (diferencia &lt;0.02), y difieren algo más en q=0 por el efecto de la estandarización por cobertura sobre la riqueza.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Nivel 1 — α (Sitio), γ y β entre Sitios dentro de cada Franja</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Franja</th>
<th style="text-align: right;">q</th>
<th style="text-align: right;">gamma</th>
<th style="text-align: right;">alpha</th>
<th style="text-align: right;">beta</th>
<th style="text-align: right;">N</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">750-850</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">43.000</td>
<td style="text-align: right;">23.333</td>
<td style="text-align: right;">1.843</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="even">
<td style="text-align: left;">750-850</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">21.471</td>
<td style="text-align: right;">11.723</td>
<td style="text-align: right;">1.832</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="odd">
<td style="text-align: left;">750-850</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">15.576</td>
<td style="text-align: right;">8.389</td>
<td style="text-align: right;">1.857</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="even">
<td style="text-align: left;">850-950</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">57.000</td>
<td style="text-align: right;">31.667</td>
<td style="text-align: right;">1.800</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="odd">
<td style="text-align: left;">850-950</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">29.072</td>
<td style="text-align: right;">15.135</td>
<td style="text-align: right;">1.921</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="even">
<td style="text-align: left;">850-950</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">20.275</td>
<td style="text-align: right;">9.016</td>
<td style="text-align: right;">2.249</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="odd">
<td style="text-align: left;">950-1050</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">53.000</td>
<td style="text-align: right;">30.667</td>
<td style="text-align: right;">1.728</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="even">
<td style="text-align: left;">950-1050</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">26.913</td>
<td style="text-align: right;">14.012</td>
<td style="text-align: right;">1.921</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="odd">
<td style="text-align: left;">950-1050</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">20.371</td>
<td style="text-align: right;">8.865</td>
<td style="text-align: right;">2.298</td>
<td style="text-align: right;">3</td>
</tr>
</tbody>
</table>
</div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Nivel 2 — α (Franja), γ total y β entre Franjas</caption>
<thead>
<tr class="header">
<th style="text-align: right;">q</th>
<th style="text-align: right;">gamma</th>
<th style="text-align: right;">alpha</th>
<th style="text-align: right;">beta</th>
<th style="text-align: right;">N</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0</td>
<td style="text-align: right;">72.000</td>
<td style="text-align: right;">51.000</td>
<td style="text-align: right;">1.412</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="even">
<td style="text-align: right;">1</td>
<td style="text-align: right;">34.793</td>
<td style="text-align: right;">24.792</td>
<td style="text-align: right;">1.403</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2</td>
<td style="text-align: right;">26.027</td>
<td style="text-align: right;">17.393</td>
<td style="text-align: right;">1.496</td>
<td style="text-align: right;">3</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>Lectura:</strong> en los tres órdenes q, el recambio (β) <strong>entre Sitios dentro de una misma Franja</strong> (1.73–2.30) es mayor que el recambio <strong>entre Franjas</strong> (1.40–1.49) — la mayor parte de la heterogeneidad taxonómica del PNNT ocurre a escala de Sitio, no del gradiente hídrico/edáfico grueso representado por Franja. El recambio dentro de Franja es notablemente menor en 750-850 (β q=0 = 1.79) que en las otras dos (1.80–1.92) para riqueza, y esa brecha se amplía en q=2 (1.86 vs.&nbsp;2.25–2.30) — la Franja más seca no solo tiene menos especies (α y γ más bajos), sino sitios internamente más parecidos entre sí en términos de las especies dominantes. Esto es coherente con el hallazgo de <em>betadisper</em> más abajo.</p>
<blockquote class="blockquote">
<p>Nota metodológica: la síntesis jerárquica (α_Sitio,regional × β_Sitio(Franja) × β_Franja) reproduce γ_total de forma aproximada, no exacta (72.2 vs.&nbsp;72 para q=0), por el uso de promedios no ponderados de razones β entre Franjas de distinto tamaño interno — una propiedad conocida de la partición multiplicativa jerárquica con pesos iguales, no un error de cálculo.</p>
</blockquote>
</section>
<section id="permanova-anidada-betadisper-y-simper" class="level2">
<h2 class="anchored" data-anchor-id="permanova-anidada-betadisper-y-simper">PERMANOVA anidada, betadisper y SIMPER</h2>
<p>Se separan dos preguntas para evitar pseudorreplicación: el efecto <strong>Sitio dentro de Franja</strong> se prueba con las 225 Subparcelas (permutaciones restringidas dentro de cada Franja); el efecto <strong>Franja</strong> se prueba con los 9 Sitios como unidad (evita inflar los grados de libertad de un factor que solo tiene 3 réplicas reales).</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Permutation test for adonis under reduced model
Terms added sequentially (first to last)
Blocks:  strata 
Permutation: free
Number of permutations: 999

adonis2(formula = bray_sub ~ Sitio, data = meta_sub, permutations = 999, by = "terms", strata = meta_sub$Franja)
          Df SumOfSqs      R2      F Pr(&gt;F)    
Sitio      8   39.406 0.47006 23.949  0.001 ***
Residual 216   44.426 0.52994                  
Total    224   83.832 1.00000                  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Permutation test for adonis under reduced model
Terms added sequentially (first to last)
Permutation: free
Number of permutations: 999

adonis2(formula = bray_sitio ~ Franja, data = meta_sitio_df, permutations = 999, by = "terms")
         Df SumOfSqs      R2      F Pr(&gt;F)
Franja    2  0.51193 0.22211 0.8566  0.589
Residual  6  1.79291 0.77789              
Total     8  2.30484 1.00000              </code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: Distances
           Df  Sum Sq  Mean Sq F value   Pr(&gt;F)    
Groups      8 0.54856 0.068570  5.6371 1.67e-06 ***
Residuals 216 2.62745 0.012164                     
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: Distances
           Df  Sum Sq  Mean Sq F value   Pr(&gt;F)    
Groups      2 0.12854 0.064268  9.2228 0.000142 ***
Residuals 222 1.54698 0.006968                     
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>  Tukey multiple comparisons of means
    95% family-wise confidence level

Fit: aov(formula = distances ~ group, data = df)

$group
                         diff         lwr        upr     p adj
850-950-750-850   0.052933965  0.02076940 0.08509853 0.0003987
950-1050-750-850  0.048128568  0.01596401 0.08029313 0.0014578
950-1050-850-950 -0.004805397 -0.03696996 0.02735916 0.9338185</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-nmds" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-nmds-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="fase4_files/figure-html/fig-nmds-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-nmds-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: nMDS (Bray-Curtis) por Subparcela
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>$`750-850_850-950`
                           average     ratio     cumsum    p
Mimosa arenosa          0.07643810 0.9493911 0.08923264 0.01
Handroanthus billbergii 0.07019703 0.7769350 0.17117954 0.06
Platymiscium pinnatum   0.05891227 1.0660780 0.23995279 0.01
Brosimum alicastrum     0.05064867 0.5311439 0.29907926 0.91
Pterocarpus rohrii      0.04046434 0.6036707 0.34631669 0.44

$`750-850_950-1050`
                           average     ratio     cumsum    p
Mimosa arenosa          0.07377185 0.9679189 0.08185655 0.01
Triplaris americana     0.04997470 0.6293152 0.13730800 0.01
Brosimum alicastrum     0.04909876 0.5617417 0.19178752 0.94
Handroanthus billbergii 0.04800181 0.6543706 0.24504988 1.00
Guazuma ulmifolia       0.04685902 0.5537746 0.29704421 0.01

$`850-950_950-1050`
                           average     ratio    cumsum    p
Brosimum alicastrum     0.07802344 0.7636233 0.0893669 0.01
Handroanthus billbergii 0.07233336 0.8050698 0.1722165 0.02
Triplaris americana     0.04986464 0.6320621 0.2293307 0.01
Guazuma ulmifolia       0.04671384 0.5556665 0.2828360 0.01
Platymiscium pinnatum   0.04592535 0.8730906 0.3354382 0.85</code></pre>
</div>
</div>
<p><strong>Lectura conjunta:</strong></p>
<ul>
<li><strong>Sitio(Franja)</strong> es muy significativo (PERMANOVA F=23.98, R²=0.47, p=0.001) — la composición varía fuertemente entre Sitios dentro de una misma Franja. Pero <em>betadisper</em> por Sitio <strong>también</strong> es significativo (p&lt;0.001): parte de esa señal puede deberse a diferencias de dispersión (heterogeneidad interna), no solo de centroide — lectura estándar en ecología de comunidades, no invalida el resultado pero matiza su interpretación como “recambio puro”.</li>
<li><strong>Franja</strong>, probado correctamente a nivel de Sitio (n=9, evitando pseudorreplicación), <strong>no es significativo</strong> (F=0.86, R²=0.22, p=0.59) — con solo 3 réplicas por Franja el test tiene poca potencia. El nMDS muestra que 750-850 sí se separa visualmente de las otras dos, que se solapan bastante entre sí.</li>
<li><em>betadisper</em> por Franja <strong>sí es significativo</strong> (p&lt;0.001): 750-850 tiene <strong>menor dispersión</strong> que 850-950 y 950-1050 (que no difieren entre sí, Tukey p=0.92) — señal consistente con la partición γ-α-β (menor β dentro de esa Franja). Es un hallazgo real, aunque de naturaleza distinta a un efecto de composición promedio.</li>
<li>SIMPER identifica a <code>Mimosa arenosa</code>, <code>Handroanthus billbergii</code>, <code>Brosimum alicastrum</code>, <code>Platymiscium pinnatum</code> y <code>Triplaris americana</code> como las especies que más contribuyen a la disimilitud entre Franjas — coherente con el IVI (varias de estas ya destacaban como las más importantes por Sitio).</li>
</ul>
</section>
<section id="manyglm-binomial-negativa-principal-y-poisson-sensibilidad" class="level2">
<h2 class="anchored" data-anchor-id="manyglm-binomial-negativa-principal-y-poisson-sensibilidad">manyGLM — Binomial Negativa (principal) y Poisson (sensibilidad)</h2>
<p><strong>Decisión (confirmada por la directora, 12-sep-2026):</strong> se reporta la <strong>Binomial Negativa (BN) como modelo principal</strong>, con Poisson como análisis de sensibilidad — justificado por la relación media-varianza de abajo.</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="fase4_files/figure-html/manyglm-meanvar-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Relación media-varianza por especie (225 Subparcelas × 72 especies)</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>Lectura de la relación media-varianza:</strong> los puntos seleccionados forman una línea razonablemente recta en escala log-log, pero <strong>por encima</strong> de la pendiente 1:1 que asumiría Poisson (varianza = media) — la varianza crece más rápido que la media a través de las 72 especies. Esto es sobredispersión clásica de conteos ecológicos (muchos ceros + unas pocas especies muy abundantes) y confirma que <strong>BN es la elección apropiada</strong>: Poisson subestimaría los errores estándar e infla artificialmente la significancia.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Deviance Table

Model: Y ~ Franja + Sitio

Multivariate test:
            Res.Df Df.diff  Dev Pr(&gt;Dev)   
(Intercept)    224                         
Franja         222       2 1167    0.002 **
Sitio          216       8 2734    0.002 **
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
Arguments:
 Test statistics calculated assuming uncorrelated response (for faster computation) 
 P-value calculated using 499 iterations via PIT-trap resampling.</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Deviance Table

Model: Y ~ Franja + Sitio

Multivariate test:
            Res.Df Df.diff  Dev Pr(&gt;Dev)   
(Intercept)    224                         
Franja         222       2 2764    0.002 **
Sitio          216       8 5195    0.002 **
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
Arguments:
 Test statistics calculated assuming uncorrelated response (for faster computation) 
 P-value calculated using 499 iterations via PIT-trap resampling.</code></pre>
</div>
</div>
<p><strong>Lectura:</strong> con BN (modelo principal), tanto <strong>Franja</strong> (p=0.002) como <strong>Sitio(Franja)</strong> (p=0.002) son significativos sobre el patrón conjunto de abundancias por especie — a diferencia de la PERMANOVA de Franja (no significativa, ver sección anterior). Poisson (sensibilidad) da la misma conclusión cualitativa, pero con estadísticos de devianza más grandes (esperable: al ignorar la sobredispersión, infla la señal) — otra razón para no reportarlo como resultado principal. La diferencia con la PERMANOVA <strong>no es una contradicción</strong>: manyGLM usa las 225 Subparcelas con el modelo anidado correcto (Tipo I, mucha más potencia que n=9 Sitios), y modela abundancia media por especie (sensible a cambios de abundancia total, no solo de composición relativa como Bray-Curtis).</p>
<blockquote class="blockquote">
<p><strong>Nota de redacción — pendiente de tu confirmación:</strong> dos borradores de cómo presentar esta comparación PERMANOVA-vs-manyGLM en el manuscrito (uno extenso para Resultados, uno breve para nota metodológica) se compartieron aparte para tu revisión; una vez elijas o ajustes uno, se inserta aquí en la versión final.</p>
</blockquote>
</section>
<section id="síntesis-de-fase-4-y-decisiones-pendientes-antes-de-fase-5" class="level2">
<h2 class="anchored" data-anchor-id="síntesis-de-fase-4-y-decisiones-pendientes-antes-de-fase-5">Síntesis de Fase 4 y decisiones pendientes antes de Fase 5</h2>
<p><strong>Lo que queda sólido y reproducible:</strong></p>
<ul>
<li>Diseño Sitio(Franja) confirmado como viable (9/3/225, perfectamente balanceado) — no fue necesario colapsar a un nivel más simple.</li>
<li>Cobertura de muestra muy alta (&gt;97 %) en todas las unidades — las comparaciones de diversidad no están sesgadas por esfuerzo de muestreo.</li>
<li>Señal consistente, con matices por orden <em>q</em>, de que la Franja <strong>750-850 es más homogénea internamente</strong> que las otras dos: en la fracción dominante del ensamblaje (q=2) la diferencia es sólida y triangulada por tres vías (<code>iNEXT.beta3D</code> con IC no solapados, betadisper significativo, y menor pendiente del RAD/radfit); en riqueza cruda (q=0) el patrón es solo sugestivo (intervalos de bootstrap solapados) — <strong>no sobre-generalizar</strong> este hallazgo a todos los órdenes de diversidad.</li>
<li>El bloque multivariado completo (PERMANOVA nested, betadisper, SIMPER, manyGLM Poisson+BN) corrió sobre datos reales, con las 225 Subparcelas como unidad de réplica correcta.</li>
</ul>
<p><strong>Lo que sigue siendo una advertencia activa, no resuelta:</strong></p>
<ul>
<li>La PERMANOVA de Franja no fue significativa (n=3 réplicas, poca potencia) mientras que manyGLM sí lo fue — ambos resultados son válidos pero responden preguntas distintas; hay que decidir cómo se presentan juntos en Resultados sin que parezcan contradictorios.</li>
<li>La PERMANOVA de Sitio(Franja) coincide con un betadisper significativo — matizar la interpretación como composición <strong>y</strong> dispersión, no solo recambio puro.</li>
<li>16 individuos bajo el umbral de 10 cm DAP (Sitio QRD) — pendiente de decisión: mantener (como aquí) o recortar estrictamente en 10.00 cm.</li>
</ul>
<p><strong>Para confirmar con la directora / el equipo antes de avanzar:</strong></p>
<ol type="1">
<li>¿Se acepta BN como modelo principal de manyGLM (Poisson como sensibilidad), dado el patrón de sobredispersión esperable en conteos ecológicos?</li>
<li>¿Cómo se prefiere presentar la discrepancia PERMANOVA-Franja (n.s.) vs.&nbsp;manyGLM-Franja (p=0.002) en el manuscrito — como matiz metodológico explícito, o priorizando una de las dos pruebas como resultado “oficial”?</li>
<li>¿Se mantienen los 16 individuos de QRD bajo el umbral de 10 cm, o se recortan estrictamente?</li>
</ol>
<p><strong>Qué hereda Fase 5:</strong> la matriz especie × Sitio y especie × Subparcela de aquí son insumo directo para repetir este mismo marco (Hill/iNEXT, partición γ-α-β) con la matriz de distancia <strong>funcional</strong> (Gower, Fase 3), para comparación directa TD vs.&nbsp;FD.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>